import json, random
from datetime import datetime, timedelta

sd = datetime(2026, 6, 15)
ed = datetime(2026, 6, 29)

def rd():
    return (sd + timedelta(days=random.randint(0, (ed-sd).days))).strftime("%Y-%m-%d")

def bt(idx, raw, cat, all_names):
    tid, name, desc, url, price, isf, tags, rating = raw
    tags = list(dict.fromkeys(tags))[:6]
    while len(tags) < 3: tags.append("AI工具")
    screenshots = [f"https://picsum.photos/seed/{tid}1/800/500", f"https://picsum.photos/seed/{tid}2/800/500"]
    features = [
        f"基于{name}核心技术的智能生成",
        "支持多语言和跨平台使用",
        "高效的内容处理和质量优化",
        "用户友好的界面和操作流程",
        "强大的API和第三方集成能力",
        "持续更新和活跃的社区支持"
    ]
    comp_pool = [n for n in all_names if n != name]
    competitors = random.sample(comp_pool, 3)
    if cat == "ai-audio":
        use_cases = ["音乐创作和歌曲制作", "播客和视频配音", "会议记录和语音转文本", "游戏和影视音效设计", "语音克隆和个性化声音"]
    else:
        use_cases = ["营销文案和广告创作", "博客文章和SEO内容", "学术论文和研究报告", "社交媒体内容管理", "创意写作和故事构思"]
    ol = desc[:30] + "..." if len(desc) > 30 else desc
    seo_title = f"{name} - {ol} | AI Navigator Pro"
    seo_desc = f"探索{name}的强大功能。{desc[:70]}..."
    return {
        "id": tid, "name": name, "logo": f"https://api.dicebear.com/7.x/shapes/svg?seed={tid}",
        "description": desc, "url": url, "price": price, "isFree": isf, "tags": tags,
        "category": cat, "rating": round(rating, 1), "updatedAt": rd(),
        "screenshots": screenshots, "features": features, "competitors": competitors,
        "useCases": use_cases, "seoTitle": seo_title, "seoDescription": seo_desc,
        "featured": idx < 5, "trending": idx < 10, "views": random.randint(5000, 150000)
    }

audio_raw = [
("suno","Suno","AI音乐生成平台，通过文本提示快速创作完整歌曲，支持多种风格和语言。","https://suno.com","免费 + $10/月",True,["AI音乐","歌曲生成","文本转音乐","多风格","多语言"],4.9),
("udio","Udio","高质量AI音乐生成工具，可创建带人声的完整曲目，支持精细风格控制。","https://udio.com","免费 + $8/月",True,["AI音乐","人声生成","风格控制","音乐创作","专业级"],4.8),
("stable-audio","Stable Audio","Stability AI推出的专业音频生成模型，支持音效和音乐创作，开源生态丰富。","https://www.stableaudio.com","免费 + $11.99/月",True,["AI音乐","音效生成","开源","专业级","Stability AI"],4.6),
("murf-ai","Murf AI","逼真的AI文本转语音平台，提供120多种声音，适用于视频配音和电子学习。","https://murf.ai","免费 + $29/月",True,["TTS","配音","视频制作","电子学习","多语言"],4.7),
("elevenlabs","ElevenLabs","业界领先的AI语音合成平台，支持超逼真语音克隆和多语言情感表达。","https://elevenlabs.io","免费 + $5/月",True,["语音克隆","TTS","多语言","情感语音","AI配音"],4.9),
("play-ht","Play.ht","多功能AI语音生成平台，提供900多种声音，支持实时语音克隆和播客制作。","https://play.ht","免费 + $39/月",True,["TTS","语音克隆","播客","多声音","实时生成"],4.6),
("wellsaid-labs","WellSaid Labs","企业级AI语音合成解决方案，提供高品质、一致性的品牌声音。","https://wellsaidlabs.com","$49/月",False,["企业级","TTS","品牌声音","高质量","一致性"],4.5),
("descript","Descript","一体化音视频编辑平台，集成AI语音克隆Overdub和自动转录功能。","https://www.descript.com","免费 + $15/月",True,["音视频编辑","语音克隆","自动转录","播客","视频制作"],4.7),
("otter-ai","Otter.ai","智能会议转录和笔记工具，实时记录、摘要和分享会议内容。","https://otter.ai","免费 + $16.99/月",True,["会议转录","实时笔记","语音识别","协作","摘要"],4.5),
("fireflies-ai","Fireflies.ai","AI会议助手，自动录制、转录和分析会议对话，生成行动项。","https://fireflies.ai","免费 + $10/月",True,["会议助手","自动转录","对话分析","CRM集成","行动项"],4.6),
("tldv","tl;dv","智能会议录制工具，支持Zoom和Google Meet，自动生成时间戳和摘要。","https://tldv.io","免费 + $18/月",True,["会议录制","时间戳","摘要","Zoom集成","团队协作"],4.4),
("rev-ai","Rev AI","高精度AI语音转文本API，支持异步和实时转录，准确率达99%。","https://www.rev.ai","按量付费",False,["语音转文本","API","高精度","实时转录","异步转录"],4.5),
("assemblyai","AssemblyAI","开发者友好的语音AI平台，提供转录、摘要、内容审核等API服务。","https://www.assemblyai.com","按量付费",False,["语音AI","API","开发者","转录","摘要"],4.6),
("deepgram","Deepgram","高性能语音AI平台，以极低延迟和成本提供语音转文本和文本转语音服务。","https://deepgram.com","免费 + $200/月起",True,["语音转文本","TTS","低延迟","API","高性能"],4.7),
("speechmatics","Speechmatics","全球领先的语音识别技术，支持50多种语言和口音的准确转录。","https://www.speechmatics.com","按量付费",False,["语音识别","多语言","口音识别","企业级","API"],4.4),
("amazon-polly","Amazon Polly","AWS云文本转语音服务，提供逼真的神经网络语音和多种语言支持。","https://aws.amazon.com/polly/","按量付费",False,["TTS","AWS","云语音","神经网络","多语言"],4.3),
("google-cloud-text-to-speech","Google Cloud Text-to-Speech","谷歌云平台TTS服务，支持WaveNet和神经网络语音生成技术。","https://cloud.google.com/text-to-speech","按量付费",False,["TTS","Google Cloud","WaveNet","神经网络","API"],4.5),
("azure-speech","Azure Speech","微软Azure语音服务，集成语音识别、合成、翻译和说话人识别功能。","https://azure.microsoft.com/services/cognitive-services/speech-services/","按量付费",False,["语音服务","微软","语音识别","TTS","翻译"],4.5),
("ibm-watson-speech","IBM Watson Speech","IBM企业级语音转文本和文本转语音解决方案，支持多种语言。","https://www.ibm.com/cloud/watson-speech-to-text","按量付费",False,["企业级","IBM","语音转文本","TTS","多语言"],4.2),
("resemble-ai","Resemble AI","实时AI语音克隆和生成平台，支持语音到语音转换和情感控制。","https://www.resemble.ai","按量付费",False,["语音克隆","实时生成","情感控制","语音转换","游戏"],4.6),
("coqui","Coqui","开源深度学习语音技术工具包，支持TTS、语音克隆和语音转文本，社区驱动。","https://github.com/coqui-ai/TTS","免费",True,["开源","深度学习","TTS","语音克隆","社区"],4.3),
("bark","Bark","Suno推出的开源文本转语音和音频生成模型，支持多语言和笑声等非语言音效。","https://github.com/suno-ai/bark","免费",True,["开源","TTS","非语言音效","多语言","Suno"],4.5),
("styletts-2","StyleTTS 2","开源风格化文本转语音模型，实现零样本语音克隆和自然风格迁移。","https://github.com/yl4579/StyleTTS2","免费",True,["开源","零样本克隆","风格迁移","TTS","研究"],4.4),
("xtts","XTTS","Coqui推出的高质量语音克隆TTS模型，支持多语言跨语言语音合成。","https://github.com/coqui-ai/TTS","免费",True,["语音克隆","多语言","跨语言","TTS","开源"],4.5),
("fish-speech","Fish Speech","2024年新兴开源TTS模型，支持多语言和高质量语音克隆，推理速度快。","https://github.com/fishaudio/fish-speech","免费",True,["开源","快速推理","多语言","语音克隆","新兴"],4.3),
("gpt-sovits","GPT-SoVITS","开源低成本AI声音克隆工具，支持少量样本训练，社区活跃度极高。","https://github.com/RVC-Boss/GPT-SoVITS","免费",True,["开源","低成本","少样本","声音克隆","社区热门"],4.6),
("rvc","RVC","实时语音转换开源项目，支持将声音转换为其他音色，广泛用于直播和娱乐。","https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI","免费",True,["开源","实时转换","直播","娱乐","社区热门"],4.4),
("so-vits-svc","So-VITS-SVC","基于VITS的singing voice conversion开源项目，支持AI翻唱和音色转换。","https://github.com/svc-develop-team/so-vits-svc","免费",True,["开源","AI翻唱","音色转换","VITS","音乐"],4.3),
("weights-gg","Weights.gg","AI语音模型分享和运行平台，用户可以创建和分享自定义AI声音。","https://www.weights.gg","免费 + $9.99/月",True,["语音模型","社区","自定义声音","分享平台","AI翻唱"],4.2),
("voicemod","Voicemod","实时AI变声器，适用于游戏和直播，提供多种音效和自定义声音面板。","https://www.voicemod.net","免费 + $20/年",True,["变声器","实时","游戏","直播","音效"],4.3),
("voicify","Voicify AI","AI音乐翻唱平台，用户可以使用AI声音模型翻唱流行歌曲。","https://www.voicify.ai","$7.99/月",False,["AI翻唱","音乐","声音模型","娱乐","社区"],4.1),
("lalal-ai","LALAL.ai","高精度AI音轨分离工具，可提取人声、鼓点、贝斯等单独音轨。","https://www.lalal.ai","免费 + $15/次",True,["音轨分离","人声提取","音乐制作","高精度","批量处理"],4.7),
("phonicmind","PhonicMind","AI人声和伴奏分离服务，支持高质量音轨提取和卡拉OK制作。","https://phonicmind.com","$9.99/月",False,["音轨分离","伴奏提取","卡拉OK","音乐制作","高质量"],4.2),
("splitter-ai","Splitter.ai","AI音频分离工具，可将歌曲拆分为人声、鼓、贝斯和其他乐器音轨。","https://www.splitter.ai","免费 + $9.99/月",True,["音轨分离","乐器提取","音乐制作","免费","多音轨"],4.0),
("bandlab","BandLab","免费在线音乐制作和协作平台，集成AI母带处理和音效工具。","https://www.bandlab.com","免费 + $7.99/月",True,["音乐制作","协作","在线DAW","AI母带","免费"],4.5),
("aiva","AIVA","AI音乐作曲助手，专为电影、游戏和广告创作情感丰富的原创配乐。","https://www.aiva.ai","免费 + $15/月",True,["AI作曲","配乐","电影音乐","游戏音乐","情感音乐"],4.4),
("amper-music","Amper Music","AI音乐创作平台，为视频、游戏和广告提供免版税原创音乐。","https://www.ampermusic.com","按量付费",False,["AI音乐","免版税","视频配乐","游戏音乐","原创"],4.0),
("boomy","Boomy","AI音乐生成和社区平台，用户可快速创作歌曲并发布到流媒体平台赚钱。","https://boomy.com","免费 + $9.99/月",True,["AI音乐","歌曲创作","流媒体发布","赚钱","社区"],4.1),
("soundraw","Soundraw","AI免版税音乐生成器，为创作者提供可定制的原创背景音乐。","https://soundraw.io","$16.99/月",False,["免版税","背景音乐","可定制","创作者","AI音乐"],4.5),
("ecrett-music","Ecrett Music","AI背景音乐生成工具，专为视频创作者提供免版税配乐。","https://ecrettmusic.com","$4.99/月",False,["背景音乐","免版税","视频配乐","AI音乐","创作者"],4.0),
("mubert","Mubert","AI生成式音乐流媒体平台，提供实时、免版税的AI音乐用于商业用途。","https://mubert.com","免费 + $14/月",True,["生成式音乐","流媒体","免版税","商业用途","实时音乐"],4.3),
("endlesss","Endlesss","协作式AI音乐创作应用，支持多人实时即兴创作和AI辅助混音。","https://endlesss.fm","免费 + $6.99/月",True,["协作","实时创作","即兴","AI混音","移动应用"],4.1),
("audiobox","Audiobox","Meta推出的开源AI音频生成模型，支持语音和音效生成，研究导向。","https://audiobox.metademolab.com","免费",True,["Meta","开源","研究","语音生成","音效生成"],4.4),
("speechify","Speechify","AI文本转语音阅读器，支持将任何文本转换为自然语音，帮助阅读障碍用户。","https://speechify.com","免费 + $139/年",True,["TTS","阅读辅助","自然语音","多平台","教育"],4.6),
("natural-reader","Natural Reader","在线文本转语音工具，支持多种自然声音和文档格式转换。","https://www.naturalreaders.com","免费 + $9.99/月",True,["TTS","文档转换","自然声音","在线工具","教育"],4.2),
("murf-studio","Murf Studio","Murf AI的专业语音制作工作室，支持团队协作和高级音频编辑。","https://murf.ai/studio","$29/月",False,["语音制作","团队协作","音频编辑","专业","TTS"],4.5),
("listnr","Listnr","AI文本转语音平台，专为播客和有声书制作提供900多种声音。","https://listnr.tech","免费 + $19/月",True,["TTS","播客","有声书","多声音","内容创作"],4.1),
("lovo-ai","LOVO AI","AI语音生成和语音克隆平台，提供500多种声音和情感表达控制。","https://lovo.ai","免费 + $24/月",True,["TTS","语音克隆","情感表达","多声音","视频配音"],4.3),
("altered-studio","Altered Studio","AI语音编辑软件，支持语音克隆、降噪和声音风格转换。","https://www.altered.ai","$14/月",False,["语音编辑","语音克隆","降噪","风格转换","专业"],4.2),
("kits-ai","Kits AI","AI音乐制作平台，提供AI人声、乐器模型和音频处理工具。","https://www.kits.ai","免费 + $9.99/月",True,["AI人声","乐器模型","音乐制作","音频处理","创作者"],4.3),
("voice-ai","Voice.ai","实时AI变声和语音克隆桌面应用，支持游戏和直播场景。","https://voice.ai","免费 + $29/终身",True,["变声","实时","桌面应用","游戏","直播"],4.0),
("meta-tts","Meta TTS","Meta AI推出的文本转语音研究模型，支持多语言高质量语音合成。","https://ai.meta.com","免费",True,["Meta","研究","TTS","多语言","开源"],4.3),
("openai-tts","OpenAI TTS","OpenAI推出的文本转语音API，提供自然流畅的语音合成能力。","https://platform.openai.com","按量付费",False,["OpenAI","TTS","API","自然语音","开发者"],4.6),
("openai-whisper","OpenAI Whisper","OpenAI开源的通用语音识别模型，支持99种语言的转录和翻译。","https://github.com/openai/whisper","免费",True,["开源","语音识别","多语言","OpenAI","转录"],4.8),
("whisper-jax","Whisper JAX","基于JAX优化的Whisper实现，推理速度提升70倍，支持大规模部署。","https://github.com/sanchit-gandhi/whisper-jax","免费",True,["开源","JAX","优化","快速推理","Whisper"],4.2),
("faster-whisper","Faster Whisper","使用CTranslate2优化的Whisper版本，推理效率大幅提升。","https://github.com/SYSTRAN/faster-whisper","免费",True,["开源","优化","Whisper","高效","转录"],4.5),
("insanely-fast-whisper","Insanely Fast Whisper","基于Optimum和Transformers的极速Whisper实现，支持批处理。","https://github.com/Vaibhavs10/insanely-fast-whisper","免费",True,["开源","极速","Whisper","批处理","优化"],4.3),
("whisper-x","WhisperX","Whisper增强版，支持单词级时间戳、说话人分离和批处理优化。","https://github.com/m-bain/whisperX","免费",True,["开源","时间戳","说话人分离","Whisper","优化"],4.6),
("nemo","NVIDIA NeMo","NVIDIA的会话式AI工具包，包含语音识别、TTS和自然语言处理模型。","https://developer.nvidia.com/nemo","免费",True,["NVIDIA","开源","语音识别","TTS","开发者"],4.4),
("nvidia-ace","NVIDIA ACE","NVIDIA AI角色引擎，为游戏和虚拟世界提供实时语音和动画生成。","https://developer.nvidia.com/ace","按量付费",False,["NVIDIA","游戏","实时","虚拟角色","语音动画"],4.5),
("respeecher","Respeecher","好莱坞级AI语音克隆技术，为影视和游戏提供逼真的声音重建。","https://www.respeecher.com","按项目报价",False,["好莱坞","影视","语音克隆","专业级","游戏"],4.6),
("sonantic","Sonantic","AI语音合成平台，专注于为游戏和电影提供情感丰富的角色声音。","https://www.sonantic.io","按量付费",False,["游戏","电影","情感语音","角色声音","专业"],4.3),
("charactr","Charactr","AI语音和虚拟形象平台，为创作者提供可定制的数字角色声音。","https://www.charactr.com","按量付费",False,["虚拟形象","数字角色","TTS","创作者","可定制"],4.0),
("replica-studios","Replica Studios","AI语音演员平台，为游戏和动画提供富有表现力的角色配音。","https://replicastudios.com","免费 + $24/月",True,["游戏配音","角色声音","动画","表现力","创作者"],4.2),
("mindos-ai","MindOS AI","2025年新兴的AI语音助手平台，支持多轮对话和知识库集成。","https://mindos.ai","免费 + $19/月",True,["新兴","语音助手","对话AI","知识库","多轮对话"],4.0),
("hume-ai","Hume AI","情感智能AI平台，通过语音分析情感状态，提供共情式语音交互。","https://hume.ai","按量付费",False,["情感AI","语音分析","共情","研究","开发者"],4.5),
("sesame","Sesame","2025年推出的超逼真AI语音对话模型，实现近乎真人的自然对话体验。","https://sesame.com","免费",True,["新兴","超逼真","对话AI","自然语音","2025"],4.7),
("kyutai","Kyutai","法国非营利AI实验室推出的开源语音模型，强调开放和透明的AI研究。","https://kyutai.org","免费",True,["开源","非营利","法国","语音模型","研究"],4.3),
("moshi","Moshi","Kyutai推出的实时语音对话AI，支持全双工语音交互，完全开源。","https://moshi.kyutai.org","免费",True,["开源","实时对话","全双工","Kyutai","新兴"],4.4),
("speechmatics-flow","Speechmatics Flow","Speechmatics推出的实时语音理解API，支持流式转录和分析。","https://www.speechmatics.com","按量付费",False,["实时","流式","API","语音理解","企业级"],4.3),
("canopy-labs","Canopy Labs","2025年新兴的AI语音基础设施提供商，专注于可扩展语音AI部署。","https://canopylabs.ai","按量付费",False,["新兴","基础设施","可扩展","语音AI","企业级"],4.1),
("cartesia","Cartesia","2025年推出的高效语音AI平台，以极低延迟提供高质量语音合成。","https://cartesia.ai","按量付费",False,["新兴","低延迟","高质量","语音合成","2025"],4.4),
("rime","Rime","AI语音合成API，专注于为开发者和企业提供快速、可定制的TTS服务。","https://rime.ai","按量付费",False,["API","开发者","可定制","TTS","快速"],4.2),
("play-ai","Play AI","Play.ht推出的对话式AI语音代理平台，支持构建语音客服和助手。","https://play.ai","$39/月",False,["语音代理","对话AI","客服","TTS","自动化"],4.3),
("bland-ai","Bland AI","2025年热门的AI电话呼叫平台，可构建自动拨打电话的AI代理。","https://www.bland.ai","按量付费",False,["新兴","电话AI","AI代理","自动化","2025"],4.5),
("retell-ai","Retell AI","AI语音对话平台，专为构建自然流畅的客户服务语音机器人设计。","https://www.retell.ai","按量付费",False,["语音对话","客服","语音机器人","自然语言","企业"],4.4),
("vapi","Vapi","开发者友好的AI语音助手API，支持快速构建和部署语音AI应用。","https://vapi.ai","按量付费",False,["API","开发者","语音助手","快速部署","构建工具"],4.3),
("pipecat","Pipecat","开源AI语音和多模态对话框架，支持构建实时语音AI应用。","https://github.com/pipecat-ai/pipecat","免费",True,["开源","框架","多模态","实时","开发者"],4.2),
("daily-bots","Daily Bots","Daily.co推出的AI语音机器人平台，支持实时语音和视频AI代理。","https://www.daily.co","按量付费",False,["实时","视频AI","语音机器人","平台","开发者"],4.1),
("symbl-ai","Symbl.ai","对话智能API平台，提供实时语音分析、情感检测和话题提取。","https://symbl.ai","按量付费",False,["对话智能","实时分析","情感检测","API","企业"],4.0),
("voiceflow","Voiceflow","AI语音和聊天代理设计平台，支持构建语音应用的原型和部署。","https://www.voiceflow.com","免费 + $50/月",True,["设计平台","语音应用","聊天代理","原型","协作"],4.4),
("spitch","Spitch","企业级语音AI解决方案提供商，专注于银行和保险行业的语音自动化。","https://spitch.ch","按项目报价",False,["企业级","银行","保险","语音自动化","专业"],4.0),
("uniphore","Uniphore","企业对话自动化平台，集成语音AI、计算机视觉和生成式AI技术。","https://www.uniphore.com","按项目报价",False,["企业级","对话自动化","语音AI","计算机视觉","生成式AI"],4.2),
("obsidian-voice","Obsidian Voice","2025年新兴的AI语音笔记工具，支持语音转文本和AI摘要整理。","https://obsidianvoice.ai","免费 + $8/月",True,["新兴","语音笔记","AI摘要","知识管理","2025"],4.1),
("snipd","Snipd","AI播客播放器，自动为播客内容生成转录、摘要和精彩片段。","https://www.snipd.com","免费 + $8.99/月",True,["播客","转录","摘要","精彩片段","AI播放"],4.3),
("memo-ai","Memo AI","AI语音笔记和会议助手，支持实时转录、翻译和知识库构建。","https://memoai.info","免费 + $12/月",True,["语音笔记","实时转录","翻译","知识库","会议"],4.2),
("superwhisper","Superwhisper","Mac本地AI语音转文本工具，支持离线运行和高精度转录。","https://superwhisper.com","免费 + $9/月",True,["Mac","本地运行","离线","高精度","语音转文本"],4.4),
("macwhisper","MacWhisper","专为Mac设计的Whisper客户端，提供友好的UI和本地转录功能。","https://goodsnooze.com/macwhisper/","免费 + €15",True,["Mac","Whisper","本地","UI友好","转录"],4.5),
("auphonic","Auphonic","AI音频后期处理平台，自动完成母带处理、降噪和音量平衡。","https://auphonic.com","免费 + $11/月",True,["母带处理","降噪","音量平衡","后期处理","播客"],4.4),
("landr","LANDR","AI母带处理和音乐分发平台，为独立音乐人提供专业级音频优化。","https://www.landr.com","$19/月",False,["母带处理","音乐分发","独立音乐人","专业级","音频优化"],4.3),
("emastered","eMastered","AI音频母带处理工具，由格莱美获奖工程师参与训练算法。","https://emastered.com","$14/月",False,["母带处理","格莱美","音频优化","专业","音乐"],4.2),
("chirp","Chirp","2025年新兴的AI音效生成工具，支持通过文本创建游戏和影视音效。","https://chirp.audio","免费 + $12/月",True,["新兴","音效生成","游戏","影视","2025"],4.1),
("myvocal-ai","MyVocal AI","AI翻唱和声音克隆平台，用户可以用自己的声音翻唱任意歌曲。","https://myvocal.ai","免费 + $9.99/月",True,["AI翻唱","声音克隆","音乐","娱乐","社交"],4.0),
("revocalize","Revocalize AI","AI声音转换和音乐制作工具，支持将歌声转换为不同音色。","https://revocalize.ai","$19/月",False,["声音转换","音乐制作","歌声转换","音色","专业"],4.1),
("ace-studio","ACE Studio","AI歌声合成软件，支持虚拟歌手和AI辅助音乐制作。","https://ace-studio.timedomain.cn","免费 + $15/月",True,["歌声合成","虚拟歌手","音乐制作","AI辅助","中文支持"],4.3),
("synthesizer-v","Synthesizer V","先进的AI歌声合成引擎，提供自然流畅的虚拟歌手演唱效果。","https://dreamtonics.com/synthesizerv/","$89",False,["歌声合成","虚拟歌手","自然","音乐制作","专业"],4.6),
("vocaloid6","Vocaloid 6","雅马哈最新AI歌声合成技术，支持更自然的歌唱表达和跨语言演唱。","https://www.vocaloid.com","$225",False,["歌声合成","雅马哈","跨语言","虚拟歌手","专业"],4.5),
("cevio-ai","CeVIO AI","日本先进的AI歌声和语音合成软件，支持歌唱和说话两种模式。","https://cevio.jp","按产品定价",False,["歌声合成","语音合成","日本","多模式","虚拟歌手"],4.4),
("neutone","Neutone","AI音频插件平台，为音乐制作人提供实时AI音效处理工具。","https://neutone.ai","免费 + $19/月",True,["音频插件","实时","音效处理","音乐制作","AI效果"],4.0),
("goyo","GOYO","AI降噪插件，专为播客和直播设计，提供实时语音增强和背景噪音消除。","https://goyo.app","$49",False,["降噪","实时","播客","直播","语音增强"],4.2),
("krisp","Krisp","AI降噪应用，实时消除会议和通话中的背景噪音和回声。","https://krisp.ai","免费 + $8/月",True,["降噪","实时","会议","通话","回声消除"],4.5),
("nvidia-rtx-voice","NVIDIA RTX Voice","NVIDIA推出的AI降噪工具，利用GPU实时消除背景噪音。","https://www.nvidia.com","免费",True,["NVIDIA","降噪","GPU","实时","免费"],4.3),
("iris-audio","Iris Audio","2025年新兴的AI空间音频工具，支持生成3D沉浸式音效。","https://irisaudio.tech","免费 + $20/月",True,["新兴","空间音频","3D音效","沉浸式","2025"],4.0),
("audio-design-desk","Audio Design Desk","AI驱动的影视音效设计平台，支持智能音效匹配和同步。","https://audiodesigndesk.com","免费 + $14.99/月",True,["影视音效","智能匹配","同步","AI驱动","创意"],4.2),
("beatoven-ai","Beatoven.ai","AI免版税音乐生成器，为视频创作者提供情感驱动的背景音乐。","https://www.beatoven.ai","免费 + $6/月",True,["免版税","背景音乐","情感驱动","视频","AI音乐"],4.3),
("soundful","Soundful","AI音乐生成平台，支持创建可商用的高品质音乐和循环素材。","https://soundful.com","免费 + $9.99/月",True,["AI音乐","可商用","循环素材","创作者","高品质"],4.1),
("evoke-music","Evoke Music","AI免版税音乐库，为内容创作者提供按情绪和风格筛选的原创音乐。","https://evokemusic.ai","$8/月",False,["免版税","音乐库","情绪筛选","内容创作","原创"],4.0),
("udio-pro","Udio Pro","Udio的专业级音乐制作扩展，提供更高质量的音频导出和精细控制。","https://udio.com/pro","$24/月",False,["专业级","高质量","精细控制","音乐制作","扩展"],4.7),
]

writing_raw = [
("jasper","Jasper","企业级AI写作助手，支持营销文案、博客、邮件等长篇内容创作，集成SEO优化工具。","https://www.jasper.ai","$49/月",False,["企业级","营销文案","SEO","长篇内容","团队协作"],4.6),
("copy-ai","Copy.ai","智能营销文案生成平台，提供90多种内容模板，适合社交媒体和广告创作。","https://www.copy.ai","免费 + $49/月",True,["营销文案","社交媒体","广告","模板","内容创作"],4.5),
("writesonic","Writesonic","多功能AI写作平台，集成ChatGPT和Google搜索，支持SEO优化文章创作。","https://writesonic.com","免费 + $19/月",True,["SEO优化","文章创作","多功能","集成搜索","营销"],4.4),
("rytr","Rytr","高性价比AI写作助手，支持40多种使用场景和30多种语言的内容生成。","https://rytr.me","免费 + $9/月",True,["高性价比","多语言","多场景","内容生成","预算友好"],4.2),
("wordtune","Wordtune","AI写作优化工具，专注于改写、润色和优化现有文本，提升表达清晰度。","https://www.wordtune.com","免费 + $9.99/月",True,["改写","润色","优化","表达清晰","写作辅助"],4.3),
("quillbot","QuillBot","AI改写和语法检查工具，提供同义词替换、总结和引文生成功能。","https://quillbot.com","免费 + $19.95/月",True,["改写","语法检查","同义词","总结","学术写作"],4.5),
("grammarly","Grammarly","全球领先的AI写作辅助工具，提供语法检查、风格建议和语气调整功能。","https://www.grammarly.com","免费 + $12/月",True,["语法检查","风格建议","语气调整","写作辅助","全球领先"],4.7),
("notion-ai","Notion AI","Notion内置的AI写作助手，支持头脑风暴、内容生成、总结和翻译。","https://www.notion.so","$10/月",False,["Notion","内置AI","头脑风暴","总结","翻译"],4.5),
("chatgpt","ChatGPT","OpenAI推出的对话式AI助手，支持写作、编程、分析等多种任务，全球最受欢迎。","https://chatgpt.com","免费 + $20/月",True,["OpenAI","对话AI","通用助手","写作","最受欢迎"],4.8),
("claude","Claude","Anthropic推出的AI助手，以长文本处理和安全性著称，适合深度写作和分析。","https://claude.ai","免费 + $20/月",True,["Anthropic","长文本","安全性","深度写作","分析"],4.7),
("sudowrite","Sudowrite","专为小说和创意写作设计的AI工具，提供情节建议、角色发展和文风模仿。","https://www.sudowrite.com","$19/月",False,["小说","创意写作","情节建议","角色发展","文风模仿"],4.5),
("novelai","NovelAI","AI故事和图像生成平台，专注于小说创作，支持自定义AI模型训练。","https://novelai.net","免费 + $10/月",True,["小说","故事生成","图像生成","自定义模型","创意"],4.3),
("moonbeam","Moonbeam","AI长文写作助手，专为博客和文章设计，支持从零开始生成完整长文。","https://www.gomoonbeam.com","免费 + $49/月",True,["长文写作","博客","文章","从零生成","内容创作"],4.2),
("lex","Lex","AI驱动的现代文字处理器，提供智能写作建议和实时协作功能，界面简洁优雅。","https://lex.page","免费 + $12/月",True,["文字处理器","智能建议","实时协作","简洁","现代"],4.4),
("hyperwrite","HyperWrite","AI个人写作助手，提供智能补全、改写和个性化建议，浏览器集成度高。","https://www.hyperwriteai.com","免费 + $19.99/月",True,["智能补全","改写","个性化","浏览器集成","写作辅助"],4.3),
("jenni-ai","Jenni AI","AI学术写作助手，支持论文撰写、引用管理和文献综述生成。","https://jenni.ai","免费 + $20/月",True,["学术写作","论文","引用管理","文献综述","学生"],4.2),
("ai-writer","AI Writer","自动化内容生成平台，通过关键词研究自动生成SEO优化的文章。","https://ai-writer.com","$29/月",False,["自动化","SEO优化","关键词研究","文章生成","内容营销"],4.0),
("article-forge","Article Forge","全自动AI文章生成器，一键生成长篇高质量文章，支持多语言。","https://www.articleforge.com","$13/月",False,["全自动","一键生成","长篇","多语言","内容农场"],3.9),
("wordai","WordAi","AI文章重写工具，使用先进NLP技术生成通顺、独特的改写内容。","https://wordai.com","$57/月",False,["重写","NLP","独特内容","文章改写","SEO"],4.0),
("spin-rewriter","Spin Rewriter","AI文章改写工具，支持一键生成多篇文章变体，集成Copyscape检测。","https://www.spinrewriter.com","$47/月",False,["改写","多篇文章","Copyscape","内容变体","SEO"],3.8),
("text-cortex","Text Cortex","AI写作和研究助手，支持多种内容类型生成和个性化AI模型训练。","https://textcortex.com","免费 + $24.99/月",True,["研究助手","个性化","多类型","AI模型","内容生成"],4.1),
("ink-editor","INK Editor","AI SEO写作平台，集成关键词优化和可读性分析，提升内容排名。","https://inkforall.com","免费 + $39/月",True,["SEO写作","关键词优化","可读性","内容排名","营销"],4.0),
("scalenut","Scalenut","AI SEO和内容营销平台，从研究到写作全流程自动化，支持内容规划。","https://www.scalenut.com","$39/月",False,["SEO","内容营销","全流程","内容规划","自动化"],4.2),
("surfer-seo","Surfer SEO","数据驱动的SEO内容优化平台，通过分析SERP提供精准的内容优化建议。","https://surferseo.com","$69/月",False,["SEO","数据驱动","SERP分析","内容优化","排名提升"],4.6),
("clearscope","Clearscope","高端AI SEO内容优化工具，提供详细的关键词和相关性分析。","https://www.clearscope.io","$170/月",False,["高端","SEO","关键词","相关性","内容优化"],4.5),
("marketmuse","MarketMuse","AI内容智能平台，通过主题建模帮助创建权威、全面的内容。","https://www.marketmuse.com","$149/月",False,["内容智能","主题建模","权威内容","全面","策略"],4.3),
("frase","Frase","AI SEO内容研究和写作平台，分析顶级搜索结果并生成优化内容大纲。","https://www.frase.io","$15/月",False,["SEO研究","内容大纲","SERP分析","写作","优化"],4.4),
("anyword","Anyword","AI性能预测写作平台，预测文案转化率，帮助选择最佳营销文案。","https://anyword.com","$49/月",False,["性能预测","转化率","营销文案","数据驱动","A/B测试"],4.2),
("copysmith","Copysmith","企业级AI营销文案平台，支持团队协作和大规模内容生成。","https://copysmith.ai","$19/月",False,["企业级","营销文案","团队协作","大规模","电商"],4.0),
("adzis","AdZis","电商AI内容生成平台，自动创建产品描述、分类页面和博客内容。","https://adzis.com","$60/月",False,["电商","产品描述","自动创建","分类页面","博客"],3.7),
("peppertype","Peppertype.ai","AI内容生成平台，为营销团队提供快速、高效的内容创作工具。","https://www.peppertype.ai","$35/月",False,["营销团队","快速创作","内容生成","效率","协作"],4.0),
("simplified","Simplified","一体化AI设计和写作平台，集成图形设计、视频编辑和AI文案。","https://simplified.com","免费 + $18/月",True,["一体化","设计","视频","AI文案","多功能"],4.3),
("writer-com","Writer.com","企业级AI写作平台，提供品牌声音定制、合规检查和团队协作功能。","https://writer.com","$18/用户/月",False,["企业级","品牌声音","合规检查","团队协作","安全"],4.4),
("type-ai","Type.ai","AI文档编辑器，支持智能续写、改写和多种文档格式导出。","https://type.ai","免费 + $12/月",True,["文档编辑","智能续写","改写","多格式","简洁"],4.1),
("craft","Craft","AI增强的文档和笔记应用，支持智能组织、协作和美观的文档排版。","https://www.craft.do","免费 + $5/月",True,["文档","笔记","智能组织","协作","美观"],4.5),
("mem-ai","Mem.ai","AI驱动的知识管理和笔记应用，自动组织和连接笔记，支持智能搜索。","https://mem.ai","免费 + $8/月",True,["知识管理","笔记","自动组织","智能搜索","连接"],4.3),
("glean","Glean","AI企业搜索平台，帮助员工快速找到公司内部的知识和信息。","https://www.glean.com","按用户报价",False,["企业搜索","知识管理","内部信息","效率","SaaS"],4.4),
("coda-ai","Coda AI","Coda文档平台的AI助手，支持自动化工作流、内容生成和数据分析。","https://coda.io","免费 + $10/月",True,["文档平台","工作流","数据分析","内容生成","协作"],4.3),
("gamma","Gamma","AI演示文稿生成平台，通过文本输入快速创建美观的交互式演示文稿。","https://gamma.app","免费 + $10/月",True,["演示文稿","AI生成","交互式","美观","快速创建"],4.6),
("tome","Tome","AI叙事和演示平台，支持创建故事化的演示文稿和视觉叙事内容。","https://tome.app","免费 + $16/月",True,["叙事","演示","视觉叙事","故事化","创意"],4.4),
("beautiful-ai","Beautiful.ai","AI驱动的演示文稿设计工具，自动调整布局和视觉设计。","https://www.beautiful.ai","$12/月",False,["演示文稿","自动设计","布局调整","视觉设计","专业"],4.3),
("gemini","Google Gemini","谷歌推出的多模态AI助手，支持写作、分析和创意内容生成。","https://gemini.google.com","免费 + $20/月",True,["Google","多模态","通用助手","写作","分析"],4.5),
("gemini-advanced","Gemini Advanced","谷歌Gemini的高级版本，支持超长上下文和复杂文档分析。","https://gemini.google.com/advanced","$20/月",False,["Google","超长上下文","文档分析","高级","多模态"],4.6),
("perplexity","Perplexity AI","AI搜索引擎，提供带引用来源的详细答案，适合研究和信息收集写作。","https://www.perplexity.ai","免费 + $20/月",True,["AI搜索","引用来源","研究","信息收集","问答"],4.7),
("you-com","You.com","AI搜索和聊天平台，集成多种AI模型，支持个性化搜索结果。","https://you.com","免费 + $20/月",True,["AI搜索","多模型","个性化","聊天","信息获取"],4.2),
("poe","Poe","AI聊天机器人聚合平台，可访问ChatGPT、Claude等多种AI模型进行写作辅助。","https://poe.com","免费 + $19.99/月",True,["聚合平台","多模型","聊天","写作辅助","AI访问"],4.3),
("character-ai","Character.AI","AI角色对话平台，用户可创建虚拟角色进行创意写作和对话练习。","https://character.ai","免费 + $9.99/月",True,["角色对话","创意写作","虚拟角色","对话练习","社区"],4.4),
("pi","Pi","Inflection AI推出的个人AI助手，以友好对话风格著称，适合头脑风暴和日常写作。","https://pi.ai","免费",True,["个人助手","友好对话","头脑风暴","日常写作","Inflection"],4.2),
("deepseek","DeepSeek","2025年热门的中国AI大模型，以高性价比和强推理能力受到全球关注。","https://www.deepseek.com","免费 + $2.19/月",True,["中国AI","高性价比","推理","大模型","2025热门"],4.7),
("doubao","Doubao","字节跳动推出的AI助手，集成写作、翻译、总结等多种办公能力。","https://www.doubao.com","免费 + $9/月",True,["字节跳动","AI助手","办公","写作","翻译"],4.3),
("kimi","Kimi","月之暗面推出的AI助手，支持超长文本处理和多文件分析，适合长文档写作。","https://kimi.moonshot.cn","免费 + $19.99/月",True,["超长文本","多文件","长文档","月之暗面","分析"],4.5),
("wps-ai","WPS AI","WPS Office内置的AI写作助手，支持文档生成、改写和翻译。","https://www.wps.cn","免费 + $15/月",True,["WPS","Office","文档生成","改写","翻译"],4.1),
("iflytek-spark","iFlytek Spark","科大讯飞推出的认知大模型，支持中文写作、翻译和代码生成。","https://xinghuo.xfyun.cn","免费 + $9.99/月",True,["科大讯飞","中文","认知大模型","写作","翻译"],4.2),
("tongyi-qianwen","Tongyi Qianwen","阿里云推出的通义千问大模型，支持多轮对话和复杂任务处理。","https://tongyi.aliyun.com","免费 + $8/月",True,["阿里云","通义千问","多轮对话","复杂任务","中文"],4.4),
("baidu-ernie","Baidu ERNIE","百度文心大模型，支持创意写作、知识问答和文档生成。","https://yiyan.baidu.com","免费 + $15/月",True,["百度","文心","创意写作","知识问答","中文"],4.3),
("openrouter","OpenRouter","AI模型统一接入平台，可访问全球多种大模型进行写作和内容生成。","https://openrouter.ai","按量付费",False,["统一接入","多模型","API","开发者","灵活"],4.2),
("groq","Groq","以超高推理速度著称的AI平台，支持快速生成大量文本内容。","https://groq.com","按量付费",False,["超高速度","推理","快速生成","开发者","高效"],4.3),
("together-ai","Together AI","开源模型推理和微调平台，支持多种大语言模型的快速部署和训练。","https://www.together.ai","按量付费",False,["开源模型","推理","微调","部署","开发者"],4.1),
("fireworks-ai","Fireworks AI","快速AI推理平台，专注于开源大语言模型的高效推理服务。","https://fireworks.ai","按量付费",False,["快速推理","开源模型","高效","开发者","API"],4.2),
("anthropic-console","Anthropic Console","Anthropic开发者平台，提供Claude API访问和提示词工程工具。","https://console.anthropic.com","按量付费",False,["开发者","Claude","API","提示词工程","企业"],4.5),
("mistral-ai","Mistral AI","法国开源大模型公司，提供高性能的AI写作和推理模型。","https://mistral.ai","免费 + $5/月",True,["法国","开源","高性能","大模型","欧洲AI"],4.4),
("cohere","Cohere","企业级大语言模型平台，专注于文本生成、嵌入和分类任务。","https://cohere.com","按量付费",False,["企业级","文本生成","嵌入","分类","开发者"],4.3),
("ai21-labs","AI21 Labs","以色列AI公司推出的Jurassic大模型，专注于长文本理解和生成。","https://studio.ai21.com","按量付费",False,["以色列","长文本","理解","生成","Jurassic"],4.1),
("hugging-chat","HuggingChat","Hugging Face推出的开源AI聊天界面，可访问多种开源大模型。","https://huggingface.co/chat","免费",True,["Hugging Face","开源","聊天","多模型","社区"],4.2),
("phind","Phind","面向开发者的AI搜索引擎，支持技术问题的智能问答和代码生成。","https://www.phind.com","免费 + $20/月",True,["开发者","AI搜索","技术问答","代码生成","编程"],4.3),
("cursor","Cursor","AI驱动的代码编辑器，集成GPT-4等模型，支持智能代码补全和生成。","https://cursor.com","免费 + $20/月",True,["代码编辑器","GPT-4","智能补全","代码生成","开发者"],4.7),
("windsurf","Windsurf","Codeium推出的AI编程IDE，支持多文件编辑和智能代码生成。","https://codeium.com","免费 + $12/月",True,["IDE","多文件编辑","代码生成","Codeium","开发者"],4.4),
("github-copilot","GitHub Copilot","GitHub推出的AI编程助手，支持实时代码建议和自动完成。","https://github.com/copilot","$10/月",False,["GitHub","编程助手","实时代码","自动完成","开发者"],4.6),
("replit-ai","Replit AI","Replit集成的AI编程助手，支持代码生成、解释和调试。","https://replit.com","免费 + $14/月",True,["编程","代码生成","解释","调试","在线IDE"],4.2),
("sourcegraph-cody","Sourcegraph Cody","AI编程助手，基于代码图谱理解代码库，提供智能代码建议。","https://sourcegraph.com/cody","免费 + $19/月",True,["代码图谱","智能建议","代码库","开发者","企业"],4.3),
("tabnine","Tabnine","AI代码补全工具，支持私有部署和团队知识共享，保护代码安全。","https://www.tabnine.com","免费 + $12/月",True,["代码补全","私有部署","团队","安全","开发者"],4.2),
("continue","Continue","开源AI编程助手，支持多种模型和IDE，可自定义工作流。","https://continue.dev","免费",True,["开源","多模型","多IDE","自定义","开发者"],4.1),
("aider","Aider","终端AI编程助手，支持多文件编辑和Git集成，适合命令行用户。","https://aider.chat","免费",True,["终端","多文件","Git集成","命令行","开源"],4.3),
("quivr","Quivr","开源AI第二大脑，支持知识库构建和智能问答，可连接多种数据源。","https://quivr.app","免费 + $15/月",True,["第二大脑","知识库","智能问答","开源","数据源"],4.0),
("obsidian-copilot","Obsidian Copilot","Obsidian笔记的AI助手插件，支持智能搜索和内容生成。","https://obsidian.md","免费",True,["Obsidian","笔记","智能搜索","插件","知识管理"],4.2),
("logseq","Logseq","开源知识管理和协作平台，支持AI插件进行智能笔记整理。","https://logseq.com","免费",True,["开源","知识管理","协作","AI插件","笔记"],4.1),
("notion-calendar","Notion Calendar","Notion集成的AI日历工具，支持智能日程安排和任务管理。","https://www.notion.so","免费",True,["日历","日程安排","任务管理","Notion","集成"],4.0),
("clickup-ai","ClickUp AI","ClickUp集成的AI写作助手，支持任务描述、文档和邮件生成。","https://clickup.com","$7/月",False,["项目管理","任务描述","文档","邮件","集成"],4.1),
("asana-ai","Asana AI","Asana内置的AI功能，支持智能任务分配、进度跟踪和报告生成。","https://asana.com","按用户报价",False,["项目管理","任务分配","进度跟踪","报告","企业"],4.0),
("monday-ai","monday AI","monday.com集成的AI助手，支持工作流自动化和内容生成。","https://monday.com","按用户报价",False,["工作流","自动化","内容生成","项目管理","协作"],4.0),
("trello-ai","Trello AI","Trello的AI功能，支持智能卡片建议和自动化规则生成。","https://trello.com","免费 + $5/月",True,["看板","智能建议","自动化","卡片","协作"],3.9),
("loom-ai","Loom AI","Loom视频平台的AI功能，支持自动视频摘要、章节划分和转录。","https://www.loom.com","免费 + $12.50/月",True,["视频","自动摘要","章节","转录","沟通"],4.2),
("descript-story","Descript Storyboard","Descript的故事板功能，支持视频脚本AI生成和视觉规划。","https://www.descript.com","$15/月",False,["故事板","视频脚本","视觉规划","AI生成","视频"],4.3),
("opus-clip","OpusClip","AI视频剪辑工具，自动将长视频转化为社交媒体短视频片段。","https://www.opus.pro","免费 + $19/月",True,["视频剪辑","短视频","自动","社交媒体","内容创作"],4.4),
("runway","Runway","AI视频生成和编辑平台，支持文本生成视频、图像编辑和特效制作。","https://runwayml.com","免费 + $15/月",True,["视频生成","文本转视频","图像编辑","特效","创意"],4.6),
("pika","Pika","AI视频生成平台，支持通过文本和图像生成高质量短视频内容。","https://pika.art","免费 + $8/月",True,["视频生成","文本转视频","图像转视频","短视频","创意"],4.3),
("luma-dream-machine","Luma Dream Machine","Luma AI推出的快速视频生成模型，支持高质量逼真视频创作。","https://lumalabs.ai/dream-machine","免费 + $23.99/月",True,["视频生成","快速","逼真","Luma","创意"],4.5),
("kling-ai","Kling AI","快手推出的AI视频生成模型，支持复杂动作和物理模拟。","https://klingai.com","免费 + $15/月",True,["快手","视频生成","动作模拟","物理","中国AI"],4.4),
("haiper","Haiper","2025年新兴的AI视频生成平台，支持高质量长视频生成和精细控制。","https://haiper.ai","免费 + $10/月",True,["新兴","视频生成","长视频","精细控制","2025"],4.2),
("heygen","HeyGen","AI数字人视频生成平台，支持多语言口播和虚拟主播创作。","https://www.heygen.com","免费 + $29/月",True,["数字人","口播","虚拟主播","多语言","视频"],4.5),
("synthesia","Synthesia","企业级AI视频生成平台，通过文本创建专业多语言培训视频。","https://www.synthesia.io","$22/月",False,["企业级","培训视频","多语言","专业","文本转视频"],4.4),
("d-id","D-ID","AI数字人视频生成平台，支持照片说话和实时流媒体数字人。","https://www.d-id.com","免费 + $5.9/月",True,["数字人","照片说话","实时","流媒体","创意"],4.1),
("invideo-ai","InVideo AI","AI视频创作平台，通过文本提示自动生成完整视频内容和脚本。","https://invideo.io","免费 + $20/月",True,["视频创作","文本提示","自动生成","脚本","营销"],4.3),
("fliki","Fliki","AI文本转视频平台，支持将博客和脚本转化为带AI配音的视频。","https://fliki.ai","免费 + $21/月",True,["文本转视频","AI配音","博客","脚本","内容"],4.2),
("veed-ai","VEED AI","在线视频编辑平台的AI功能，支持自动字幕、翻译和剪辑。","https://www.veed.io","免费 + $18/月",True,["视频编辑","自动字幕","翻译","在线","剪辑"],4.1),
("capcut","CapCut","字节跳动的AI视频编辑工具，提供智能剪辑、特效和字幕功能。","https://www.capcut.com","免费",True,["视频编辑","智能剪辑","特效","字幕","字节跳动"],4.4),
("canva-ai","Canva AI","Canva集成的AI设计助手，支持文本生成图像、演示文稿和文档。","https://www.canva.com","免费 + $12.99/月",True,["设计","AI图像","演示文稿","文档","模板"],4.5),
("adobe-firefly","Adobe Firefly","Adobe推出的AI创意生成工具，支持图像、矢量图和文字效果生成。","https://www.adobe.com/firefly","免费 + $4.99/月",True,["Adobe","创意","图像生成","矢量","文字效果"],4.4),
("midjourney","Midjourney","全球领先的AI图像生成平台，以艺术风格和高美学质量著称。","https://www.midjourney.com","$10/月",False,["图像生成","艺术风格","高美学","全球领先","创意"],4.8),
("stable-diffusion","Stable Diffusion","开源AI图像生成模型，支持本地部署和高度自定义创作。","https://stability.ai","免费",True,["开源","图像生成","本地部署","自定义","Stability"],4.6),
("dall-e-3","DALL-E 3","OpenAI推出的AI图像生成模型，擅长遵循复杂文本提示生成精确图像。","https://openai.com/dall-e-3","按量付费",False,["OpenAI","图像生成","精确","复杂提示","创意"],4.5),
("ideogram","Ideogram","专注于文本渲染的AI图像生成工具，擅长生成带精确文字的图像。","https://ideogram.ai","免费 + $8/月",True,["文本渲染","图像生成","精确文字","设计","创意"],4.3),
("recraft","Recraft","AI矢量图形生成平台，支持创建可编辑的品牌级设计素材。","https://www.recraft.ai","免费 + $20/月",True,["矢量图形","品牌设计","可编辑","设计素材","专业"],4.2),
("leonardo-ai","Leonardo.ai","AI图像生成平台，专注于游戏资产和概念艺术创作。","https://leonardo.ai","免费 + $12/月",True,["游戏资产","概念艺术","图像生成","创作者","游戏"],4.4),
("playground-ai","Playground AI","AI图像编辑和生成平台，支持混合图像编辑和多模型选择。","https://playgroundai.com","免费 + $15/月",True,["图像编辑","混合编辑","多模型","生成","创意"],4.1),
]

aan = [r[1] for r in audio_raw]
awn = [r[1] for r in writing_raw]

audio_tools = [bt(i, r, "ai-audio", aan) for i, r in enumerate(audio_raw)]
writing_tools = [bt(i, r, "ai-writing", awn) for i, r in enumerate(writing_raw)]

tools = audio_tools + writing_tools

with open("/workspace/data/tools-batch-3.json", "w", encoding="utf-8") as f:
    json.dump(tools, f, ensure_ascii=False, indent=2)

print(f"Generated {len(tools)} tools")
