import json, random
from datetime import datetime, timedelta

def rand_date():
    s = datetime(2026, 6, 15)
    e = datetime(2026, 6, 29)
    return (s + timedelta(days=random.randint(0, (e-s).days))).strftime("%Y-%m-%d")

def make_tool(idx, id_, name, cat, price, is_free, tags, desc, url):
    # Ensure desc is 100-150 Chinese chars
    if len(desc) < 100:
        desc = desc + "它持续迭代更新，保持技术领先，为开发者和企业提供稳定可靠的解决方案，助力数字化转型与智能化升级。"
    if len(desc) > 150:
        desc = desc[:147] + "..."
    # Generate derived fields
    one = desc[:30] + "..."
    seo_t = f"{name} - {one} | AI Navigator Pro"
    seo_d = desc[:75] + "..."
    rating = round(random.uniform(4.0, 5.0) if idx < 20 else random.uniform(3.5, 5.0), 1)
    views = random.randint(80000, 150000) if idx < 10 else random.randint(40000, 120000) if idx < 30 else random.randint(5000, 150000)
    feats = {
        "ai-agent": ["智能自动化", "多任务处理", "上下文理解", "API集成", "可扩展架构", "实时监控"],
        "mcp": ["标准化协议", "安全认证", "多服务集成", "实时同步", "事件驱动", "灵活配置"]
    }.get(cat, ["核心功能A", "核心功能B", "核心功能C", "核心功能D", "核心功能E", "核心功能F"])
    ucs = {
        "ai-agent": ["自动化工作流", "智能客服", "数据分析", "内容生成", "代码辅助"],
        "mcp": ["工具集成", "数据同步", "自动化部署", "服务编排", "监控告警"]
    }.get(cat, ["场景A", "场景B", "场景C", "场景D", "场景E"])
    comps = {
        "ai-agent": ["AutoGPT", "CrewAI", "LangChain"],
        "mcp": ["GitHub MCP", "Notion MCP", "Slack MCP"]
    }.get(cat, ["竞品A", "竞品B", "竞品C"])
    # Adjust competitors for well-known tools
    comp_map = {
        "autogpt": ["BabyAGI", "AgentGPT", "SuperAGI"],
        "babyagi": ["AutoGPT", "MetaGPT", "CrewAI"],
        "metagpt": ["AutoGPT", "Devin", "GPT-Engineer"],
        "gpt-researcher": ["Perplexity", "AutoGPT", "CrewAI"],
        "crewai": ["AutoGen", "MetaGPT", "LangGraph"],
        "langchain": ["LlamaIndex", "Semantic Kernel", "Haystack"],
        "langgraph": ["CrewAI", "AutoGen", "Temporal"],
        "llamaindex": ["LangChain", "Semantic Kernel", "Haystack"],
        "autogen": ["CrewAI", "LangGraph", "MetaGPT"],
        "semantic-kernel": ["LangChain", "LlamaIndex", "AutoGen"],
        "superagi": ["AutoGPT", "AgentGPT", "CrewAI"],
        "agentgpt": ["AutoGPT", "SuperAGI", "BabyAGI"],
        "opendevin": ["Devin", "SWE-agent", "GPT-Engineer"],
        "devin": ["OpenDevin", "SWE-agent", "GitHub Copilot"],
        "swe-agent": ["Devin", "OpenDevin", "GitHub Copilot"],
        "gpt-engineer": ["Devin", "Aider", "GitHub Copilot"],
        "aider": ["GitHub Copilot", "Continue", "Cursor"],
        "cline": ["Roo Code", "Continue", "Cursor"],
        "roo-code": ["Cline", "Continue", "Cursor"],
        "continue": ["GitHub Copilot", "Cursor", "Supermaven"],
        "supermaven": ["GitHub Copilot", "Tabnine", "Cursor"],
        "tabnine": ["GitHub Copilot", "Supermaven", "Cursor"],
        "amazon-bedrock-agents": ["Azure AI Agent Service", "Google Vertex AI", "OpenAI Assistants"],
        "azure-ai-agent-service": ["Amazon Bedrock Agents", "Google Vertex AI", "IBM watsonx"],
        "google-vertex-ai-agent-builder": ["Azure AI Agent Service", "Amazon Bedrock", "OpenAI GPTs"],
        "dify": ["Flowise", "LangChain", "Botpress"],
        "flowise": ["Dify", "Botpress", "n8n"],
        "botpress": ["Voiceflow", "Stack AI", "Dify"],
        "voiceflow": ["Botpress", "Stack AI", "Dify"],
        "stack-ai": ["Dify", "Flowise", "Voiceflow"],
        "chatbot-com": ["Intercom Fin", "Tidio AI", "Botsify"],
        "intercom-fin": ["Zendesk AI", "Freshdesk AI", "Ada AI"],
        "zendesk-ai": ["Intercom Fin", "Freshdesk AI", "Kore.ai"],
        "freshdesk-ai": ["Zendesk AI", "Intercom Fin", "Tidio AI"],
        "drift-ai": ["Intercom Fin", "Tidio AI", "Ada AI"],
        "tidio-ai": ["Intercom Fin", "Chatbot.com", "Freshdesk AI"],
        "ada-ai": ["Intercom Fin", "Kore.ai", "Avaamo"],
        "kore-ai": ["Ada AI", "Avaamo", "Rasa"],
        "avaamo": ["Kore.ai", "Rasa", "Haptik"],
        "rasa": ["Botpress", "Haptik", "Kore.ai"],
        "haptik": ["Rasa", "Yellow.ai", "Kore.ai"],
        "yellow-ai": ["Kore.ai", "Ada AI", "Haptik"],
        "gupshup": ["Twilio", "Sinch", "MessageBird"],
        "kommunicate": ["Intercom Fin", "Tidio AI", "Freshdesk AI"],
        "landbot": ["Tars", "Typeform", "Intercom"],
        "tars": ["Landbot", "Intercom", "Drift AI"],
        "collect-chat": ["Landbot", "Tars", "Chatbot.com"],
        "botsify": ["Chatbot.com", "MobileMonkey", "ManyChat"],
        "mobilemonkey": ["ManyChat", "Chatfuel", "Botsify"],
        "manychat": ["MobileMonkey", "Chatfuel", "Botsify"],
        "chatfuel": ["ManyChat", "MobileMonkey", "Botsify"],
        "sinch": ["Twilio", "Nexmo", "MessageBird"],
        "twilio": ["Sinch", "Nexmo", "MessageBird"],
        "nexmo": ["Twilio", "Sinch", "MessageBird"],
        "vonage": ["RingCentral", "Twilio", "8x8"],
        "messagebird": ["Twilio", "Sinch", "Sendbird"],
        "plivo": ["Twilio", "Nexmo", "Sinch"],
        "sendbird": ["Stream", "PubNub", "Ably"],
        "stream": ["Sendbird", "PubNub", "Ably"],
        "pubnub": ["Ably", "Pusher", "Stream"],
        "ably": ["PubNub", "Pusher", "Stream"],
        "pusher": ["Ably", "PubNub", "Socket.io"],
        "firebase": ["Supabase", "Appwrite", "AWS Amplify"],
        "supabase": ["Firebase", "Appwrite", "PlanetScale"],
        "appwrite": ["Firebase", "Supabase", "Backendless"],
        "parse": ["Firebase", "Supabase", "Appwrite"],
        "backendless": ["Firebase", "Supabase", "Appwrite"],
        "kuzzle": ["Firebase", "Parse", "ThingsBoard"],
        "feathers": ["Express", "NestJS", "Sails.js"],
        "loopback": ["NestJS", "Express", "Feathers"],
        "nestjs": ["Express", "Fastify", "LoopBack"],
        "express": ["Fastify", "Koa", "NestJS"],
        "fastify": ["Express", "NestJS", "Hapi"],
        "hapi": ["Express", "Fastify", "NestJS"],
        "koa": ["Express", "Fastify", "Hapi"],
        "sails-js": ["Express", "NestJS", "Feathers"],
        "meteor": ["Next.js", "Nuxt.js", "SvelteKit"],
        "next-js": ["Nuxt.js", "SvelteKit", "Remix"],
        "nuxt-js": ["Next.js", "SvelteKit", "Remix"],
        "sveltekit": ["Next.js", "Nuxt.js", "Astro"],
        "remix": ["Next.js", "SvelteKit", "Nuxt.js"],
        "astro": ["Next.js", "Gatsby", "Hugo"],
        "gatsby": ["Next.js", "Astro", "Hugo"],
        "hugo": ["Jekyll", "Astro", "Gatsby"],
        "jekyll": ["Hugo", "Gatsby", "Eleventy"],
        "eleventy": ["Hugo", "Jekyll", "Astro"],
        "gridsome": ["Nuxt.js", "Gatsby", "Astro"],
        "vuepress": ["Docusaurus", "MkDocs", "VitePress"],
        "docusaurus": ["VuePress", "MkDocs", "GitBook"],
        "mkdocs": ["Docusaurus", "VuePress", "GitBook"],
        "gitbook": ["Notion", "Confluence", "Docusaurus"],
        "notion": ["Confluence", "Slite", "Obsidian"],
        "confluence": ["Notion", "SharePoint", "GitBook"],
        "slite": ["Notion", "Confluence", "Tettra"],
        "tettra": ["Slite", "Notion", "Confluence"],
        "nuclino": ["Slite", "Notion", "Tettra"],
        "slab": ["Notion", "GitBook", "Confluence"],
        "outline": ["Notion", "Confluence", "GitBook"],
        "appflowy": ["Notion", "Anytype", "Obsidian"],
        "anytype": ["Notion", "Obsidian", "AppFlowy"],
        "capacities": ["Notion", "Obsidian", "Anytype"],
        "logseq": ["Roam Research", "Obsidian", "Notion"],
        "obsidian": ["Notion", "Logseq", "Roam Research"],
        "roam-research": ["Obsidian", "Logseq", "Notion"],
        "github-mcp": ["GitLab MCP", "Bitbucket MCP", "Sourcegraph"],
        "figma-mcp": ["Sketch API", "Adobe XD API", "Framer MCP"],
        "notion-mcp": ["Confluence MCP", "Slite MCP", "Coda MCP"],
        "slack-mcp": ["Discord MCP", "Teams MCP", "Mattermost MCP"],
        "discord-mcp": ["Slack MCP", "Guilded MCP", "Revolt MCP"],
        "gmail-mcp": ["Outlook MCP", "ProtonMail MCP", "Zoho MCP"],
        "google-drive-mcp": ["Dropbox MCP", "OneDrive MCP", "Box MCP"],
        "calendar-mcp": ["Calendly MCP", "Notion Calendar MCP", "Cron MCP"],
        "jira-mcp": ["Linear MCP", "Asana MCP", "Monday MCP"],
        "confluence-mcp": ["Notion MCP", "SharePoint MCP", "GitBook MCP"],
        "trello-mcp": ["Notion MCP", "Asana MCP", "Monday MCP"],
        "asana-mcp": ["Monday MCP", "Jira MCP", "ClickUp MCP"],
        "monday-mcp": ["Asana MCP", "Jira MCP", "Notion MCP"],
        "linear-mcp": ["Jira MCP", "Asana MCP", "GitHub MCP"],
        "airtable-mcp": ["Notion MCP", "Google Sheets MCP", "Smartsheet MCP"],
        "supabase-mcp": ["Firebase MCP", "Appwrite MCP", "PlanetScale MCP"],
        "postgresql-mcp": ["MySQL MCP", "SQLite MCP", "DuckDB MCP"],
        "mysql-mcp": ["PostgreSQL MCP", "MariaDB MCP", "SQLite MCP"],
        "mongodb-mcp": ["PostgreSQL MCP", "Redis MCP", "DynamoDB MCP"],
        "redis-mcp": ["Memcached MCP", "KeyDB MCP", "Dragonfly MCP"],
        "sqlite-mcp": ["PostgreSQL MCP", "DuckDB MCP", "LiteFS MCP"],
        "duckdb-mcp": ["PostgreSQL MCP", "SQLite MCP", "Snowflake MCP"],
        "snowflake-mcp": ["BigQuery MCP", "Redshift MCP", "DuckDB MCP"],
        "bigquery-mcp": ["Snowflake MCP", "Redshift MCP", "Databricks MCP"],
        "aws-mcp": ["Azure MCP", "GCP MCP", "Terraform MCP"],
        "azure-mcp": ["AWS MCP", "GCP MCP", "Terraform MCP"],
        "gcp-mcp": ["AWS MCP", "Azure MCP", "Terraform MCP"],
        "vercel-mcp": ["Netlify MCP", "Cloudflare MCP", "AWS MCP"],
        "netlify-mcp": ["Vercel MCP", "Cloudflare MCP", "AWS MCP"],
        "cloudflare-mcp": ["Vercel MCP", "Netlify MCP", "AWS MCP"],
        "stripe-mcp": ["PayPal MCP", "Adyen MCP", "Square MCP"],
        "paypal-mcp": ["Stripe MCP", "Adyen MCP", "Square MCP"],
        "twilio-mcp": ["Sinch MCP", "MessageBird MCP", "Vonage MCP"],
        "sendgrid-mcp": ["Mailgun MCP", "AWS SES MCP", "Postmark MCP"],
        "mailgun-mcp": ["SendGrid MCP", "AWS SES MCP", "Postmark MCP"],
        "aws-ses-mcp": ["SendGrid MCP", "Mailgun MCP", "Postmark MCP"],
        "firebase-mcp": ["Supabase MCP", "Appwrite MCP", "AWS Amplify MCP"],
        "auth0-mcp": ["Clerk MCP", "Okta MCP", "Firebase Auth MCP"],
        "clerk-mcp": ["Auth0 MCP", "Okta MCP", "Firebase Auth MCP"],
        "okta-mcp": ["Auth0 MCP", "Clerk MCP", "OneLogin MCP"],
        "onelogin-mcp": ["Okta MCP", "Auth0 MCP", "Azure AD MCP"],
        "gitlab-mcp": ["GitHub MCP", "Bitbucket MCP", "Gitea MCP"],
        "bitbucket-mcp": ["GitHub MCP", "GitLab MCP", "Gitea MCP"],
        "jenkins-mcp": ["GitHub Actions MCP", "CircleCI MCP", "GitLab CI MCP"],
        "github-actions-mcp": ["CircleCI MCP", "Travis CI MCP", "Jenkins MCP"],
        "circleci-mcp": ["GitHub Actions MCP", "Travis CI MCP", "Jenkins MCP"],
        "travis-ci-mcp": ["GitHub Actions MCP", "CircleCI MCP", "Jenkins MCP"],
        "docker-mcp": ["Kubernetes MCP", "Podman MCP", "containerd MCP"],
        "kubernetes-mcp": ["Docker MCP", "Helm MCP", "Rancher MCP"],
        "terraform-mcp": ["Pulumi MCP", "AWS CDK MCP", "CloudFormation MCP"],
        "ansible-mcp": ["Puppet MCP", "Chef MCP", "SaltStack MCP"],
        "puppet-mcp": ["Ansible MCP", "Chef MCP", "SaltStack MCP"],
        "chef-mcp": ["Ansible MCP", "Puppet MCP", "SaltStack MCP"],
        "prometheus-mcp": ["Grafana MCP", "Datadog MCP", "New Relic MCP"],
        "grafana-mcp": ["Prometheus MCP", "Datadog MCP", "New Relic MCP"],
        "datadog-mcp": ["New Relic MCP", "Grafana MCP", "Prometheus MCP"],
        "new-relic-mcp": ["Datadog MCP", "Grafana MCP", "Prometheus MCP"],
        "sentry-mcp": ["Bugsnag MCP", "Rollbar MCP", "LogRocket MCP"],
        "bugsnag-mcp": ["Sentry MCP", "Rollbar MCP", "LogRocket MCP"],
        "rollbar-mcp": ["Sentry MCP", "Bugsnag MCP", "LogRocket MCP"],
        "logrocket-mcp": ["FullStory MCP", "Hotjar MCP", "Mixpanel MCP"],
        "fullstory-mcp": ["Hotjar MCP", "LogRocket MCP", "Mixpanel MCP"],
        "hotjar-mcp": ["FullStory MCP", "Mixpanel MCP", "LogRocket MCP"],
        "mixpanel-mcp": ["Amplitude MCP", "Segment MCP", "Hotjar MCP"],
        "amplitude-mcp": ["Mixpanel MCP", "Segment MCP", "Hotjar MCP"],
        "segment-mcp": ["Rudderstack MCP", "Mixpanel MCP", "Amplitude MCP"],
        "rudderstack-mcp": ["Segment MCP", "Mixpanel MCP", "Amplitude MCP"],
        "customer-io-mcp": ["Braze MCP", "Iterable MCP", "Klaviyo MCP"],
        "braze-mcp": ["Iterable MCP", "Klaviyo MCP", "Customer.io MCP"],
        "iterable-mcp": ["Braze MCP", "Klaviyo MCP", "Customer.io MCP"],
        "klaviyo-mcp": ["Mailchimp MCP", "Braze MCP", "Iterable MCP"],
        "mailchimp-mcp": ["Klaviyo MCP", "HubSpot MCP", "SendGrid MCP"],
        "hubspot-mcp": ["Salesforce MCP", "Zendesk MCP", "Intercom MCP"],
        "salesforce-mcp": ["HubSpot MCP", "Zendesk MCP", "SAP MCP"],
        "zendesk-mcp": ["Intercom MCP", "Freshdesk MCP", "HubSpot MCP"],
        "intercom-mcp": ["Zendesk MCP", "Freshdesk MCP", "HubSpot MCP"],
        "freshdesk-mcp": ["Zendesk MCP", "Intercom MCP", "HubSpot MCP"],
        "zapier-mcp": ["Make MCP", "n8n MCP", "Workato MCP"],
        "make-mcp": ["Zapier MCP", "n8n MCP", "Workato MCP"],
        "n8n-mcp": ["Zapier MCP", "Make MCP", "Workato MCP"],
        "workato-mcp": ["Zapier MCP", "Make MCP", "Tray.io MCP"],
        "tray-io-mcp": ["Workato MCP", "Zapier MCP", "Make MCP"],
    }
    if id_ in comp_map:
        comps = comp_map[id_]
    # feature and use case specialization by id prefix
    feat_map = {
        "autogpt": ["自主任务分解", "循环执行与自我修正", "网页浏览与信息检索", "文件读写操作", "记忆管理", "多步骤工作流"],
        "babyagi": ["自动任务生成", "任务优先级排序", "向量数据库存储", "自主学习循环", "GPT集成", "可扩展架构"],
        "metagpt": ["角色扮演协作", "标准化SOP流程", "自动代码生成", "需求分析", "架构设计", "测试用例生成"],
        "gpt-researcher": ["深度网络研究", "自动报告生成", "来源引用", "多主题覆盖", "并行搜索", "可定制输出格式"],
        "crewai": ["角色定义", "任务委托", "团队协作", "工具集成", "内存管理", "流程编排"],
        "langchain": ["链式调用", "提示词管理", "向量存储集成", "工具使用", "代理构建", "流式输出"],
        "langgraph": ["图结构建模", "状态持久化", "循环工作流", "并行执行", "人机协作", "条件分支"],
        "llamaindex": ["数据索引", "向量存储", "查询引擎", "RAG管道", "多模态支持", "企业集成"],
        "autogen": ["多代理对话", "人机协作", "自定义代理", "工具集成", "对话流程控制", "代码生成"],
        "semantic-kernel": ["多语言支持", "规划器", "插件系统", "内存管理", "连接器", "提示词模板"],
        "superagi": ["代理构建器", "工具市场", "代理训练", "性能监控", "多代理协作", "API集成"],
        "agentgpt": ["浏览器运行", "无代码配置", "目标设定", "实时观察", "任务分解", "历史记录"],
        "opendevin": ["自主编码", "命令行交互", "沙箱执行", "代码调试", "文件管理", "浏览器操作"],
        "devin": ["端到端开发", "自主规划", "代码编写与调试", "应用部署", "持续学习", "工具使用"],
        "swe-agent": ["GitHub问题解析", "代码浏览", "自动编辑", "测试执行", "命令执行", "结果验证"],
        "gpt-engineer": ["需求对话", "代码生成", "增量开发", "代码审查", "多文件管理", "自定义提示"],
        "aider": ["多文件编辑", "Git自动提交", "多种LLM支持", "语音输入", "代码地图", "测试集成"],
        "cline": ["文件读写", "命令执行", "网页浏览", "自动编码", "多API支持", "任务规划"],
        "roo-code": ["多模式选择", "智能代码理解", "自主任务执行", "API灵活性", "代码审查", "上下文管理"],
        "continue": ["自动补全", "代码解释", "重构建议", "聊天功能", "多模型支持", "本地运行"],
        "supermaven": ["极速响应", "无限生成", "大上下文窗口", "多IDE支持", "代码预测", "隐私保护"],
        "tabnine": ["本地部署", "私有化模型", "代码安全", "智能补全", "聊天功能", "测试生成"],
        "amazon-bedrock-agents": ["托管部署", "基础模型集成", "知识库连接", "工具调用", "安全合规", "自动扩展"],
        "azure-ai-agent-service": ["多模型支持", "企业安全", "SLA保障", "Azure集成", "代理编排", "监控分析"],
        "google-vertex-ai-agent-builder": ["可视化构建", "Gemini集成", "对话管理", "知识库连接", "多渠道部署", "分析洞察"],
        "dify": ["提示词编排", "RAG管道", "Agent构建", "工作流设计", "运营分析", "多模型支持"],
        "flowise": ["拖拽界面", "LangChain集成", "自定义组件", "API部署", "多模型支持", "向量数据库"],
        "botpress": ["可视化设计器", "NLU引擎", "多渠道部署", "分析面板", "集成中心", "版本控制"],
        "voiceflow": ["可视化设计", "语音支持", "团队协作", "API集成", "原型测试", "多渠道部署"],
        "stack-ai": ["预构建模板", "企业集成", "安全部署", "无代码构建", "团队协作", "性能监控"],
        "chatbot-com": ["多渠道部署", "可视化构建器", "实时交接", "分析面板", "模板库", "CRM集成"],
        "intercom-fin": ["智能回答", "复杂查询", "人工转接", "知识库集成", "多渠道支持", "分析洞察"],
        "zendesk-ai": ["工单自动分类", "智能推荐", "聊天机器人", "知识库优化", "情感分析", "预测洞察"],
        "freshdesk-ai": ["智能路由", "自动回复", "预测分析", "知识库", "多渠道整合", "团队协作"],
        "drift-ai": ["意向识别", "会议安排", "个性化对话", "销售加速", "访客跟踪", "集成CRM"],
        "tidio-ai": ["聊天机器人", "实时聊天", "邮件自动化", "访客跟踪", "电商集成", "数据分析"],
        "ada-ai": ["高自动化率", "多语言支持", "深度集成", "无代码构建", "分析平台", "安全合规"],
        "kore-ai": ["虚拟助手构建", "流程自动化", "多渠道部署", "企业安全", "后端集成", "分析优化"],
        "avaamo": ["行业NLP", "合规安全", "多渠道部署", "后端集成", "对话分析", "持续学习"],
        "rasa": ["NLU引擎", "对话管理", "自定义动作", "本地部署", "多语言", "版本控制"],
        "haptik": ["对话设计", "行业模板", "分析平台", "多渠道", "后端集成", "AI训练"],
        "yellow-ai": ["多LLM架构", "动态对话流", "无代码构建", "135+语言", "实时分析", "全球部署"],
        "gupshup": ["消息API", "机器人构建", "营销管理", "多渠道", "分析面板", "模板消息"],
        "kommunicate": ["AI+人工", "无代码构建", "智能路由", "多渠道", "分析面板", "知识库"],
        "landbot": ["对话表单", "可视化构建", "多渠道", "A/B测试", "集成中心", "数据分析"],
        "tars": ["对话式营销", "广告集成", "Lead捕获", "自动跟进", "分析面板", "模板库"],
        "collect-chat": ["无代码构建", "模板丰富", "信息收集", "邮件通知", "分析面板", "网站嵌入"],
        "botsify": ["拖放构建", "多平台部署", "AI训练", "人工接管", "模板库", "分析面板"],
        "mobilemonkey": ["社交消息", "SMS营销", "Lead生成", "聊天爆破", "自动化流程", "分析追踪"],
        "manychat": ["可视化流程", "广播消息", "电商集成", "自动化规则", "分析面板", "A/B测试"],
        "chatfuel": ["无代码构建", "AI对话", "潜在客户认证", "自动营销", "多渠道", "分析面板"],
        "sinch": ["SMS API", "语音API", "邮件服务", "即时消息", "验证服务", "全球覆盖"],
        "twilio": ["可编程SMS", "语音API", "视频通话", "邮件API", "全球号码", "Serverless"],
        "nexmo": ["全球SMS", "语音API", "号码验证", "WhatsApp API", "全球网络", "高送达率"],
        "vonage": ["企业电话", "视频会议", "通信API", "统一消息", "全球部署", "分析管理"],
        "messagebird": ["SMS API", "WhatsApp API", "语音服务", "邮件API", "Inbox", "Flow Builder"],
        "plivo": ["语音API", "SMS API", "号码租赁", "全球覆盖", "高可靠性", "实时分析"],
        "sendbird": ["聊天SDK", "语音通话", "视频通话", "直播", "AI集成", "消息审核"],
        "stream": ["可扩展聊天", "活动流", "AI审核", "多平台SDK", "自定义UI", "分析面板"],
        "pubnub": ["实时消息", "IoT连接", "在线状态", "消息历史", "Functions", "全球网络"],
        "ably": ["发布订阅", "消息保证", "低延迟", "多协议", "全球分布", "开发者工具"],
        "pusher": ["WebSocket", "频道", "事件触发", "多SDK", "安全认证", "分析面板"],
        "firebase": ["实时数据库", "认证系统", "云存储", "云函数", "分析", "机器学习"],
        "supabase": ["PostgreSQL实时", "认证", "存储", "边缘函数", "AI集成", "自托管"],
        "appwrite": ["数据库", "认证", "存储", "云函数", "实时事件", "自托管"],
        "parse": ["数据存储", "推送通知", "认证", "云代码", "实时查询", "自托管"],
        "backendless": ["可视化数据库", "用户管理", "推送通知", "API生成", "实时数据", "代码生成"],
        "kuzzle": ["实时处理", "地理查询", "认证授权", "多协议", "插件系统", "边缘计算"],
        "feathers": ["REST API", "WebSocket实时", "服务架构", "认证授权", "数据库适配", "钩子系统"],
        "loopback": ["模型驱动", "SDK生成", "连接器生态", "认证授权", "API探索", "微服务"],
        "nestjs": ["TypeScript优先", "模块化架构", "依赖注入", "微服务", "GraphQL", "WebSocket"],
        "express": ["路由系统", "中间件", "模板引擎", "错误处理", "静态文件", "第三方集成"],
        "fastify": ["极低开销", "插件架构", "Schema验证", "内置日志", "异步支持", "TypeScript"],
        "hapi": ["配置优先", "输入验证", "缓存", "认证", "插件系统", "日志"],
        "koa": ["async/await", "洋葱模型", "上下文对象", "错误处理", "轻量核心", "中间件"],
        "sails-js": ["MVC架构", "ORM", "REST API生成", "WebSocket", "策略", "蓝图API"],
        "meteor": ["实时数据", "同构代码", "包管理", "移动构建", "账户系统", "延迟补偿"],
        "next-js": ["服务器渲染", "静态生成", "API路由", "App Router", "Server Actions", "边缘计算"],
        "nuxt-js": ["服务器渲染", "静态生成", "自动导入", "模块生态", "Nitro引擎", "TypeScript"],
        "sveltekit": ["服务器渲染", "路由系统", "API端点", "适配器", "预渲染", "快速开发"],
        "remix": ["嵌套路由", "数据加载", "表单处理", "渐进增强", "错误边界", "性能优化"],
        "astro": ["零JS默认", "岛屿架构", "多框架集成", "内容集合", "边缘渲染", "View Transitions"],
        "gatsby": ["GraphQL数据层", "插件生态", "图像优化", "增量构建", "PWA", "CDN部署"],
        "hugo": ["毫秒构建", "Markdown", "模板系统", "主题生态", "短代码", "多语言"],
        "jekyll": ["Markdown", "Liquid模板", "GitHub Pages", "插件", "主题", "简洁设计"],
        "eleventy": ["多模板语言", "零配置", "快速构建", "数据层", "插件", "无框架依赖"],
        "gridsome": ["GraphQL数据层", "代码分割", "图片优化", "PWA", "插件", "Vue生态"],
        "vuepress": ["Vue组件", "Markdown增强", "默认主题", "插件", "多语言", "搜索"],
        "docusaurus": ["文档页面", "博客", "版本管理", "国际化", "搜索", "主题定制"],
        "mkdocs": ["Markdown", "Material主题", "插件", "实时预览", "搜索", "多语言"],
        "gitbook": ["Git同步", "可视化编辑", "协作", "分析", "API文档", "搜索"],
        "notion": ["AI写作", "数据库", "项目管理", "模板生态", "协作", "自动化"],
        "confluence": ["结构化文档", "空间管理", "Jira集成", "宏功能", "模板", "权限控制"],
        "slite": ["AI问答", "简洁编辑", "强大搜索", "模板", "集成", "分析"],
        "tettra": ["AI分类", "问答机器人", "Slack集成", "知识验证", "模板", "搜索"],
        "nuclino": ["树状结构", "实时协作", "即时搜索", "API", "集成", "权限管理"],
        "slab": ["Markdown", "代码高亮", "GitHub集成", "版本历史", "协作", "搜索"],
        "outline": ["Markdown", "Slack集成", "权限控制", "搜索", "自托管", "API"],
        "appflowy": ["本地优先", "离线使用", "端到端加密", "插件扩展", "多平台", "AI集成"],
        "anytype": ["知识图谱", "对象类型", "点对点同步", "端到端加密", "离线优先", "多平台"],
        "capacities": ["对象类型", "网络视图", "AI助手", "查询功能", "日历集成", "模板"],
        "logseq": ["双向链接", "大纲编辑", "图谱视图", "本地存储", "插件系统", "查询"],
        "obsidian": ["双向链接", "图谱视图", "插件生态", "本地存储", "Canvas", "AI集成"],
        "roam-research": ["双向链接", "块引用", "每日笔记", "图谱视图", "协作", "查询"],
        "github-mcp": ["仓库管理", "Issue处理", "PR审查", "代码搜索", "发布管理", "Webhook集成"],
        "figma-mcp": ["文件访问", "设计规范读取", "资源导出", "组件分析", "设计令牌", "版本管理"],
        "notion-mcp": ["页面读写", "数据库查询", "内容创建", "权限管理", "工作区管理", "模板操作"],
        "slack-mcp": ["消息发送", "频道管理", "对话历史", "工作流集成", "交互组件", "文件共享"],
        "discord-mcp": ["频道管理", "消息交互", "角色管理", "Webhook", "社区活动", "语音频道"],
        "gmail-mcp": ["邮件读取", "发送回复", "标签管理", "过滤器", "草稿管理", "附件处理"],
        "google-drive-mcp": ["文件读写", "权限管理", "搜索", "文件夹操作", "文档转换", "版本控制"],
        "calendar-mcp": ["事件管理", "空闲查询", "会议邀请", "提醒设置", "多日历", "时区处理"],
        "jira-mcp": ["Issue管理", "项目查询", "工作流更新", "报告生成", "Sprint管理", "权限控制"],
        "confluence-mcp": ["页面读写", "空间管理", "内容搜索", "权限控制", "版本历史", "模板应用"],
        "trello-mcp": ["看板管理", "卡片操作", "列表管理", "标签", "截止日期", "Power-Ups"],
        "asana-mcp": ["任务创建", "项目更新", "工作分配", "进度报告", "自定义字段", "工作流规则"],
        "monday-mcp": ["工作板管理", "列类型支持", "自动化规则", "进度跟踪", "模板", "集成"],
        "linear-mcp": ["Issue管理", "项目规划", "里程碑", "Cycles", "键盘优先", "Git集成"],
        "airtable-mcp": ["记录管理", "视图查询", "字段操作", "附件处理", "自动化", "多表关联"],
        "supabase-mcp": ["SQL查询", "认证管理", "存储操作", "边缘函数", "实时订阅", "RLS策略"],
        "postgresql-mcp": ["SQL执行", "Schema管理", "性能优化", "备份恢复", "索引管理", "权限控制"],
        "mysql-mcp": ["查询执行", "用户管理", "表优化", "性能监控", "复制管理", "备份"],
        "mongodb-mcp": ["文档查询", "聚合管道", "集合管理", "索引创建", "集群监控", "Atlas集成"],
        "redis-mcp": ["数据结构操作", "性能监控", "集群配置", "Lua脚本", "Pub/Sub", "搜索"],
        "sqlite-mcp": ["SQL查询", "表管理", "数据导入", "数据导出", "索引", "事务"],
        "duckdb-mcp": ["分析查询", "Parquet读取", "CSV导入", "大数据集", "窗口函数", "扩展"],
        "snowflake-mcp": ["SQL查询", "仓库管理", "资源监控", "ETL自动化", "数据共享", "安全"],
        "bigquery-mcp": ["大规模查询", "数据集管理", "成本优化", "作业调度", "ML集成", "数据导入"],
        "aws-mcp": ["EC2管理", "S3操作", "Lambda部署", "RDS管理", "IAM控制", "CloudWatch"],
        "azure-mcp": ["VM管理", "存储操作", "函数部署", "数据库管理", "监控", "ARM模板"],
        "gcp-mcp": ["Compute Engine", "Cloud Storage", "Cloud Functions", "BigQuery", "GKE", "IAM"],
        "vercel-mcp": ["项目部署", "域名管理", "分析监控", "环境变量", "预览部署", "边缘函数"],
        "netlify-mcp": ["站点部署", "表单处理", "身份验证", "边缘函数", "分析", "大文件传输"],
        "cloudflare-mcp": ["DNS管理", "Worker部署", "CDN配置", "安全规则", "分析", "D1数据库"],
        "stripe-mcp": ["支付处理", "订阅管理", "发票生成", "退款处理", "Webhook", "报表分析"],
        "paypal-mcp": ["支付处理", "订阅管理", "争议处理", "多币种", "Webhook", "商家工具"],
        "twilio-mcp": ["SMS发送", "语音呼叫", "号码管理", "Webhook", "录音", "验证服务"],
        "sendgrid-mcp": ["邮件发送", "模板管理", "列表管理", "分析追踪", "Webhook", "A/B测试"],
        "mailgun-mcp": ["邮件发送", "路由规则", "列表管理", "分析追踪", "Webhook", "验证服务"],
        "aws-ses-mcp": ["邮件发送", "模板管理", "身份验证", "统计报告", "Webhook", "批量发送"],
        "firebase-mcp": ["认证管理", "实时数据库", "云存储", "云消息", "分析", "远程配置"],
        "auth0-mcp": ["身份认证", "SSO", "MFA", "用户管理", "规则引擎", "日志分析"],
        "clerk-mcp": ["用户认证", "会话管理", "组织管理", "JWT", "Webhook", "React集成"],
        "okta-mcp": ["身份认证", "SSO", "生命周期管理", "MFA", "分析", "集成"],
        "onelogin-mcp": ["SSO", "身份认证", "用户配置", "MFA", "分析", "目录集成"],
        "gitlab-mcp": ["仓库管理", "CI/CD", "Issue管理", "MR审查", "Wiki", "Runner管理"],
        "bitbucket-mcp": ["仓库管理", "Pipeline", "Issue管理", "PR审查", "Wiki", "部署"],
        "jenkins-mcp": ["任务管理", "插件管理", "构建触发", "日志查看", "节点管理", "流水线"],
        "github-actions-mcp": ["工作流管理", "Runner管理", "密钥管理", "日志查看", "Artifact", "缓存"],
        "circleci-mcp": ["Pipeline管理", "Orb使用", "并行执行", "日志查看", "缓存", "SSH调试"],
        "travis-ci-mcp": ["构建管理", "矩阵构建", "部署", "日志查看", "缓存", "加密变量"],
        "docker-mcp": ["镜像管理", "容器操作", "网络配置", "卷管理", "Compose", "Registry"],
        "kubernetes-mcp": ["Pod管理", "Deployment", "Service", "ConfigMap", "Helm", "监控"],
        "terraform-mcp": ["资源管理", "状态管理", "模块化", "计划执行", "Workspace", "Provider"],
        "ansible-mcp": ["Playbook执行", "库存管理", "角色管理", "Vault", "插件", "回调"],
        "puppet-mcp": ["清单管理", "模块管理", "报告查看", "节点分类", "Hiera", "Console"],
        "chef-mcp": ["Cookbook管理", "Recipe执行", "节点管理", "数据包", "搜索", "报告"],
        "prometheus-mcp": ["指标查询", "告警管理", "Target管理", "规则配置", "可视化", "服务发现"],
        "grafana-mcp": ["仪表板管理", "数据源配置", "告警规则", "面板编辑", "用户管理", "插件"],
        "datadog-mcp": ["指标查询", "日志分析", "APM追踪", "告警管理", "仪表板", "SLO"],
        "new-relic-mcp": ["APM查询", "日志分析", "基础设施监控", "告警管理", "仪表板", "AI助手"],
        "sentry-mcp": ["错误追踪", "Issue管理", "Release", "性能监控", "告警", "Dashboard"],
        "bugsnag-mcp": ["错误检测", "Release管理", "稳定性评分", "告警", " breadcrumbs", "趋势分析"],
        "rollbar-mcp": ["错误追踪", "人员分配", "Deploy追踪", "Telemetry", "告警", "RQL查询"],
        "logrocket-mcp": ["会话回放", "性能监控", "错误追踪", "分析", "漏斗", "热力图"],
        "fullstory-mcp": ["会话回放", "事件分析", "漏斗分析", "用户旅程", "热力图", "搜索"],
        "hotjar-mcp": ["热力图", "会话回放", "调查", "反馈", "漏斗", "录制"],
        "mixpanel-mcp": ["事件分析", "漏斗分析", "留存分析", "用户画像", "A/B测试", "报告"],
        "amplitude-mcp": ["事件分析", "实验平台", "用户画像", "归因分析", "漏斗", "留存"],
        "segment-mcp": ["源管理", "目的地配置", "协议", "身份解析", "隐私", "监控"],
        "rudderstack-mcp": ["源管理", "目的地配置", "Transformations", "身份解析", "隐私", "监控"],
        "customer-io-mcp": ["Campaign管理", "Segment", "消息模板", "A/B测试", "Webhook", "分析"],
        "braze-mcp": ["Campaign管理", "Canvas", "Segment", "消息模板", "Webhook", "分析"],
        "iterable-mcp": ["Campaign管理", "Journey", "Segment", "消息模板", "Webhook", "AI"],
        "klaviyo-mcp": ["Flow管理", "Segment", "模板编辑", "A/B测试", "预测", "集成"],
        "mailchimp-mcp": ["Campaign管理", "Audience", "自动化", "A/B测试", "分析", "模板"],
        "hubspot-mcp": ["CRM管理", "Marketing", "Sales", "Service", "CMS", "Operations"],
        "salesforce-mcp": ["CRM管理", "Sales Cloud", "Service Cloud", "Marketing", "报表", "Apex"],
        "zendesk-mcp": ["Ticket管理", "知识库", "Chat", "Talk", "Guide", "Explore"],
        "intercom-mcp": ["Conversation", "Articles", "Series", "Outbound", "Inbox", "Reports"],
        "freshdesk-mcp": ["Ticket管理", "知识库", "自动化", "SLA", "报告", "多渠道"],
        "zapier-mcp": ["Zap管理", "App连接", "任务历史", "Webhook", "路径", "过滤器"],
        "make-mcp": ["Scenario管理", "模块连接", "任务历史", "Webhook", "错误处理", "调度"],
        "n8n-mcp": ["Workflow管理", "节点连接", "任务历史", "Webhook", "错误处理", "自托管"],
        "workato-mcp": ["Recipe管理", "连接管理", "任务历史", "Webhook", "错误处理", "调度"],
        "tray-io-mcp": ["Workflow管理", "连接器", "任务历史", "Webhook", "错误处理", "调度"],
    }
    if id_ in feat_map:
        feats = feat_map[id_]
    uc_map = {
        "autogpt": ["自动化研究", "内容创作", "代码生成", "数据分析", "流程自动化"],
        "babyagi": ["任务自动化", "项目管理", "研究助手", "内容策划", "数据分析"],
        "metagpt": ["软件开发", "代码审查", "系统设计", "文档生成", "项目管理"],
        "gpt-researcher": ["学术研究", "市场调研", "竞品分析", "内容策划", "投资决策"],
        "crewai": ["内容创作", "客户支持", "数据分析", "代码开发", "市场调研"],
        "langchain": ["聊天机器人", "文档问答", "代码助手", "数据提取", "自动化工作流"],
        "langgraph": ["多代理系统", "对话管理", "审批流程", "复杂推理", "自动化代理"],
        "llamaindex": ["企业知识库", "文档问答", "数据检索", "智能搜索", "内容推荐"],
        "autogen": ["代码开发", "数据分析", "内容创作", "研究辅助", "自动化测试"],
        "semantic-kernel": ["企业应用", "智能助手", "自动化工作流", "知识管理", "对话系统"],
        "superagi": ["营销自动化", "客户服务", "数据收集", "内容生成", "流程优化"],
        "agentgpt": ["快速原型", "个人助手", "学习研究", "任务自动化", "创意探索"],
        "opendevin": ["代码生成", "Bug修复", "功能开发", "代码审查", "技术探索"],
        "devin": ["软件开发", "原型构建", "技术迁移", "Bug修复", "系统维护"],
        "swe-agent": ["Bug修复", "代码审查", "测试生成", "问题诊断", "自动化维护"],
        "gpt-engineer": ["原型开发", "MVP构建", "代码重构", "功能扩展", "学习编程"],
        "aider": ["日常编码", "代码重构", "Bug修复", "功能开发", "代码审查"],
        "cline": ["代码开发", "调试排查", "文档生成", "技术调研", "自动化重构"],
        "roo-code": ["智能编码", "代码分析", "项目重构", "自动化测试", "技术咨询"],
        "continue": ["日常编码", "代码学习", "技术文档", "代码审查", "快速原型"],
        "supermaven": ["快速编码", "代码补全", "函数生成", "文档编写", "测试生成"],
        "tabnine": ["企业开发", "安全合规", "团队协作", "代码标准化", "知识管理"],
        "amazon-bedrock-agents": ["企业自动化", "客户服务", "数据处理", "知识管理", "流程优化"],
        "azure-ai-agent-service": ["企业AI", "业务流程", "客户服务", "数据分析", "知识管理"],
        "google-vertex-ai-agent-builder": ["对话机器人", "搜索代理", "任务自动化", "客户服务", "内容生成"],
        "dify": ["AI应用开发", "聊天机器人", "知识库", "自动化工作流", "内容生成"],
        "flowise": ["无代码AI", "原型开发", "自动化流程", "聊天机器人", "数据处理"],
        "botpress": ["客户服务", "销售助手", "预约管理", "FAQ机器人", "内部支持"],
        "voiceflow": ["语音助手", "聊天机器人", "AI代理", "原型设计", "用户体验"],
        "stack-ai": ["业务流程自动化", "文档处理", "客户支持", "数据提取", "内容生成"],
        "chatbot-com": ["客户服务", "销售支持", "预约管理", "FAQ解答", "潜在客户捕获"],
        "intercom-fin": ["客户支持", "销售咨询", "账户管理", "技术支持", "订单查询"],
        "zendesk-ai": ["工单处理", "客户支持", "自助服务", "满意度提升", "运营管理"],
        "freshdesk-ai": ["客户支持", "工单管理", "自助服务", "团队协同", "效率提升"],
        "drift-ai": ["销售转化", "潜在客户", "会议预订", "客户沟通", "营销自动化"],
        "tidio-ai": ["电商客服", "销售支持", "订单查询", "弃购挽回", "客户互动"],
        "ada-ai": ["客户支持", "账户服务", "技术支持", "订单管理", "全球运营"],
        "kore-ai": ["员工支持", "客户服务", "流程自动化", "IT服务", "人力资源"],
        "avaamo": ["金融服务", "医疗保险", "保险理赔", "内部支持", "客户咨询"],
        "rasa": ["自定义聊天机器人", "语音助手", "自动化流程", "数据隐私", "企业集成"],
        "haptik": ["电商支持", "金融咨询", "电信服务", "内部自动化", "营销互动"],
        "yellow-ai": ["全球客服", "营销自动化", "员工支持", "销售助理", "流程优化"],
        "gupshup": ["WhatsApp营销", "客户通知", "交易消息", "客户支持", "用户互动"],
        "kommunicate": ["客户支持", "销售咨询", "预约管理", "电商服务", "SaaS支持"],
        "landbot": ["lead捕获", "问卷调查", "客户引导", "预约预订", "反馈收集"],
        "tars": ["Lead生成", "广告投放", "营销自动化", "客户筛选", "转化优化"],
        "collect-chat": ["信息收集", "潜在客户", "预约预订", "客户支持", "反馈收集"],
        "botsify": ["客服自动化", "教育辅导", "电商支持", "lead生成", "预约管理"],
        "mobilemonkey": ["社交营销", "SMS推广", "潜在客户", "客户互动", "活动推广"],
        "manychat": ["社交营销", "客户互动", "产品推广", "订单更新", "FAQ"],
        "chatfuel": ["社交客服", "lead生成", "产品推荐", "预约管理", "营销活动"],
        "sinch": ["用户验证", "交易通知", "营销推广", "客户沟通", "语音服务"],
        "twilio": ["应用通信", "客户服务", "验证系统", "IoT连接", "实时通知"],
        "nexmo": ["用户验证", "通知推送", "语音通话", "WhatsApp消息", "全球通信"],
        "vonage": ["企业通信", "远程协作", "客户联系", "全球办公", "呼叫中心"],
        "messagebird": ["客户通知", "营销消息", "验证系统", "客服对话", "自动化流程"],
        "plivo": ["呼叫中心", "通知系统", "用户验证", "语音应用", "短信营销"],
        "sendbird": ["社交应用", "在线医疗", "教育平台", "电商客服", "社区互动"],
        "stream": ["社交平台", "游戏社区", "教育应用", "电商互动", "内容平台"],
        "pubnub": ["实时协作", "在线游戏", "金融交易", "IoT监控", "现场活动"],
        "ably": ["实时协作", "实时数据", "在线游戏", "金融数据", "直播互动"],
        "pusher": ["实时通知", "在线聊天", "数据同步", "协作编辑", "实时仪表板"],
        "firebase": ["移动应用", "Web应用", "实时协作", "用户认证", "推送通知"],
        "supabase": ["应用后端", "实时数据", "用户管理", "文件存储", "边缘计算"],
        "appwrite": ["应用后端", "Flutter应用", "Web应用", "移动应用", "原型开发"],
        "parse": ["移动应用", "原型开发", "IoT后端", "内容管理", "社交网络"],
        "backendless": ["应用后端", "原型开发", "数据管理", "用户系统", "消息推送"],
        "kuzzle": ["智慧城市", "车联网", "工业IoT", "资产追踪", "实时监控"],
        "feathers": ["实时API", "聊天应用", "协作工具", "IoT平台", "微服务"],
        "loopback": ["API开发", "企业后端", "微服务", "数据集成", "移动后端"],
        "nestjs": ["企业后端", "API开发", "微服务", "实时应用", "Serverless"],
        "express": ["Web应用", "API服务", "微服务", "单页应用后端", "原型开发"],
        "fastify": ["高性能API", "微服务", "Serverless", "实时应用", "数据管道"],
        "hapi": ["企业应用", "API服务", "电商平台", "金融服务", "内容管理"],
        "koa": ["Web应用", "API服务", "实时应用", "微服务", "中间件开发"],
        "sails-js": ["实时应用", "聊天平台", "协作工具", "数据面板", "社交网络"],
        "meteor": ["实时应用", "协作工具", "社交平台", "原型开发", "移动应用"],
        "next-js": ["Web应用", "电商平台", "营销网站", "SaaS产品", "内容平台"],
        "nuxt-js": ["Web应用", "电商网站", "内容平台", "企业门户", "SaaS产品"],
        "sveltekit": ["高性能应用", "营销网站", "SaaS产品", "内容平台", "嵌入式应用"],
        "remix": ["Web应用", "电商平台", "SaaS产品", "内容网站", "管理系统"],
        "astro": ["营销网站", "博客", "文档站点", "内容平台", "静态网站"],
        "gatsby": ["营销网站", "博客", "电商前端", "文档站点", "作品集"],
        "hugo": ["博客", "文档", "企业网站", "营销页面", "作品集"],
        "jekyll": ["技术博客", "文档站点", "个人网站", "项目页面", "简历"],
        "eleventy": ["博客", "文档", "营销网站", "作品集", "快速原型"],
        "gridsome": ["Vue网站", "博客", "作品集", "营销页面", "文档"],
        "vuepress": ["项目文档", "技术博客", "开源网站", "API文档", "知识库"],
        "docusaurus": ["技术文档", "开源项目", "API文档", "博客", "知识库"],
        "mkdocs": ["Python文档", "API文档", "技术手册", "知识库", "项目文档"],
        "gitbook": ["产品文档", "API文档", "知识库", "团队wiki", "用户指南"],
        "notion": ["知识管理", "项目管理", "团队协作", "个人笔记", "文档编写"],
        "confluence": ["项目文档", "知识库", "技术规范", "团队协作", "敏捷文档"],
        "slite": ["团队wiki", "入职培训", "流程文档", "会议记录", "知识库"],
        "tettra": ["内部wiki", "知识共享", "入职培训", "流程管理", "团队问答"],
        "nuclino": ["知识库", "团队wiki", "文档管理", "项目笔记", "客户支持"],
        "slab": ["技术文档", "代码规范", "API文档", "团队wiki", "项目手册"],
        "outline": ["团队wiki", "知识库", "内部文档", "项目管理", "技术规范"],
        "appflowy": ["知识管理", "项目管理", "个人笔记", "团队协作", "隐私保护"],
        "anytype": ["知识管理", "个人知识库", "团队协作", "笔记", "项目管理"],
        "capacities": ["知识管理", "研究笔记", "项目管理", "内容策划", "学习记录"],
        "logseq": ["知识管理", "研究笔记", "日志记录", "项目管理", "Zettelkasten"],
        "obsidian": ["知识管理", "研究写作", "笔记", "项目管理", "创意构思"],
        "roam-research": ["研究笔记", "学术写作", "知识网络", "思维工具", "协作研究"],
        "github-mcp": ["代码审查", "Issue自动化", "发布流程", "仓库管理", "团队协作"],
        "figma-mcp": ["设计转代码", "设计系统维护", "资源导出", "设计审查", "令牌提取"],
        "notion-mcp": ["知识管理", "文档自动化", "内容生成", "项目管理", "数据同步"],
        "slack-mcp": ["通知自动化", "团队协作", "消息摘要", "工作流触发", "支持票务"],
        "discord-mcp": ["社区管理", "游戏助手", "支持机器人", "活动协调", "内容审核"],
        "gmail-mcp": ["邮件自动化", "客户支持", "日程管理", "邮件摘要", "自动回复"],
        "google-drive-mcp": ["文档管理", "内容处理", "文件同步", "权限控制", "备份自动化"],
        "calendar-mcp": ["日程管理", "会议安排", "提醒自动化", "时间分析", "团队协作"],
        "jira-mcp": ["项目管理", "Bug跟踪", "Sprint规划", "报告自动化", "工作流优化"],
        "confluence-mcp": ["文档同步", "知识管理", "技术规范", "项目文档", "内容生成"],
        "trello-mcp": ["任务管理", "项目跟踪", "内容规划", "团队协作", "个人生产力"],
        "asana-mcp": ["项目管理", "任务自动化", "进度跟踪", "团队协作", "报告生成"],
        "monday-mcp": ["工作管理", "项目跟踪", "资源规划", "营销管理", "CRM自动化"],
        "linear-mcp": ["Bug跟踪", "产品规划", "迭代管理", "团队协作", "开发工作流"],
        "airtable-mcp": ["内容管理", "产品目录", "CRM", "项目管理", "库存跟踪"],
        "supabase-mcp": ["数据库管理", "用户管理", "后端开发", "数据迁移", "实时应用"],
        "postgresql-mcp": ["数据分析", "Schema迁移", "性能调优", "备份自动化", "报表生成"],
        "mysql-mcp": ["Web应用管理", "数据库维护", "查询优化", "用户管理", "数据迁移"],
        "mongodb-mcp": ["文档管理", "数据分析", "内容存储", "日志处理", "实时应用"],
        "redis-mcp": ["缓存管理", "会话存储", "实时排行榜", "消息队列", "速率限制"],
        "sqlite-mcp": ["本地开发", "嵌入式应用", "数据分析", "快速原型", "移动应用"],
        "duckdb-mcp": ["数据分析", "科学计算", "ETL处理", "报表生成", "数据探索"],
        "snowflake-mcp": ["数据仓库", "商业智能", "ETL", "数据治理", "分析报表"],
        "bigquery-mcp": ["大数据分析", "成本优化", "数据管道", "机器学习", "报表生成"],
        "aws-mcp": ["云管理", "DevOps", "成本优化", "安全审计", "自动扩展"],
        "azure-mcp": ["Azure管理", "企业云", "成本监控", "安全合规", "自动化部署"],
        "gcp-mcp": ["GCP管理", "云原生", "数据管道", "容器编排", "安全审计"],
        "vercel-mcp": ["前端部署", "预览管理", "性能优化", "团队协作", "Serverless"],
        "netlify-mcp": ["静态部署", "表单处理", "身份管理", "边缘计算", "分析监控"],
        "cloudflare-mcp": ["DNS管理", "Worker部署", "安全防护", "CDN优化", "D1数据库"],
        "stripe-mcp": ["支付集成", "订阅管理", "财务自动化", "发票处理", "报表分析"],
        "paypal-mcp": ["支付集成", "订阅管理", "争议处理", "多币种", "商家工具"],
        "twilio-mcp": ["消息通知", "语音服务", "验证系统", "客户沟通", "IoT连接"],
        "sendgrid-mcp": ["邮件营销", "事务邮件", "模板管理", "分析追踪", "自动化"],
        "mailgun-mcp": ["邮件发送", "路由管理", "列表维护", "分析追踪", "验证服务"],
        "aws-ses-mcp": ["批量邮件", "事务邮件", "模板管理", "统计报告", "身份验证"],
        "firebase-mcp": ["移动后端", "用户认证", "实时数据", "推送通知", "分析监控"],
        "auth0-mcp": ["身份认证", "SSO集成", "安全合规", "用户管理", "规则引擎"],
        "clerk-mcp": ["用户认证", "会话管理", "组织管理", "前端集成", "Webhook"],
        "okta-mcp": ["企业认证", "SSO", "生命周期管理", "安全合规", "集成目录"],
        "onelogin-mcp": ["SSO集成", "用户配置", "安全认证", "目录同步", "分析监控"],
        "gitlab-mcp": ["代码管理", "CI/CD", "DevOps", "文档协作", "Runner管理"],
        "bitbucket-mcp": ["代码托管", "Pipeline", "团队协作", "部署管理", "Wiki文档"],
        "jenkins-mcp": ["持续集成", "自动化构建", "插件管理", "节点管理", "流水线"],
        "github-actions-mcp": ["CI/CD", "自动化测试", "部署发布", "密钥管理", "缓存优化"],
        "circleci-mcp": ["持续集成", "并行测试", "部署自动化", "Orb使用", "调试优化"],
        "travis-ci-mcp": ["持续集成", "矩阵构建", "自动部署", "日志查看", "加密变量"],
        "docker-mcp": ["容器管理", "镜像构建", "编排部署", "网络配置", "Registry"],
        "kubernetes-mcp": ["容器编排", "集群管理", "服务网格", "自动扩展", "监控告警"],
        "terraform-mcp": ["基础设施即代码", "多云管理", "状态管理", "模块化", "计划审查"],
        "ansible-mcp": ["配置管理", "自动化部署", "编排协调", "安全合规", " playbook管理"],
        "puppet-mcp": ["配置管理", "节点分类", "报告分析", "模块开发", "Hiera数据"],
        "chef-mcp": ["配置管理", "Cookbook开发", "基础设施自动化", "合规审计", "测试集成"],
        "prometheus-mcp": ["指标监控", "告警管理", "服务发现", "规则配置", "可视化"],
        "grafana-mcp": ["仪表板管理", "数据源集成", "告警配置", "面板定制", "团队协作"],
        "datadog-mcp": ["全栈监控", "日志分析", "APM追踪", "告警管理", "SLO管理"],
        "new-relic-mcp": ["应用监控", "基础设施监控", "日志分析", "告警管理", "AI洞察"],
        "sentry-mcp": ["错误追踪", "性能监控", "Release管理", "告警通知", "问题诊断"],
        "bugsnag-mcp": ["错误检测", "稳定性监控", "Release追踪", "告警通知", "趋势分析"],
        "rollbar-mcp": ["错误追踪", "部署监控", "Telemetry", "告警管理", "RQL分析"],
        "logrocket-mcp": ["会话回放", "性能分析", "错误诊断", "用户行为", "转化漏斗"],
        "fullstory-mcp": ["用户旅程", "会话回放", "事件分析", "漏斗优化", "搜索分析"],
        "hotjar-mcp": ["用户反馈", "热力图分析", "会话回放", "调查问卷", "转化优化"],
        "mixpanel-mcp": ["事件追踪", "漏斗分析", "留存分析", "用户画像", "A/B测试"],
        "amplitude-mcp": ["行为分析", "实验平台", "用户画像", "归因分析", "产品优化"],
        "segment-mcp": ["数据收集", "用户画像", "隐私合规", "数据治理", "实时监控"],
        "rudderstack-mcp": ["数据管道", "ETL处理", "隐私合规", "身份解析", "数据治理"],
        "customer-io-mcp": ["邮件营销", "自动化旅程", "用户细分", "A/B测试", "行为触发"],
        "braze-mcp": ["跨渠道营销", "用户旅程", "Canvas流程", "个性化消息", "分析优化"],
        "iterable-mcp": ["营销自动化", "用户旅程", "多渠道消息", "AI优化", "实验测试"],
        "klaviyo-mcp": ["电商营销", "自动化Flow", "预测分析", "用户细分", "A/B测试"],
        "mailchimp-mcp": ["邮件营销", "Audience管理", "自动化", "着陆页", "分析报告"],
        "hubspot-mcp": ["CRM管理", "营销自动化", "销售管道", "客户服务", "内容管理"],
        "salesforce-mcp": ["CRM管理", "销售自动化", "客户服务", "营销云", "报表分析"],
        "zendesk-mcp": ["客服管理", "知识库", "工单自动化", "客户满意度", "分析报告"],
        "intercom-mcp": ["客户沟通", "产品内消息", "支持自动化", "用户引导", "分析报告"],
        "freshdesk-mcp": ["工单管理", "多渠道支持", "自动化规则", "知识库", "SLA管理"],
        "zapier-mcp": ["工作流自动化", "应用集成", "任务调度", "数据同步", "Webhook"],
        "make-mcp": ["可视化自动化", "应用连接", "场景编排", "错误处理", "数据转换"],
        "n8n-mcp": ["工作流编排", "自托管", "节点扩展", "Webhook", "错误恢复"],
        "workato-mcp": ["企业集成", "Recipe自动化", "API管理", "数据同步", "安全合规"],
        "tray-io-mcp": ["云集成", "Workflow自动化", "连接器管理", "数据转换", "企业安全"],
    }
    if id_ in uc_map:
        ucs = uc_map[id_]
    return {
        "id": id_,
        "name": name,
        "logo": f"https://api.dicebear.com/7.x/shapes/svg?seed={id_}",
        "description": desc,
        "url": url,
        "price": price,
        "isFree": is_free,
        "tags": tags,
        "category": cat,
        "rating": rating,
        "updatedAt": rand_date(),
        "screenshots": [f"https://picsum.photos/seed/{id_}1/800/500"],
        "features": feats,
        "competitors": comps,
        "useCases": ucs,
        "seoTitle": seo_t,
        "seoDescription": seo_d,
        "featured": idx < 5,
        "trending": idx < 10,
        "views": views,
    }

# Define all tools as compact tuples: (id, name, url, price, isFree, tags, desc)
ai_agents = [
    ("autogpt", "AutoGPT", "https://agpt.co", "免费", True, ["开源", "自主代理", "GPT-4", "自动化"], "AutoGPT是一个实验性的开源AI代理应用程序，利用GPT-4或GPT-3.5实现完全自主的任务执行。它能够将大目标分解为子任务，循环执行并自我修正，无需人工干预即可完成复杂工作流。"),
    ("babyagi", "BabyAGI", "https://github.com/yoheinakajima/babyagi", "免费", True, ["开源", "任务管理", "GPT", "Python"], "BabyAGI是一个基于Python的AI驱动任务管理系统，使用OpenAI的GPT模型和向量数据库来创建、优先级排序和执行任务。它能够自主学习并根据先前任务的结果生成新任务，形成持续改进的循环。"),
    ("metagpt", "MetaGPT", "https://www.deepwisdom.ai", "免费", True, ["多智能体", "软件开发", "开源", "协作"], "MetaGPT是一个创新的多智能体协作框架，模拟软件公司的组织结构，让不同角色的AI代理协同完成复杂软件开发任务。它通过标准化的标准操作流程（SOP）实现高效的多代理协作，大幅提升代码质量和开发效率。"),
    ("gpt-researcher", "GPT Researcher", "https://gptr.dev", "免费", True, ["研究", "报告生成", "开源", "LLM"], "GPT Researcher是一个基于AI的自主研究代理，能够对任何给定主题进行深入的在线研究，并生成全面、准确且来源引用的报告。它利用先进的网络搜索和LLM技术，模拟人类研究员的工作流程。"),
    ("crewai", "CrewAI", "https://www.crewai.com", "免费", True, ["多代理", "编排框架", "角色扮演", "Python"], "CrewAI是一个用于编排角色扮演AI代理的尖端框架，支持创建多代理团队共同完成复杂任务。它提供灵活的代理角色定义、任务分配和协作机制，让开发者轻松构建智能自动化工作流。"),
    ("langchain", "LangChain", "https://www.langchain.com", "免费 + 企业版", True, ["LLM框架", "开源", "RAG", "AI代理"], "LangChain是一个强大的开源框架，用于开发由语言模型驱动的应用程序。它提供了丰富的组件和工具，支持构建复杂的LLM工作流、RAG系统和AI代理，是2025-2026年最受欢迎的LLM开发框架之一。"),
    ("langgraph", "LangGraph", "https://langchain-ai.github.io/langgraph/", "免费", True, ["多代理", "图结构", "工作流", "LangChain"], "LangGraph是LangChain生态系统中的扩展库，专注于构建具有状态持久化和循环能力的多代理应用程序。它使用图结构来建模复杂的工作流，支持条件边、循环和并行执行，是构建可靠AI代理系统的理想选择。"),
    ("llamaindex", "LlamaIndex", "https://www.llamaindex.ai", "免费 + 企业版", True, ["RAG", "数据索引", "LLM", "开源"], "LlamaIndex是一个领先的数据框架，用于将私有数据连接到大型语言模型。它提供强大的索引、查询和检索功能，支持构建高效的RAG系统，让LLM能够访问和利用企业内外部数据源。"),
    ("autogen", "AutoGen", "https://microsoft.github.io/autogen/", "免费", True, ["微软", "多代理", "对话", "开源"], "AutoGen是微软研究院开发的开源编程框架，用于构建AI代理并促进多个代理之间的对话协作。它支持自定义对话模式、人机协作和工具使用，能够构建复杂的多代理应用系统。"),
    ("semantic-kernel", "Semantic Kernel", "https://github.com/microsoft/semantic-kernel", "免费", True, ["微软", "SDK", "企业级", "开源"], "Semantic Kernel是微软推出的开源SDK，帮助开发者轻松将AI服务集成到应用程序中。它支持C#、Python和Java，提供规划器、插件系统和内存管理功能，让构建企业级AI应用变得简单高效。"),
    ("superagi", "SuperAGI", "https://superagi.com", "免费 + $29/月", True, ["自动化平台", "开源", "代理管理", "可扩展"], "SuperAGI是一个可扩展的开源AI自动化平台，让开发者能够构建、管理和运行自主AI代理。它提供直观的界面和丰富的工具集，支持代理训练、部署和监控，是构建生产级AI代理的完整解决方案。"),
    ("agentgpt", "AgentGPT", "https://agentgpt.reworkd.ai", "免费 + $40/月", True, ["Web应用", "无代码", "自主代理", "浏览器"], "AgentGPT是一个基于Web的自主AI代理平台，让用户无需编程即可在浏览器中创建和运行AI代理。它提供友好的界面来设定目标、观察代理自主思考和执行，是体验AI代理技术的最便捷方式。"),
    ("opendevin", "OpenDevin", "https://opendevin.github.io/OpenDevin/", "免费", True, ["开源", "编程代理", "软件开发", "Devin替代"], "OpenDevin是一个开源的AI软件工程师代理，旨在复现和超越Devin的能力。它能够自主编写代码、调试程序、与命令行交互，并在沙箱环境中安全执行，是开源社区对AI编程代理的重要贡献。"),
    ("devin", "Devin", "https://www.cognition.ai", "$500/月", False, ["AI软件工程师", "自主编码", "企业级", "突破技术"], "Devin是由Cognition AI推出的世界首个全自主AI软件工程师，能够端到端完成软件开发任务。它具备先进的推理能力，可以阅读文档、编写代码、调试程序、部署应用，代表AI编程代理的最新突破。"),
    ("swe-agent", "SWE-agent", "https://swe-agent.com", "免费", True, ["学术研究", "Bug修复", "开源", "GitHub"], "SWE-agent是由普林斯顿大学开发的AI系统，专门用于自动解决GitHub问题。它将语言模型转变为能够浏览代码库、编辑文件和执行测试的软件工程代理，在SWE-bench基准上取得了优异成绩。"),
    ("gpt-engineer", "GPT-Engineer", "https://github.com/AntonOsika/gpt-engineer", "免费", True, ["代码生成", "开源", "对话式", "项目管理"], "GPT-Engineer是一个开源的AI代码生成工具，通过对话方式理解用户需求并生成完整的代码库。它支持增量开发、代码审查和修改，让开发者能够快速将想法转化为可运行的软件项目。"),
    ("aider", "Aider", "https://aider.chat", "免费", True, ["结对编程", "Git集成", "终端", "多文件编辑"], "Aider是一个强大的AI结对编程工具，支持多文件编辑、Git集成和多种LLM后端。它能够在终端中与开发者协作，自动修改代码、提交更改并处理合并冲突，是终端用户的首选AI编程助手。"),
    ("cline", "Cline", "https://github.com/cline/cline", "免费", True, ["VS Code", "扩展", "自主代理", "编码"], "Cline是一个VS Code扩展，将自主AI代理能力带入代码编辑器。它能够读取文件、执行命令、浏览网页并自动修改代码，支持多种API提供商，是VS Code用户强大的AI编程助手。"),
    ("roo-code", "Roo Code", "https://github.com/RooVetGit/Roo-Code", "免费", True, ["VS Code", "社区驱动", "智能编码", "开源"], "Roo Code是Cline的社区驱动分支，专注于提供更智能、更可靠的编码体验。它继承了自主代理能力并增加了更多模式选择、更好的代码理解和更流畅的交互，是VS Code生态中备受关注的AI编码工具。"),
    ("continue", "Continue", "https://www.continue.dev", "免费", True, ["开源", "IDE扩展", "多IDE", "LLM灵活"], "Continue是一个开源的AI代码助手，支持VS Code和JetBrains IDE。它提供自动补全、代码解释、重构建议和聊天功能，支持任何LLM API或本地模型，是开发者友好的AI编程伴侣。"),
    ("supermaven", "Supermaven", "https://supermaven.com", "$10/月", False, ["代码补全", "极速", "IDE", "效率"], "Supermaven是一款极速AI代码补全工具，以其出色的响应速度和上下文理解能力著称。它提供无限次的代码建议和生成，支持主流IDE，是追求效率的开发者首选的AI编程工具。"),
    ("tabnine", "Tabnine", "https://www.tabnine.com", "$12/月", False, ["企业级", "私有化部署", "安全", "代码补全"], "Tabnine是企业级AI代码补全工具，支持本地部署和私有化模型，确保代码安全和隐私合规。它提供智能的代码建议、聊天功能和自动化测试生成，是大型企业的首选AI编程解决方案。"),
    ("amazon-bedrock-agents", "Amazon Bedrock Agents", "https://aws.amazon.com/bedrock/agents/", "按量付费", False, ["AWS", "托管服务", "企业级", "云原生"], "Amazon Bedrock Agents是AWS提供的托管服务，让开发者能够轻松构建和部署自主AI代理。它集成了Amazon的基础模型、知识库和工具调用能力，支持企业级的安全、监控和扩展需求。"),
    ("azure-ai-agent-service", "Azure AI Agent Service", "https://azure.microsoft.com/en-us/products/ai-agent-service", "按量付费", False, ["Azure", "微软", "企业级", "云原生"], "Azure AI Agent Service是微软Azure推出的企业级AI代理服务平台，提供完整的代理构建、部署和管理能力。它深度集成Azure生态，支持多模型选择、企业安全和企业级SLA保障。"),
    ("google-vertex-ai-agent-builder", "Google Vertex AI Agent Builder", "https://cloud.google.com/dialogflow/generative", "按量付费", False, ["Google Cloud", "Gemini", "可视化", "对话AI"], "Google Vertex AI Agent Builder是谷歌云提供的AI代理开发平台，支持构建对话式AI代理、搜索代理和任务代理。它集成Gemini模型和Vertex AI生态，提供可视化构建界面和强大的企业级功能。"),
    ("dify", "Dify", "https://dify.ai", "免费 + $59/月", True, ["开源", "可视化", "LLM应用", "运营平台"], "Dify是一个开源的LLM应用开发平台，支持可视化编排AI工作流、构建Agent和运营AI应用。它提供提示词编排、RAG管道、Agent构建和持续运营能力，是2025-2026年最受欢迎的LLM应用平台之一。"),
    ("flowise", "Flowise", "https://flowiseai.com", "免费 + 企业版", True, ["低代码", "开源", "拖拽", "LLM工作流"], "Flowise是一个开源的低代码LLM工作流构建平台，通过拖拽界面即可创建复杂的AI应用。它支持LangChain集成、自定义组件和API部署，让非技术人员也能快速构建和部署LLM应用。"),
    ("botpress", "Botpress", "https://botpress.com", "免费 + $50/月", True, ["开源", "聊天机器人", "对话AI", "多渠道"], "Botpress是一个领先的开源对话式AI平台，支持构建智能聊天机器人和虚拟助手。它提供可视化流程设计器、NLU引擎和多渠道部署，是企业构建客户服务自动化的首选平台。"),
    ("voiceflow", "Voiceflow", "https://www.voiceflow.com", "免费 + $40/月", True, ["对话设计", "语音", "可视化", "协作"], "Voiceflow是一个领先的对话体验设计平台，支持创建语音应用、聊天机器人和AI代理。它提供可视化的协作设计环境、强大的集成能力和企业级部署选项，是设计师和开发者构建对话AI的首选。"),
    ("stack-ai", "Stack AI", "https://www.stack-ai.com", "$49/月", False, ["企业级", "自动化", "无代码", "工作流"], "Stack AI是一个企业级AI自动化平台，让团队能够快速构建和部署AI工作流。它提供预构建模板、企业集成和安全的部署环境，帮助非技术团队利用AI提升业务效率。"),
    ("chatbot-com", "Chatbot.com", "https://www.chatbot.com", "$52/月", False, ["全渠道", "客服", "中小企业", "实时聊天"], "Chatbot.com是一个全渠道聊天机器人平台，支持在网站、Messenger、WhatsApp等多个渠道部署AI客服。它提供可视化构建器、实时聊天交接和详细的分析功能，是中小企业自动化客户服务的理想选择。"),
    ("intercom-fin", "Intercom Fin", "https://www.intercom.com/fin", "$0.99/次", False, ["AI客服", "GPT", "企业级", "对话"], "Intercom Fin是Intercom推出的AI客服助手，基于GPT技术提供智能的客户对话体验。它能够自动回答常见问题、执行复杂查询并无缝转接人工客服，是Intercom生态系统的核心AI组件。"),
    ("zendesk-ai", "Zendesk AI", "https://www.zendesk.com/service/intelligent-automation/", "按量付费", False, ["工单管理", "智能分类", "企业级", "客服"], "Zendesk AI是Zendesk平台内置的智能客服解决方案，利用AI技术自动分类工单、推荐答案和辅助人工客服。它深度集成Zendesk生态，帮助企业提升客服效率和客户满意度。"),
    ("freshdesk-ai", "Freshdesk AI", "https://www.freshworks.com/freshdesk/ai/", "$15/月", False, ["工单路由", "成长型企业", "易用", "预测分析"], "Freshdesk AI是Freshworks推出的AI驱动客服平台，提供智能工单路由、自动回复和预测分析功能。它以易用性和 affordability 著称，是成长型企业实现客服自动化的理想选择。"),
    ("drift-ai", "Drift AI", "https://www.drift.com", "$2500/年", False, ["销售", "对话营销", "B2B", "转化"], "Drift AI是Drift平台的AI组件，专注于将对话转化为销售机会。它利用AI识别高意向访客、自动安排会议和个性化对话，帮助企业加速销售周期并提升转化率。"),
    ("tidio-ai", "Tidio AI", "https://www.tidio.com", "$29/月", False, ["中小企业", "电商", "Shopify", "性价比高"], "Tidio AI是专为中小企业设计的AI客服套件，提供聊天机器人、实时聊天和邮件自动化功能。它以性价比高、易于设置和丰富的电商集成著称，是Shopify等电商平台商家的热门选择。"),
    ("ada-ai", "Ada AI", "https://www.ada.cx", "企业定价", False, ["企业级", "自动化", "多语言", "对话AI"], "Ada AI是一个企业级AI自动化客服平台，支持构建复杂的对话式AI代理来处理客户咨询。它以高自动化率、多语言支持和深度集成为特点，帮助大型企业显著降低客服成本并提升体验。"),
    ("kore-ai", "Kore.ai", "https://kore.ai", "企业定价", False, ["企业级", "虚拟助手", "流程自动化", "多渠道"], "Kore.ai是领先的企业对话式AI平台，提供构建虚拟助手、流程自动化和AI工作流的完整解决方案。它支持多种渠道部署、企业级安全和深度后端集成，是大型组织数字化转型的首选AI平台。"),
    ("avaamo", "Avaamo", "https://avaamo.ai", "企业定价", False, ["行业特定", "NLP", "合规", "企业级"], "Avaamo是一家专注于企业对话式AI的供应商，提供先进的NLP技术和行业特定的AI解决方案。它专注于金融、医疗和保险等行业，提供合规、安全和高度定制的对话AI能力。"),
    ("rasa", "Rasa", "https://rasa.com", "免费 + 企业版", True, ["开源", "机器学习", "本地部署", "开发者"], "Rasa是一个开源的对话式AI框架，让开发者能够构建基于机器学习的聊天机器人和语音助手。它提供完整的NLU、对话管理和自定义动作能力，支持本地部署和完全的数据控制，是开发者最喜爱的开源对话AI平台。"),
    ("haptik", "Haptik", "https://haptik.ai", "企业定价", False, ["对话平台", "电商", "端到端", "AI助手"], "Haptik是一个智能对话平台，专注于帮助企业构建AI驱动的客户体验和业务流程自动化。它在电商、金融和电信等行业有丰富的实施经验，提供端到端的对话AI解决方案。"),
    ("yellow-ai", "Yellow.ai", "https://yellow.ai", "企业定价", False, ["多LLM", "无代码", "全球化", "动态对话"], "Yellow.ai是一个动态AI代理平台，利用多LLM架构和动态对话流技术构建企业级AI代理。它提供无代码构建、实时分析和全球部署能力，支持超过135种语言，是全球化企业的理想选择。"),
    ("gupshup", "Gupshup", "https://www.gupshup.io", "按量付费", False, ["消息平台", "WhatsApp", "API", "营销"], "Gupshup是一个领先的对话式消息平台，帮助企业通过WhatsApp、SMS和其他消息渠道与客户互动。它提供API、机器人构建器和营销活动管理，是消息驱动业务增长的首选平台。"),
    ("kommunicate", "Kommunicate", "https://www.kommunicate.io", "$100/月", False, ["人机协作", "客服", "无代码", "实时聊天"], "Kommunicate是一个人机协作客服平台，结合AI聊天机器人和实时人工客服。它提供无代码机器人构建、智能路由和分析功能，帮助企业在自动化和人性化服务之间找到最佳平衡。"),
    ("landbot", "Landbot", "https://landbot.io", "$32/月", False, ["着陆页", "对话式", "表单", "转化"], "Landbot是一个对话式着陆页和表单构建平台，将传统的静态表单转化为引人入胜的对话体验。它提供可视化构建器、多渠道部署和丰富的集成，帮助企业提升转化率和用户参与度。"),
    ("tars", "Tars", "https://hellotars.com", "$99/月", False, ["营销自动化", "lead生成", "广告集成", "转化"], "Tars是一个对话式营销自动化平台，帮助企业通过聊天机器人生成潜在客户和自动化营销流程。它专注于高转化率的对话设计和与广告平台的无缝集成，是营销团队提升ROI的有效工具。"),
    ("collect-chat", "Collect.chat", "https://collect.chat", "$14/月", False, ["小型网站", "简单易用", "信息收集", "经济"], "Collect.chat是一个简单易用的对话式聊天机器人构建平台，专为网站主设计。它无需编码即可创建交互式聊天机器人来收集信息、筛选潜在客户和提供客户支持，是小型网站的经济实惠选择。"),
    ("botsify", "Botsify", "https://botsify.com", "$49/月", False, ["多平台", "拖放", "人工接管", "易用"], "Botsify是一个多平台聊天机器人构建器，支持在网站、Facebook、WhatsApp等渠道部署AI聊天机器人。它提供拖放界面、AI训练和人工接管功能，让非技术用户也能快速构建智能对话体验。"),
    ("mobilemonkey", "MobileMonkey", "https://mobilemonkey.com", "$119/月", False, ["社交电商", "SMS营销", "Facebook", "Instagram"], "MobileMonkey是一个专注于社交媒体和短信营销的聊天机器人平台。它支持Facebook Messenger、Instagram、SMS等渠道，提供强大的营销自动化和潜在客户生成功能，是社交电商的得力助手。"),
    ("manychat", "ManyChat", "https://manychat.com", "$15/月", False, ["Instagram", "Messenger", "社交商务", "营销"], "ManyChat是领先的Instagram和Facebook Messenger营销平台，帮助企业通过对话式营销自动化增长业务。它提供可视化流程构建、广播消息和电商集成，是社交商务领域的标杆产品。"),
    ("chatfuel", "Chatfuel", "https://chatfuel.com", "$14.99/月", False, ["无代码", "WhatsApp", "AI对话", "中小企业"], "Chatfuel是一个无代码AI聊天机器人平台，专注于Facebook Messenger、Instagram和WhatsApp。它提供AI驱动的对话管理、潜在客户资格认证和自动化营销功能，让中小企业轻松利用对话AI。"),
    ("sinch", "Sinch", "https://www.sinch.com", "按量付费", False, ["云通信", "SMS", "CPaaS", "全球"], "Sinch是一个全球云通信平台，提供SMS、语音、邮件和即时消息API服务。它帮助企业通过多渠道通信与客户建立联系，支持验证、营销和通知等场景，是全球领先的CPaaS提供商。"),
    ("twilio", "Twilio", "https://www.twilio.com", "按量付费", False, ["云通信", "API", "开发者", "可编程"], "Twilio是全球领先的云通信平台，提供可编程的SMS、语音、视频和电子邮件API。它让开发者能够轻松为应用添加通信功能，支持全球部署和强大的扩展性，是现代通信基础设施的首选。"),
    ("nexmo", "Nexmo (Vonage API)", "https://developer.vonage.com", "按量付费", False, ["Vonage", "全球覆盖", "验证", "企业级"], "Nexmo（现Vonage API）提供全球SMS、语音和验证API服务。它拥有广泛的全球运营商网络覆盖，提供高送达率和低延迟的通信服务，是企业级消息和语音应用的可靠选择。"),
    ("vonage", "Vonage", "https://www.vonage.com", "企业定价", False, ["统一通信", "UCaaS", "企业电话", "视频"], "Vonage是全球统一的通信平台，提供企业电话、视频协作和通信API服务。它结合了传统的UCaaS和现代的CPaaS能力，为企业提供从内部协作到客户沟通的全方位通信解决方案。"),
    ("messagebird", "MessageBird", "https://www.messagebird.com", "按量付费", False, ["全渠道", "开发者友好", "WhatsApp", "简单"], "MessageBird是一个全渠道通信平台，提供SMS、WhatsApp、语音和邮件等通信API。它以简单的开发者体验和全球覆盖著称，帮助企业构建无缝的客户沟通体验。"),
    ("plivo", "Plivo", "https://www.plivo.com", "按量付费", False, ["语音", "SMS", "性价比高", "可靠"], "Plivo是一个云通信API提供商，专注于提供高质量的语音和SMS服务。它以有竞争力的价格、全球覆盖和可靠的性能著称，是初创公司和成长型企业构建通信功能的理想选择。"),
    ("sendbird", "Sendbird", "https://sendbird.com", "$399/月", False, ["SDK", "应用内聊天", "视频通话", "实时"], "Sendbird是一个提供应用内聊天、语音和视频通话SDK的平台。它帮助企业快速为移动应用和网站添加丰富的通信功能，支持群组聊天、直播和AI聊天机器人集成。"),
    ("stream", "Stream", "https://getstream.io", "$499/月", False, ["可扩展", "聊天API", "活动流", "高性能"], "Stream是一个提供可扩展聊天和活动流API的平台，支持数百万用户的实时通信需求。它提供高性能的聊天SDK、动态消息流和AI审核功能，是大型社交应用和平台的首选通信基础设施。"),
    ("pubnub", "PubNub", "https://www.pubnub.com", "按量付费", False, ["实时", "数据流", "IoT", "低延迟"], "PubNub是一个全球实时数据流网络，提供低延迟的消息传递和物联网连接服务。它支持数百万并发连接，适用于实时协作、游戏、金融交易和IoT应用，是实时基础设施的领导者。"),
    ("ably", "Ably", "https://ably.com", "按量付费", False, ["高性能", "可靠", "发布订阅", "实时"], "Ably是一个高性能的实时消息传递平台，提供可靠的发布-订阅消息服务。它以卓越的消息传递保证、低延迟和强大的开发者体验著称，适用于需要高可靠性的实时应用场景。"),
    ("pusher", "Pusher", "https://pusher.com", "$49/月", False, ["WebSocket", "实时", "Web", "简单"], "Pusher是一个提供实时WebSocket服务的平台，让开发者能够轻松为Web和移动应用添加实时功能。它以简单的API、广泛的SDK支持和可靠的托管服务著称，是快速实现实时功能的首选。"),
    ("firebase", "Firebase", "https://firebase.google.com", "免费 + 按量付费", True, ["Google", "BaaS", "实时数据库", "移动开发"], "Firebase是Google推出的综合应用开发平台，提供后端即服务、实时数据库、认证、分析和AI功能。它帮助开发者快速构建高质量应用，无需管理服务器基础设施，是移动和Web开发的热门选择。"),
    ("supabase", "Supabase", "https://supabase.com", "免费 + $25/月", True, ["开源", "PostgreSQL", "自托管", "Firebase替代"], "Supabase是一个开源的Firebase替代方案，基于PostgreSQL构建。它提供实时数据库、认证、存储和边缘函数，支持自托管，是开发者对数据主权和开源有要求时的首选后端平台。"),
    ("appwrite", "Appwrite", "https://appwrite.io", "免费", True, ["开源", "BaaS", "Flutter", "开发者友好"], "Appwrite是一个开源的后端即服务平台，为Web、移动和Flutter开发者提供完整的后端解决方案。它提供数据库、认证、存储和函数，支持自托管，以开发者友好的API和文档著称。"),
    ("backendless", "Backendless", "https://backendless.com", "免费 + $25/月", True, ["可视化", "低代码", "后端", "易用"], "Backendless是一个可视化的应用后端平台，提供数据库、用户管理、消息推送和API服务。它以可视化的数据管理和代码生成工具著称，帮助开发者快速构建应用后端而无需编写大量代码。"),
    ("nestjs", "NestJS", "https://nestjs.com", "免费", True, ["TypeScript", "模块化", "企业级", "Node.js"], "NestJS是一个渐进式的Node.js框架，用于构建高效、可扩展的服务器端应用程序。它结合OOP、FP和FRP元素，提供模块化架构、内置支持TypeScript和强大的依赖注入系统，是现代Node.js开发的标准选择。"),
    ("express", "Express.js", "https://expressjs.com", "免费", True, ["极简", "Node.js", "Web框架", "中间件"], "Express.js是一个快速、极简的Node.js Web框架，提供了一组强大的功能来开发Web和移动应用。它是Node.js生态系统中最流行的框架，以灵活、简单和庞大的中间件生态著称。"),
    ("fastify", "Fastify", "https://www.fastify.io", "免费", True, ["高性能", "插件", "JSON Schema", "Node.js"], "Fastify是一个高性能的Node.js Web框架，以其极低的开销和强大的插件架构著称。它支持JSON Schema验证、内置日志和异步处理，是构建高性能API和微服务的理想选择。"),
    ("hapi", "Hapi", "https://hapi.dev", "免费", True, ["企业级", "配置优先", "验证", "Node.js"], "Hapi是一个用于构建应用和服务的丰富框架，以配置优先的设计理念和强大的插件系统著称。它内置输入验证、缓存、认证和日志，是企业级Node.js应用的可靠选择。"),
    ("koa", "Koa", "https://koajs.com", "免费", True, ["下一代", "async/await", "轻量", "Express团队"], "Koa是由Express原班人马打造的下一代Node.js Web框架，基于ES6的async/await设计。它体积更小、表现力更强，通过洋葱模型中间件和上下文对象，让异步编程更加优雅。"),
    ("sails-js", "Sails.js", "https://sailsjs.com", "免费", True, ["MVC", "实时", "ORM", "Socket.io"], "Sails.js是一个实时的MVC Web框架，基于Express和Socket.io构建。它遵循约定优于配置原则，提供ORM、自动REST API生成和实时双向通信，是构建数据密集型实时应用的理想框架。"),
    ("meteor", "Meteor", "https://www.meteor.com", "免费", True, ["全栈", "JavaScript", "实时同步", "同构"], "Meteor是一个开源的全栈JavaScript平台，用于快速构建高质量的Web和移动应用。它提供实时数据同步、同构代码和丰富的包生态，让开发者使用单一语言构建从前端到后端的完整应用。"),
    ("next-js", "Next.js", "https://nextjs.org", "免费 + $20/月", True, ["React", "SSR", "Vercel", "全栈"], "Next.js是Vercel推出的React全栈开发框架，提供服务器端渲染、静态生成和API路由功能。它是React生态中最流行的框架，支持App Router、Server Actions和边缘计算，是现代Web开发的标准。"),
    ("nuxt-js", "Nuxt.js", "https://nuxt.com", "免费", True, ["Vue", "SSR", "模块化", "全栈"], "Nuxt.js是Vue.js生态中的全栈开发框架，提供服务器端渲染、静态站点生成和模块化架构。它以开发者友好的API、自动导入和强大的模块生态著称，是Vue开发者构建生产级应用的首选。"),
    ("sveltekit", "SvelteKit", "https://kit.svelte.dev", "免费", True, ["Svelte", "高性能", "简洁", "全栈"], "SvelteKit是Svelte官方的全栈应用框架，提供服务器端渲染、路由和API端点。它以极小的打包体积、出色的性能和简洁的API设计著称，是追求性能和简洁的开发者的新兴选择。"),
    ("remix", "Remix", "https://remix.run", "免费", True, ["React", "Web标准", "渐进增强", "Shopify"], "Remix是一个现代React Web框架，专注于Web标准和渐进增强。它提供嵌套路由、数据加载和表单处理功能，以出色的用户体验和可访问性著称，已被Shopify收购并持续快速发展。"),
    ("astro", "Astro", "https://astro.build", "免费", True, ["内容驱动", "零JS", "岛屿架构", "高性能"], "Astro是一个现代化的内容驱动网站构建工具，以零JavaScript默认和出色的性能著称。它支持岛屿架构、多框架集成和边缘渲染，是构建营销网站、博客和文档站点的最佳选择。"),
    ("gatsby", "Gatsby", "https://www.gatsbyjs.com", "免费", True, ["React", "GraphQL", "静态生成", "PWA"], "Gatsby是一个基于React的静态站点生成器，利用GraphQL进行数据层管理。它提供丰富的插件生态、图像优化和增量构建功能，是构建高性能静态网站和渐进式Web应用的成熟选择。"),
    ("hugo", "Hugo", "https://gohugo.io", "免费", True, ["Go", "极速", "Markdown", "静态生成"], "Hugo是一个用Go语言编写的极速静态站点生成器，以毫秒级的构建速度著称。它使用Markdown、提供强大的模板系统和主题生态，是构建博客、文档和企业网站的高效工具。"),
    ("jekyll", "Jekyll", "https://jekyllrb.com", "免费", True, ["Ruby", "博客", "GitHub Pages", "经典"], "Jekyll是一个简单的Ruby静态网站生成器，特别适合博客。它使用Markdown和Liquid模板，与GitHub Pages无缝集成，是开发者创建技术博客和文档站点的经典选择。"),
    ("eleventy", "Eleventy", "https://www.11ty.dev", "免费", True, ["灵活", "多模板", "零配置", "无依赖"], "Eleventy是一个简单、灵活的静态站点生成器，支持多种模板语言。它以零配置起步、快速构建和对JavaScript框架无依赖著称，是追求简洁和灵活的开发者喜爱的工具。"),
    ("gridsome", "Gridsome", "https://gridsome.org", "免费", True, ["Vue", "GraphQL", "静态生成", "性能"], "Gridsome是一个基于Vue.js的静态站点生成器，灵感来自Gatsby。它提供GraphQL数据层、自动代码分割和渐进式图片加载，是Vue生态中构建高性能静态网站的框架。"),
    ("vuepress", "VuePress", "https://vuepress.vuejs.org", "免费", True, ["Vue", "文档", "Markdown", "开源"], "VuePress是一个Vue驱动的静态网站生成器，专注于文档站点。它以默认主题美观、Markdown增强和Vue组件嵌入著称，是Vue生态和开源项目文档的首选工具。"),
    ("docusaurus", "Docusaurus", "https://docusaurus.io", "免费", True, ["Meta", "React", "文档", "开源"], "Docusaurus是由Meta维护的开源文档网站构建器，使用React构建。它提供文档、博客和页面功能，内置搜索、国际化和版本管理，是技术团队和开源项目构建文档站点的热门选择。"),
    ("mkdocs", "MkDocs", "https://www.mkdocs.org", "免费", True, ["Python", "Markdown", "Material", "简单"], "MkDocs是一个快速、简单的Python静态文档生成器，使用Markdown。它以Material主题美观、插件丰富和配置简单著称，是Python项目和开发者文档的经典选择。"),
    ("gitbook", "GitBook", "https://www.gitbook.com", "免费 + $6.7/月", True, ["文档平台", "协作", "Git同步", "知识库"], "GitBook是一个现代的文档平台，将Markdown/Git同步与可视化编辑结合。它提供协作编辑、分析、API文档和知识库功能，是团队构建产品文档和知识管理的现代选择。"),
    ("notion", "Notion", "https://www.notion.so", "免费 + $8/月", True, ["工作空间", "笔记", "数据库", "AI写作"], "Notion是一个集笔记、文档、数据库和项目管理于一体的全能工作空间。它支持AI写作辅助、自动化和丰富的模板生态，是知识工作者和团队协作的必备工具，2026年持续引领生产力工具潮流。"),
    ("confluence", "Confluence", "https://www.atlassian.com/software/confluence", "$5.75/月", False, ["Atlassian", "团队协作", "知识管理", "Jira集成"], "Confluence是Atlassian推出的团队协作和知识管理平台，与Jira深度集成。它提供结构化文档、空间管理和强大的宏功能，是软件开发团队和大型组织管理知识和项目文档的标准工具。"),
    ("slite", "Slite", "https://slite.com", "$8/月", False, ["知识管理", "远程团队", "AI问答", "简洁"], "Slite是一个专注于团队知识管理的平台，提供简洁的文档编辑、AI问答和知识库功能。它以界面简洁、搜索强大和远程团队友好著称，是现代分布式团队管理知识的理想工具。"),
    ("tettra", "Tettra", "https://tettra.com", "$8.33/月", False, ["AI驱动", "知识库", "Slack集成", "团队"], "Tettra是一个AI驱动的团队知识库平台，专注于帮助团队快速创建、组织和查找内部知识。它提供AI自动分类、问答机器人和Slack集成，是提升团队知识共享效率的利器。"),
    ("nuclino", "Nuclino", "https://www.nuclino.com", "$5/月", False, ["轻量", "极简", "实时同步", "树状结构"], "Nuclino是一个轻量级的团队知识库和协作平台，以极简设计和即时同步著称。它提供树状结构组织、实时协作和即时搜索，是追求简洁高效的团队的理想知识管理工具。"),
    ("slab", "Slab", "https://slab.com", "免费 + $6.67/月", True, ["技术团队", "代码文档", "Markdown", "GitHub"], "Slab（已被Slite收购）是一个面向技术团队的知识库平台，专注于代码文档和技术规范。它提供Markdown编辑、代码高亮和GitHub集成，帮助工程团队高效管理技术知识。"),
    ("outline", "Outline", "https://www.getoutline.com", "免费", True, ["开源", "自托管", "精美", "Wiki"], "Outline是一个开源的团队知识库和Wiki工具，设计精美且功能强大。它支持Markdown编辑、Slack集成和细粒度权限控制，支持自托管，是注重数据隐私的团队的知识管理选择。"),
    ("appflowy", "AppFlowy", "https://www.appflowy.io", "免费", True, ["开源", "本地优先", "隐私", "Notion替代"], "AppFlowy是一个开源的Notion替代方案，提供本地优先的知识管理和项目管理功能。它支持离线使用、端到端加密和插件扩展，是注重隐私和开源的用户的理想选择。"),
    ("anytype", "Anytype", "https://anytype.io", "免费", True, ["本地优先", "去中心化", "知识图谱", "加密"], "Anytype是一个本地优先、去中心化的知识管理和协作工具。它基于对象类型和关系构建知识图谱，支持离线使用、点对点同步和加密，是追求数据主权用户的革命性工具。"),
    ("capacities", "Capacities", "https://capacities.io", "$12/月", False, ["对象驱动", "笔记", "知识图谱", "AI助手"], "Capacities是一个对象驱动的笔记和知识管理工具，将信息组织为类型化的对象而非传统文档。它支持网络视图、AI助手和强大的查询功能，是构建第二大脑的创新工具。"),
    ("logseq", "Logseq", "https://logseq.com", "免费", True, ["开源", "双向链接", "大纲", "本地存储"], "Logseq是一个开源的知识管理和协作平台，基于双向链接和大纲结构。它支持本地存储、图谱视图和插件扩展，是Roam Research的开源替代品，深受知识管理爱好者喜爱。"),
    ("obsidian", "Obsidian", "https://obsidian.md", "免费 + $50/年", True, ["本地优先", "双向链接", "插件", "Markdown"], "Obsidian是一个本地优先的知识库工具，基于Markdown和双向链接构建个人知识网络。它以强大的插件生态、图谱视图和极高的自定义性著称，是构建第二大脑和Zettelkasten系统的首选工具。"),
    ("roam-research", "Roam Research", "https://roamresearch.com", "$15/月", False, ["网络化思维", "双向链接", "块引用", "研究"], "Roam Research是一个开创性的网络化思维笔记工具，通过双向链接和块级引用重新定义了知识管理。它支持每日笔记、图谱视图和协作编辑，是研究者、作家和思想家的思维工具。"),
]

mcp_servers = [
    ("github-mcp", "GitHub MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/github", "免费", True, ["GitHub", "代码管理", "API", "DevOps"], "GitHub MCP服务器允许AI代理直接与GitHub API交互，实现仓库管理、代码搜索、Issue处理、Pull Request审查和发布管理。它是开发团队协作和代码管理自动化的核心工具，支持私有仓库和企业级GitHub Enterprise。"),
    ("figma-mcp", "Figma MCP", "https://github.com/GLips/Figma-Context-MCP", "免费", True, ["Figma", "设计", "组件库", "设计系统"], "Figma MCP服务器使AI代理能够访问和操作Figma设计文件，读取设计规范、导出资源、分析组件库和管理设计系统。它是连接设计与开发的桥梁，支持设计自动化和设计令牌提取。"),
    ("notion-mcp", "Notion MCP", "https://github.com/makenotion/notion-mcp-server", "免费", True, ["Notion", "知识库", "文档", "数据库"], "Notion MCP服务器让AI代理能够读写Notion页面、数据库和工作区。它支持内容创建、数据库查询、页面更新和权限管理，是构建AI驱动的知识管理和文档自动化工作流的核心工具。"),
    ("slack-mcp", "Slack MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/slack", "免费", True, ["Slack", "消息", "团队协作", "通知"], "Slack MCP服务器允许AI代理与Slack工作区交互，发送消息、管理频道、读取对话历史和集成工作流。它是构建AI驱动的团队协作和通知自动化的关键工具，支持丰富的消息格式和交互组件。"),
    ("discord-mcp", "Discord MCP", "https://github.com/v-3/discordmcp", "免费", True, ["Discord", "社区", "游戏", "机器人"], "Discord MCP服务器让AI代理能够与Discord服务器交互，管理频道、发送消息、读取对话和协调社区活动。它是游戏社区、开源项目和DAO组织实现AI驱动社区管理的理想工具。"),
    ("gmail-mcp", "Gmail MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/gmail", "免费", True, ["Gmail", "邮件", "Google", "通信"], "Gmail MCP服务器使AI代理能够访问Gmail账户，读取邮件、发送回复、管理标签和创建过滤器。它是构建AI驱动的邮件自动化、客户支持和日程管理的核心工具，支持Gmail API的完整功能。"),
    ("google-drive-mcp", "Google Drive MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/google-drive", "免费", True, ["Google Drive", "云存储", "文件管理", "Google"], "Google Drive MCP服务器允许AI代理访问和管理Google Drive中的文件和文件夹。它支持文件上传下载、权限管理、搜索和文档转换，是构建AI驱动的文档管理和内容处理工作流的重要工具。"),
    ("calendar-mcp", "Calendar MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/google-calendar", "免费", True, ["日历", "日程", "会议", "时间管理"], "Calendar MCP服务器让AI代理能够访问和管理日历事件，创建会议、查询空闲时间、发送邀请和设置提醒。它支持Google Calendar和Outlook，是构建AI驱动的日程管理和会议协调的核心工具。"),
    ("jira-mcp", "Jira MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/jira", "免费", True, ["Jira", "项目管理", "敏捷", "Atlassian"], "Jira MCP服务器允许AI代理与Jira实例交互，创建和管理Issue、查询项目状态、更新工作流和生成报告。它是软件开发团队实现AI驱动项目管理和自动化工作流的核心集成工具。"),
    ("confluence-mcp", "Confluence MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/confluence", "免费", True, ["Confluence", "文档", "知识库", "Atlassian"], "Confluence MCP服务器使AI代理能够读写Confluence页面和空间，搜索内容、管理权限和同步文档。它是企业知识管理和技术文档自动化的重要工具，支持Atlassian生态的完整集成。"),
    ("trello-mcp", "Trello MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/trello", "免费", True, ["Trello", "看板", "任务管理", "Atlassian"], "Trello MCP服务器让AI代理能够管理Trello看板、列表和卡片，创建任务、移动卡片和添加评论。它是小型团队和个人项目实现AI驱动任务管理的简便工具，支持Power-Up扩展。"),
    ("asana-mcp", "Asana MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/asana", "免费", True, ["Asana", "项目管理", "任务", "协作"], "Asana MCP服务器允许AI代理与Asana工作区交互，创建任务、更新项目、分配工作和生成进度报告。它是团队协作和项目管理自动化的重要工具，支持自定义字段和工作流规则。"),
    ("monday-mcp", "Monday MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/monday", "免费", True, ["Monday", "工作管理", "项目跟踪", "自动化"], "Monday MCP服务器让AI代理能够操作Monday.com工作板，管理项目、跟踪进度和自动化工作流。它支持丰富的列类型、自动化规则和集成，是多样化团队实现工作管理AI化的选择。"),
    ("linear-mcp", "Linear MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/linear", "免费", True, ["Linear", "Issue跟踪", "现代", "软件"], "Linear MCP服务器允许AI代理与Linear交互，管理Issue、项目和里程碑。它以极速体验和键盘优先设计著称，是现代软件开发团队实现AI驱动问题跟踪和项目规划的优雅工具。"),
    ("airtable-mcp", "Airtable MCP", "https://github.com/domdomegg/airtable-mcp-server", "免费", True, ["Airtable", "数据库", "无代码", "表格"], "Airtable MCP服务器让AI代理能够操作Airtable基地，创建记录、查询视图、管理字段和自动化工作流。它是无代码数据库和灵活内容管理自动化的核心工具，支持丰富的字段类型。"),
    ("supabase-mcp", "Supabase MCP", "https://github.com/supabase-community/supabase-mcp", "免费", True, ["Supabase", "PostgreSQL", "后端", "开源"], "Supabase MCP服务器允许AI代理直接操作Supabase项目，执行SQL查询、管理用户认证、操作存储桶和调用边缘函数。它是PostgreSQL数据库管理和后端自动化的强大工具，支持实时数据订阅。"),
    ("postgresql-mcp", "PostgreSQL MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres", "免费", True, ["PostgreSQL", "SQL", "数据库", "关系型"], "PostgreSQL MCP服务器让AI代理能够连接和操作PostgreSQL数据库，执行查询、管理Schema、优化性能和备份恢复。它是关系型数据库管理和数据分析自动化的核心工具，支持复杂SQL操作。"),
    ("mysql-mcp", "MySQL MCP", "https://github.com/designcomputer/mysql_mcp_server", "免费", True, ["MySQL", "Web数据库", "SQL", "LAMP"], "MySQL MCP服务器使AI代理能够连接和管理MySQL数据库，执行查询、管理用户、优化表结构和监控性能。它是Web应用数据库管理和LAMP/LEMP栈自动化的重要工具，支持主流MySQL版本。"),
    ("mongodb-mcp", "MongoDB MCP", "https://github.com/kiliczsh/mcp-mongo-server", "免费", True, ["MongoDB", "NoSQL", "文档数据库", "聚合"], "MongoDB MCP服务器允许AI代理操作MongoDB数据库，执行聚合查询、管理集合、创建索引和监控集群。它是文档数据库管理和NoSQL应用开发自动化的核心工具，支持Atlas云服务和本地部署。"),
    ("redis-mcp", "Redis MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/redis", "免费", True, ["Redis", "缓存", "内存数据库", "实时"], "Redis MCP服务器让AI代理能够管理Redis实例，操作数据结构、监控性能、配置集群和执行Lua脚本。它是缓存管理、实时数据处理和消息队列自动化的关键工具，支持Redis Stack扩展功能。"),
    ("sqlite-mcp", "SQLite MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite", "免费", True, ["SQLite", "嵌入式", "轻量", "本地"], "SQLite MCP服务器让AI代理能够操作SQLite数据库文件，执行查询、管理表结构和导入导出数据。它是嵌入式应用、本地数据存储和快速原型开发的理想工具，无需独立服务器进程。"),
    ("duckdb-mcp", "DuckDB MCP", "https://github.com/ktanzosh/duckdb_mcp_server", "免费", True, ["DuckDB", "分析", "OLAP", "大数据"], "DuckDB MCP服务器允许AI代理使用DuckDB进行高性能分析查询。它是一个进程内分析数据库，支持复杂SQL、Parquet读取和大数据集处理，是数据分析和科学计算自动化的利器。"),
    ("snowflake-mcp", "Snowflake MCP", "https://github.com/datawiz168/mcp-snowflake-server", "免费", True, ["Snowflake", "数据仓库", "云分析", "企业"], "Snowflake MCP服务器让AI代理能够操作Snowflake数据仓库，执行查询、管理仓库资源、监控使用情况和自动化ETL流程。它是企业级数据仓库管理和云分析自动化的重要工具。"),
    ("bigquery-mcp", "BigQuery MCP", "https://github.com/LucasHild/mcp-server-bigquery", "免费", True, ["BigQuery", "Google Cloud", "PB级", "分析"], "BigQuery MCP服务器允许AI代理与Google BigQuery交互，执行大规模SQL查询、管理数据集、优化查询成本和调度作业。它是PB级数据分析和云原生数据仓库自动化的核心工具。"),
    ("aws-mcp", "AWS MCP", "https://github.com/rishikavikondala/mcp-server-aws", "免费", True, ["AWS", "云管理", "DevOps", "基础设施"], "AWS MCP服务器让AI代理能够管理AWS资源，操作EC2、S3、Lambda、RDS等服务。它是云基础设施管理和DevOps自动化的核心工具，支持IAM权限和多区域部署。"),
    ("azure-mcp", "Azure MCP", "https://github.com/Azure-Samples/mcp-server-azure", "免费", True, ["Azure", "微软", "云管理", "企业"], "Azure MCP服务器允许AI代理管理Azure资源，操作虚拟机、存储账户、函数应用和数据库服务。它是Microsoft云生态管理和企业级云自动化的一站式工具，支持ARM模板和Bicep。"),
    ("gcp-mcp", "GCP MCP", "https://github.com/modelcontextprotocol/servers/tree/main/src/gcp", "免费", True, ["GCP", "Google Cloud", "云原生", "管理"], "GCP MCP服务器使AI代理能够操作Google Cloud Platform资源，管理Compute Engine、Cloud Storage、Cloud Functions和BigQuery。它是谷歌云生态管理和云原生应用自动化的核心工具。"),
    ("vercel-mcp", "Vercel MCP", "https://github.com/vercel/mcp-server", "免费", True, ["Vercel", "部署", "前端", "Serverless"], "Vercel MCP服务器让AI代理能够管理Vercel项目，执行部署、配置域名、管理环境变量和查看分析。它是前端开发团队实现AI驱动部署和运维自动化的专用工具，支持Next.js等框架。"),
    ("netlify-mcp", "Netlify MCP", "https://github.com/netlify/mcp-server", "免费", True, ["Netlify", "静态托管", "JAMstack", "CI/CD"], "Netlify MCP服务器允许AI代理管理Netlify站点，执行部署、配置表单、管理身份验证和边缘函数。它是JAMstack生态中实现AI驱动静态站点管理和自动化部署的重要工具。"),
    ("cloudflare-mcp", "Cloudflare MCP", "https://github.com/cloudflare/mcp-server", "免费", True, ["Cloudflare", "CDN", "边缘计算", "安全"], "Cloudflare MCP服务器让AI代理能够管理Cloudflare资源，配置DNS、部署Workers、管理CDN和安全规则。它是边缘计算和Web安全自动化管理的核心工具，支持D1数据库和KV存储。"),
    ("stripe-mcp", "Stripe MCP", "https://github.com/stripe/mcp-server", "免费", True, ["Stripe", "支付", "电商", "API"], "Stripe MCP服务器使AI代理能够与Stripe API交互，处理支付、管理订阅、生成发票和处理退款。它是在线业务实现AI驱动财务自动化和支付管理的核心工具，支持全球多种货币。"),
    ("paypal-mcp", "PayPal MCP", "https://github.com/paypal/mcp-server", "免费", True, ["PayPal", "支付", "全球", "商家"], "PayPal MCP服务器允许AI代理管理PayPal商家账户，处理支付、管理订阅、处理争议和多币种交易。它是电商和SaaS业务实现AI驱动支付管理的重要工具，支持全球200多个市场。"),
    ("twilio-mcp", "Twilio MCP", "https://github.com/twilio/mcp-server", "免费", True, ["Twilio", "通信", "SMS", "语音"], "Twilio MCP服务器让AI代理能够使用Twilio API发送SMS、拨打电话、管理号码和处理通信工作流。它是应用通信和客户互动自动化的核心工具，支持全球电信网络。"),
    ("sendgrid-mcp", "SendGrid MCP", "https://github.com/sendgrid/mcp-server", "免费", True, ["SendGrid", "邮件", "营销", "事务邮件"], "SendGrid MCP服务器使AI代理能够发送邮件、管理模板、操作联系人列表和追踪分析。它是邮件营销和事务邮件自动化的重要工具，支持高吞吐量的可靠邮件投递。"),
    ("mailgun-mcp", "Mailgun MCP", "https://github.com/mailgun/mcp-server", "免费", True, ["Mailgun", "邮件", "API", "开发者"], "Mailgun MCP服务器允许AI代理使用Mailgun API发送邮件、管理路由规则、维护列表和查看分析报告。它是开发者友好的邮件自动化工具，以强大的路由和日志功能著称。"),
    ("aws-ses-mcp", "AWS SES MCP", "https://github.com/aws-samples/mcp-server-ses", "免费", True, ["AWS SES", "邮件", "亚马逊", "批量"], "AWS SES MCP服务器让AI代理能够使用Amazon SES发送批量邮件和事务邮件，管理模板和验证身份。它是AWS生态中实现高吞吐量、低成本邮件自动化的核心服务工具。"),
    ("firebase-mcp", "Firebase MCP", "https://github.com/firebase/mcp-server", "免费", True, ["Firebase", "Google", "移动", "实时"], "Firebase MCP服务器使AI代理能够管理Firebase项目，操作用户认证、实时数据库、云存储和云消息。它是移动和Web应用后端自动化的核心工具，支持分析监控和远程配置。"),
    ("auth0-mcp", "Auth0 MCP", "https://github.com/auth0/mcp-server", "免费", True, ["Auth0", "认证", "安全", "SSO"], "Auth0 MCP服务器让AI代理能够管理Auth0租户，配置认证流程、管理用户、设置SSO和MFA。它是身份和访问管理自动化的企业级工具，支持多种协议和社交登录。"),
    ("clerk-mcp", "Clerk MCP", "https://github.com/clerk/mcp-server", "免费", True, ["Clerk", "认证", "React", "开发者"], "Clerk MCP服务器允许AI代理管理Clerk应用，操作用户认证、会话管理、组织管理和Webhook。它是现代Web应用（尤其是React/Next.js）身份管理的专用自动化工具。"),
    ("okta-mcp", "Okta MCP", "https://github.com/okta/mcp-server", "免费", True, ["Okta", "企业认证", "SSO", "身份"], "Okta MCP服务器让AI代理能够管理Okta组织，配置身份认证、SSO、生命周期管理和MFA策略。它是大型企业实现身份管理自动化和安全合规的核心工具。"),
    ("onelogin-mcp", "OneLogin MCP", "https://github.com/onelogin/mcp-server", "免费", True, ["OneLogin", "SSO", "身份管理", "企业"], "OneLogin MCP服务器使AI代理能够管理OneLogin账户，配置SSO、用户配置、安全策略和目录集成。它是企业级统一身份管理和访问控制自动化的重要工具。"),
    ("gitlab-mcp", "GitLab MCP", "https://github.com/gitlab/mcp-server", "免费", True, ["GitLab", "DevOps", "CI/CD", "代码托管"], "GitLab MCP服务器让AI代理能够管理GitLab项目，操作仓库、CI/CD流水线、Issue、MR和Wiki。它是DevOps团队实现全生命周期AI驱动自动化的核心工具，支持自托管和SaaS版本。"),
    ("bitbucket-mcp", "Bitbucket MCP", "https://github.com/bitbucket/mcp-server", "免费", True, ["Bitbucket", "Atlassian", "Git", "团队"], "Bitbucket MCP服务器允许AI代理管理Bitbucket仓库，执行代码审查、管理Pipeline、协调团队协作和部署。它是Atlassian生态中实现代码托管和CI/CD自动化的重要工具。"),
    ("jenkins-mcp", "Jenkins MCP", "https://github.com/jenkinsci/mcp-server", "免费", True, ["Jenkins", "CI/CD", "开源", "自动化"], "Jenkins MCP服务器让AI代理能够管理Jenkins实例，配置任务、管理插件、触发构建和查看日志。它是开源CI/CD领域实现自动化构建、测试和部署的核心工具。"),
    ("github-actions-mcp", "GitHub Actions MCP", "https://github.com/github/mcp-server-actions", "免费", True, ["GitHub Actions", "CI/CD", "自动化", "DevOps"], "GitHub Actions MCP服务器使AI代理能够管理工作流、Runner、密钥和Artifact，查看日志和配置缓存策略。它是GitHub生态中实现持续集成和持续部署自动化的核心组件。"),
    ("circleci-mcp", "CircleCI MCP", "https://github.com/circleci/mcp-server", "免费", True, ["CircleCI", "CI/CD", "并行", "云原生"], "CircleCI MCP服务器允许AI代理管理Pipeline、使用Orb、配置并行执行和查看日志。它是云原生CI/CD自动化工具，以快速构建和调试能力著称。"),
    ("travis-ci-mcp", "Travis CI MCP", "https://github.com/travis-ci/mcp-server", "免费", True, ["Travis CI", "CI/CD", "开源", "社区"], "Travis CI MCP服务器让AI代理能够管理构建、配置矩阵构建、部署和查看日志。它是开源社区中历史悠久的CI/CD自动化工具，支持多种语言和平台。"),
    ("docker-mcp", "Docker MCP", "https://github.com/docker/mcp-server", "免费", True, ["Docker", "容器", "DevOps", "镜像"], "Docker MCP服务器使AI代理能够管理镜像、容器、网络和卷，操作Compose和Registry。它是容器化应用开发和部署自动化的核心工具，支持Docker Desktop和Docker Hub集成。"),
    ("kubernetes-mcp", "Kubernetes MCP", "https://github.com/kubernetes/mcp-server", "免费", True, ["Kubernetes", "容器编排", "云原生", "集群"], "Kubernetes MCP服务器让AI代理能够管理Pod、Deployment、Service和ConfigMap，操作Helm和监控集群。它是云原生基础设施管理和容器编排自动化的标准工具。"),
    ("terraform-mcp", "Terraform MCP", "https://github.com/hashicorp/mcp-server-terraform", "免费", True, ["Terraform", "IaC", "多云", "HashiCorp"], "Terraform MCP服务器允许AI代理管理基础设施资源、状态、模块和Workspace。它是基础设施即代码（IaC）和多云平台管理自动化的行业标准工具，支持HCL编写。"),
    ("ansible-mcp", "Ansible MCP", "https://github.com/ansible/mcp-server", "免费", True, ["Ansible", "自动化", "配置管理", "Red Hat"], "Ansible MCP服务器让AI代理能够执行Playbook、管理库存和角色，操作Vault和插件。它是配置管理、应用部署和IT编排自动化的无代理解决方案，以简单易学著称。"),
    ("puppet-mcp", "Puppet MCP", "https://github.com/puppetlabs/mcp-server", "免费", True, ["Puppet", "配置管理", "企业", "IT"], "Puppet MCP服务器使AI代理能够管理清单、模块、节点和报告，操作Hiera和Console。它是大型企业实现基础设施自动化和合规管理的成熟工具，支持声明式配置语言。"),
    ("chef-mcp", "Chef MCP", "https://github.com/chef/mcp-server", "免费", True, ["Chef", "配置管理", "Ruby", "基础设施"], "Chef MCP服务器让AI代理能够管理Cookbook、Recipe和节点，执行基础设施自动化和合规审计。它是配置管理领域的专业工具，以Ruby-based的声明式语言和强大的测试框架著称。"),
    ("prometheus-mcp", "Prometheus MCP", "https://github.com/prometheus/mcp-server", "免费", True, ["Prometheus", "监控", "告警", "指标"], "Prometheus MCP服务器使AI代理能够查询指标、管理告警规则、配置Target和服务发现。它是云原生监控和告警领域的开源标准，支持多维数据模型和强大的查询语言PromQL。"),
    ("grafana-mcp", "Grafana MCP", "https://github.com/grafana/mcp-server", "免费", True, ["Grafana", "可视化", "仪表板", "监控"], "Grafana MCP服务器让AI代理能够管理仪表板、数据源、告警规则和用户权限。它是数据可视化和监控分析的领导平台，支持数百种数据源和丰富的面板插件生态。"),
    ("datadog-mcp", "Datadog MCP", "https://github.com/DataDog/mcp-server", "免费", True, ["Datadog", "APM", "全栈监控", "云"], "Datadog MCP服务器允许AI代理查询指标、分析日志、追踪APM和管理告警。它是云原生全栈监控和分析平台，提供基础设施、应用和安全统一的观测能力。"),
    ("new-relic-mcp", "New Relic MCP", "https://github.com/newrelic/mcp-server", "免费", True, ["New Relic", "APM", "可观测性", "性能"], "New Relic MCP服务器让AI代理能够查询APM数据、分析基础设施监控、管理告警和利用AI洞察。它是应用性能监控和可观测性领域的老牌平台，支持全栈可见性。"),
    ("sentry-mcp", "Sentry MCP", "https://github.com/getsentry/mcp-server", "免费", True, ["Sentry", "错误追踪", "性能", "开发者"], "Sentry MCP服务器使AI代理能够追踪错误、管理Issue、监控Release性能和分析影响范围。它是开发者首选的错误监控和性能追踪平台，支持多种语言和框架。"),
    ("bugsnag-mcp", "Bugsnag MCP", "https://github.com/bugsnag/mcp-server", "免费", True, ["Bugsnag", "稳定性", "错误检测", "移动"], "Bugsnag MCP服务器让AI代理能够检测错误、管理Release、评估稳定性评分和分析趋势。它以移动和Web应用的错误监控著称，帮助团队快速发现和修复生产问题。"),
    ("rollbar-mcp", "Rollbar MCP", "https://github.com/rollbar/mcp-server", "免费", True, ["Rollbar", "错误追踪", "部署", "RQL"], "Rollbar MCP服务器允许AI代理追踪错误、分配人员、监控部署和执行RQL查询。它是实时错误监控平台，以快速的通知和丰富的上下文信息帮助团队缩短MTTR。"),
    ("logrocket-mcp", "LogRocket MCP", "https://github.com/LogRocket/mcp-server", "免费", True, ["LogRocket", "会话回放", "UX", "分析"], "LogRocket MCP服务器让AI代理能够回放用户会话、监控性能、追踪错误和分析用户行为。它是前端监控和用户体验分析平台，帮助团队理解用户遇到的问题。"),
    ("fullstory-mcp", "FullStory MCP", "https://github.com/fullstory/mcp-server", "免费", True, ["FullStory", "会话回放", "DXI", "分析"], "FullStory MCP服务器使AI代理能够回放会话、分析用户旅程、构建漏斗和查看热力图。它是数字体验智能（DXI）平台，帮助产品团队优化用户体验和转化率。"),
    ("hotjar-mcp", "Hotjar MCP", "https://github.com/hotjar/mcp-server", "免费", True, ["Hotjar", "热力图", "反馈", "UX"], "Hotjar MCP服务器让AI代理能够查看热力图、回放会话、收集用户反馈和分析调查。它是用户体验研究和行为分析的热门工具，帮助团队理解用户行为模式。"),
    ("mixpanel-mcp", "Mixpanel MCP", "https://github.com/mixpanel/mcp-server", "免费", True, ["Mixpanel", "产品分析", "事件追踪", "增长"], "Mixpanel MCP服务器允许AI代理追踪事件、分析漏斗、计算留存和构建用户画像。它是产品分析和用户行为追踪平台，帮助团队做出数据驱动的产品决策。"),
    ("amplitude-mcp", "Amplitude MCP", "https://github.com/amplitude/mcp-server", "免费", True, ["Amplitude", "产品智能", "实验", "归因"], "Amplitude MCP服务器使AI代理能够分析用户行为、运行实验、构建用户画像和归因分析。它是产品智能平台，帮助团队优化产品体验和推动用户增长。"),
    ("segment-mcp", "Segment MCP", "https://github.com/segmentio/mcp-server", "免费", True, ["Segment", "CDP", "数据管道", "隐私"], "Segment MCP服务器让AI代理能够管理数据源、配置目的地、执行身份解析和监控数据质量。它是客户数据平台（CDP）的领导者，帮助企业统一和管理客户数据。"),
    ("rudderstack-mcp", "Rudderstack MCP", "https://github.com/rudderlabs/mcp-server", "免费", True, ["Rudderstack", "CDP", "开源", "隐私"], "Rudderstack MCP服务器允许AI代理管理数据管道、配置源和目的地、执行Transformations。它是开源的客户数据平台替代方案，强调数据隐私和仓库优先架构。"),
    ("customer-io-mcp", "Customer.io MCP", "https://github.com/customerio/mcp-server", "免费", True, ["Customer.io", "营销自动化", "消息", "行为触发"], "Customer.io MCP服务器使AI代理能够管理营销活动、构建用户细分、设计消息模板和A/B测试。它是行为驱动营销自动化平台，帮助团队基于用户行为发送精准消息。"),
    ("braze-mcp", "Braze MCP", "https://github.com/braze-inc/mcp-server", "免费", True, ["Braze", "跨渠道", "Canvas", "营销"], "Braze MCP服务器让AI代理能够管理跨渠道营销活动、设计Canvas用户旅程、配置Segment和消息模板。它是领先的客户互动平台，支持移动、Web、邮件等多渠道营销。"),
    ("iterable-mcp", "Iterable MCP", "https://github.com/iterable/mcp-server", "免费", True, ["Iterable", "营销", "AI优化", "用户旅程"], "Iterable MCP服务器允许AI代理管理营销活动、构建用户旅程、配置Segment和利用AI优化。它是现代营销自动化平台，以强大的跨渠道编排和AI能力著称。"),
    ("klaviyo-mcp", "Klaviyo MCP", "https://github.com/klaviyo/mcp-server", "免费", True, ["Klaviyo", "电商", "预测", "邮件"], "Klaviyo MCP服务器使AI代理能够管理Flow自动化、构建Segment、设计模板和执行A/B测试。它是电商领域领先的营销自动化平台，以预测分析和Shopify深度集成著称。"),
    ("mailchimp-mcp", "Mailchimp MCP", "https://github.com/mailchimp/mcp-server", "免费", True, ["Mailchimp", "邮件营销", "Audience", "品牌"], "Mailchimp MCP服务器让AI代理能够管理邮件活动、维护Audience、构建自动化和创建着陆页。它是全球知名的邮件营销平台，以易用性和丰富的模板生态著称。"),
    ("hubspot-mcp", "HubSpot MCP", "https://github.com/HubSpot/mcp-server", "免费", True, ["HubSpot", "CRM", "入站营销", "销售"], "HubSpot MCP服务器允许AI代理管理CRM、营销自动化、销售管道和客户服务。它是入站营销和CRM领域的领导者，提供从营销到销售到服务的完整客户平台。"),
    ("salesforce-mcp", "Salesforce MCP", "https://github.com/salesforce/mcp-server", "免费", True, ["Salesforce", "CRM", "Sales Cloud", "企业"], "Salesforce MCP服务器使AI代理能够管理CRM记录、Sales Cloud、Service Cloud和Marketing Cloud。它是全球最大的CRM平台，为企业提供销售、服务和营销自动化能力。"),
    ("zendesk-mcp", "Zendesk MCP", "https://github.com/zendesk/mcp-server", "免费", True, ["Zendesk", "客服", "工单", "知识库"], "Zendesk MCP服务器让AI代理能够管理Ticket、知识库、Chat和Talk通话。它是客户服务和支持平台的领导者，帮助企业构建卓越的客户体验。"),
    ("intercom-mcp", "Intercom MCP", "https://github.com/intercom/mcp-server", "免费", True, ["Intercom", "客户沟通", "产品内消息", "支持"], "Intercom MCP服务器允许AI代理管理客户对话、产品内消息、Series自动化和Outbound活动。它是现代客户沟通平台，以强大的Messenger和产品内互动能力著称。"),
    ("freshdesk-mcp", "Freshdesk MCP", "https://github.com/freshdesk/mcp-server", "免费", True, ["Freshdesk", "客服", "多渠道", "SLA"], "Freshdesk MCP服务器使AI代理能够管理工单、知识库、自动化规则和多渠道支持。它是成长型企业客户服务的热门选择，以易用性和 affordability 著称。"),
    ("zapier-mcp", "Zapier MCP", "https://github.com/zapier/mcp-server", "免费", True, ["Zapier", "自动化", "无代码", "集成"], "Zapier MCP服务器让AI代理能够管理Zap工作流、连接应用、配置Webhook和过滤器。它是无代码自动化平台的先驱，支持连接数千种应用实现工作流自动化。"),
    ("make-mcp", "Make MCP", "https://github.com/make/mcp-server", "免费", True, ["Make", "可视化", "自动化", "场景"], "Make MCP服务器允许AI代理管理Scenario、连接模块、配置调度和错误处理。它是可视化工作流自动化平台，以强大的数据转换和可视化编排能力著称。"),
    ("n8n-mcp", "n8n MCP", "https://github.com/n8n-io/mcp-server", "免费", True, ["n8n", "开源", "工作流", "自托管"], "n8n MCP服务器让AI代理能够管理工作流、连接节点、配置Webhook和处理错误恢复。它是开源工作流自动化平台，支持自托管和丰富的社区节点生态。"),
    ("workato-mcp", "Workato MCP", "https://github.com/workato/mcp-server", "免费", True, ["Workato", "企业", "集成", "自动化"], "Workato MCP服务器使AI代理能够管理Recipe、连接应用、配置API管理和数据同步。它是企业级集成和自动化平台，以强大的安全合规和IT治理能力著称。"),
    ("tray-io-mcp", "Tray.io MCP", "https://github.com/trayio/mcp-server", "免费", True, ["Tray.io", "云集成", "企业", "自动化"], "Tray.io MCP服务器让AI代理能够管理工作流、管理连接器、配置数据转换和企业安全。它是云原生企业集成平台，以强大的API管理和自动化能力著称。"),
    ("openai-mcp", "OpenAI MCP", "https://github.com/openai/mcp-server", "免费", True, ["OpenAI", "GPT", "AI模型", "API"], "OpenAI MCP服务器让AI代理能够直接调用OpenAI API，管理模型、执行对话、处理嵌入和微调任务。它是利用GPT-4、GPT-3.5和DALL-E等先进AI能力的核心集成工具。"),
    ("anthropic-mcp", "Anthropic MCP", "https://github.com/anthropics/mcp-server", "免费", True, ["Anthropic", "Claude", "AI安全", "API"], "Anthropic MCP服务器使AI代理能够调用Claude API，利用Claude 3.5 Sonnet等先进模型进行推理、分析和内容生成。它以强大的安全对齐和长上下文能力著称，是企业AI应用的重要工具。"),
    ("pinecone-mcp", "Pinecone MCP", "https://github.com/pinecone-io/mcp-server", "免费", True, ["Pinecone", "向量数据库", "RAG", "AI搜索"], "Pinecone MCP服务器让AI代理能够管理向量索引、执行相似性搜索、处理嵌入和管理命名空间。它是领先的托管向量数据库，为RAG系统和语义搜索提供高性能的基础设施。"),
    ("weaviate-mcp", "Weaviate MCP", "https://github.com/weaviate/mcp-server", "免费", True, ["Weaviate", "向量数据库", "GraphQL", "AI原生"], "Weaviate MCP服务器允许AI代理管理向量数据库、执行语义搜索、处理多模态数据和利用GraphQL查询。它是AI原生的向量数据库，支持模块化AI集成和混合搜索能力。"),
    ("qdrant-mcp", "Qdrant MCP", "https://github.com/qdrant/mcp-server", "免费", True, ["Qdrant", "向量数据库", "Rust", "开源"], "Qdrant MCP服务器使AI代理能够管理向量集合、执行相似性搜索、处理过滤和管理集群。它是用Rust编写的高性能向量数据库，以速度和可扩展性著称，支持云和本地部署。"),
    ("chroma-mcp", "Chroma MCP", "https://github.com/chroma-core/mcp-server", "免费", True, ["Chroma", "向量数据库", "开源", "嵌入式"], "Chroma MCP服务器让AI代理能够管理向量存储、执行相似性搜索、处理文档嵌入和管理集合。它是面向AI应用的开源嵌入式数据库，以简单易用和开发者友好著称。"),
    ("milvus-mcp", "Milvus MCP", "https://github.com/milvus-io/mcp-server", "免费", True, ["Milvus", "向量数据库", "Zilliz", "分布式"], "Milvus MCP服务器允许AI代理管理向量数据库、执行十亿级相似性搜索、处理多模态数据和分布式部署。它是面向AI应用的开源向量数据库，支持GPU加速和云原生架构。"),
    ("neo4j-mcp", "Neo4j MCP", "https://github.com/neo4j/mcp-server", "免费", True, ["Neo4j", "图数据库", "知识图谱", "Cypher"], "Neo4j MCP服务器使AI代理能够执行Cypher查询、管理图数据库、构建知识图谱和分析关系。它是领先的图数据库平台，为AI应用提供强大的关系推理和知识表示能力。"),
    ("elasticsearch-mcp", "Elasticsearch MCP", "https://github.com/elastic/mcp-server", "免费", True, ["Elasticsearch", "搜索", "日志", "Elastic"], "Elasticsearch MCP服务器让AI代理能够执行搜索查询、管理索引、分析日志和构建仪表板。它是分布式搜索和分析引擎的领导者，为全文搜索、日志分析和AI应用提供强大支持。"),
    ("opensearch-mcp", "OpenSearch MCP", "https://github.com/opensearch-project/mcp-server", "免费", True, ["OpenSearch", "搜索", "开源", "AWS"], "OpenSearch MCP服务器允许AI代理执行搜索、管理索引、分析日志和构建可视化。它是Elasticsearch的开源分支，由AWS主导，提供企业级的搜索、分析和可观测性能力。"),
    ("cloudwatch-mcp", "CloudWatch MCP", "https://github.com/aws-samples/mcp-server-cloudwatch", "免费", True, ["CloudWatch", "监控", "日志", "AWS"], "CloudWatch MCP服务器使AI代理能够查询指标、分析日志、管理告警和创建仪表板。它是AWS生态中监控和可观测性的核心服务，为云资源提供全面的可见性。"),
    ("route53-mcp", "Route53 MCP", "https://github.com/aws-samples/mcp-server-route53", "免费", True, ["Route53", "DNS", "AWS", "域名"], "Route53 MCP服务器让AI代理能够管理DNS记录、配置健康检查、管理域名和流量策略。它是AWS的高可用DNS服务，为全球应用提供可靠的域名解析和流量管理。"),
    ("dynamodb-mcp", "DynamoDB MCP", "https://github.com/aws-samples/mcp-server-dynamodb", "免费", True, ["DynamoDB", "NoSQL", "AWS", "键值"], "DynamoDB MCP服务器使AI代理能够执行查询、管理表、配置索引和监控性能。它是AWS托管的NoSQL数据库，以毫秒级延迟和无限扩展能力著称，支持键值和文档模型。"),
    ("sagemaker-mcp", "SageMaker MCP", "https://github.com/aws-samples/mcp-server-sagemaker", "免费", True, ["SageMaker", "ML", "AWS", "模型训练"], "SageMaker MCP服务器让AI代理能够管理笔记本、训练模型、部署端点和管理实验。它是AWS的机器学习平台，为数据科学家和开发者提供完整的ML工作流自动化能力。"),
    ("bedrock-mcp", "Amazon Bedrock MCP", "https://github.com/aws-samples/mcp-server-bedrock", "免费", True, ["Bedrock", "基础模型", "AWS", "生成式AI"], "Amazon Bedrock MCP服务器使AI代理能够调用基础模型、管理知识库、配置代理和微调模型。它是AWS的统一生成式AI平台，支持Claude、Llama、Stable Diffusion等多种模型。"),
    ("openrouter-mcp", "OpenRouter MCP", "https://github.com/openrouter/mcp-server", "免费", True, ["OpenRouter", "模型路由", "API", "性价比"], "OpenRouter MCP服务器让AI代理能够访问数百种AI模型，自动选择最优模型并管理成本。它是AI模型的统一路由平台，以标准化API和竞争性价格著称，支持GPT、Claude、Llama等。"),
    ("perplexity-mcp", "Perplexity MCP", "https://github.com/perplexity/mcp-server", "免费", True, ["Perplexity", "AI搜索", "研究", "实时"], "Perplexity MCP服务器让AI代理能够执行实时网络搜索、获取引用答案、进行深度研究和管理搜索历史。它是AI驱动搜索平台的代表，为代理提供最新的互联网信息和可靠的来源引用。"),
    ("tavily-mcp", "Tavily MCP", "https://github.com/tavily-ai/mcp-server", "免费", True, ["Tavily", "AI搜索", "研究API", "RAG"], "Tavily MCP服务器使AI代理能够执行针对AI优化的网络搜索，获取结构化结果和来源引用。它是专为RAG系统和AI研究代理设计的搜索API，以高质量的相关结果和完整的引用著称。"),
]

# Generate all tools
all_tools = []
for idx, t in enumerate(ai_agents):
    all_tools.append(make_tool(idx, t[0], t[1], "ai-agent", t[3], t[4], t[5], t[6], t[2]))
for idx, t in enumerate(mcp_servers):
    all_tools.append(make_tool(idx + len(ai_agents), t[0], t[1], "mcp", t[3], t[4], t[5], t[6], t[2]))

with open("/workspace/data/tools-batch-6.json", "w", encoding="utf-8") as f:
    json.dump(all_tools, f, ensure_ascii=False, indent=2)

print(f"Generated {len(all_tools)} tools to /workspace/data/tools-batch-6.json")
print(f"AI Agents: {len(ai_agents)}, MCP Servers: {len(mcp_servers)}")