import json
import random
from datetime import datetime, timedelta

def random_date():
    start = datetime(2026, 6, 15)
    end = datetime(2026, 6, 29)
    delta = end - start
    return (start + timedelta(days=random.randint(0, delta.days))).strftime("%Y-%m-%d")

def random_views():
    return random.randint(5000, 150000)

def generate_tool(idx, raw, category):
    id_, name, url, price, is_free, tags, desc = raw
    seo_title = f"{name} - 领先的{'AI营销' if category=='ai-marketing' else 'AI教育'}平台"
    # Generate fields
    features = [
        f"AI驱动的{name.split()[0]}核心功能优化",
        f"智能数据分析与深度洞察报告",
        f"自动化工作流与任务管理",
        f"多平台无缝集成与同步",
        f"实时协作与团队共享功能",
        f"个性化推荐与自适应学习"
    ]
    if category == "ai-marketing":
        features = [
            f"AI智能营销自动化与优化",
            f"多渠道数据整合与深度分析",
            f"精准客户细分与个性化触达",
            f"实时ROI追踪与效果归因",
            f"A/B测试与智能创意优化",
            f"全渠道营销编排与协同"
        ]
    competitors = []
    if category == "ai-marketing":
        competitors = ["HubSpot", "Salesforce", "Marketo"]
    else:
        competitors = ["Khan Academy", "Coursera", "Duolingo"]
    use_cases = [
        f"{name.split()[0]}日常核心工作场景",
        "团队协作与项目管理",
        "数据驱动决策支持",
        "客户/学生体验优化",
        "效率提升与流程自动化"
    ]
    if category == "ai-marketing":
        use_cases = [
            "数字营销活动策划与执行",
            "潜在客户获取与培育",
            "品牌内容创作与分发",
            "客户数据分析与洞察",
            "销售转化与留存提升"
        ]
    else:
        use_cases = [
            "在线课程学习与知识获取",
            "技能评估与能力提升",
            "课堂教学与互动反馈",
            "学术研究与文献管理",
            "考试备考与认证获取"
        ]
    seo_desc = f"{name}是领先的{category=='ai-marketing' and 'AI营销' or 'AI教育'}平台，提供{desc[:30]}...等强大功能。"
    if len(seo_desc) > 80:
        seo_desc = seo_desc[:77] + "..."
    elif len(seo_desc) < 50:
        seo_desc += "帮助用户高效达成目标，提升整体效果。"
    return {
        "id": id_,
        "name": name,
        "logo": f"https://api.dicebear.com/7.x/shapes/svg?seed={id_}",
        "description": desc,
        "url": url,
        "price": price,
        "isFree": is_free,
        "tags": tags,
        "category": category,
        "rating": round(random.uniform(3.5, 5.0), 1),
        "updatedAt": random_date(),
        "screenshots": [f"https://picsum.photos/seed/{id_}1/800/500"],
        "features": features,
        "competitors": competitors,
        "useCases": use_cases,
        "seoTitle": f"{seo_title} | AI Navigator Pro",
        "seoDescription": seo_desc,
        "featured": idx < 5,
        "trending": idx < 10,
        "views": random_views()
    }

# Marketing tools core data
marketing = [
    ("hubspot","HubSpot","https://www.hubspot.com","免费 + $800/月",False,["营销自动化","CRM","邮件营销","销售","入站营销"],"HubSpot是全球领先的入站营销、销售和客服平台，提供AI驱动的营销自动化工具，帮助企业吸引访客、转化潜在客户并达成交易。"),
    ("salesforce-einstein","Salesforce Einstein","https://www.salesforce.com/einstein","自定义定价",False,["CRM","AI预测","销售智能","客户洞察","自动化"],"Salesforce Einstein是内置在Salesforce平台上的AI技术，通过预测分析和智能自动化帮助企业提升销售效率和客户满意度。"),
    ("marketo","Marketo Engage","https://business.adobe.com/products/marketo/adobe-marketo.html","自定义定价",False,["营销自动化","B2B营销","线索评分","邮件营销","Adobe"],"Marketo Engage是Adobe旗下的B2B营销自动化平台，利用AI实现精准线索评分、个性化内容和跨渠道营销编排。"),
    ("semrush","Semrush","https://www.semrush.com","免费 + $119.95/月",True,["SEO","关键词研究","竞争分析","内容营销","PPC"],"Semrush是全球知名的数字营销工具套件，提供AI增强的SEO审计、关键词研究、竞争对手分析和内容优化建议。"),
    ("ahrefs","Ahrefs","https://ahrefs.com","$99/月起",False,["SEO","外链分析","关键词研究","排名追踪","站点审计"],"Ahrefs是专业SEO人员首选的工具，拥有强大的外链数据库和AI驱动的内容探索功能，帮助网站提升搜索排名。"),
    ("moz","Moz Pro","https://moz.com","$99/月起",False,["SEO","域名权威","排名追踪","站点审计","关键词"],"Moz Pro提供全面的SEO工具集，包括标志性的域名权威评分、关键词探索和AI辅助的页面优化建议。"),
    ("surfer-seo","Surfer SEO","https://surferseo.com","$49/月起",False,["内容优化","SEO","SERP分析","关键词","NLP"],"Surfer SEO利用AI和自然语言处理技术分析排名前10的页面，提供实时的内容优化建议以提升搜索排名。"),
    ("clearscope","Clearscope","https://www.clearscope.io","$170/月起",False,["内容优化","NLP","SEO","内容策略","语义分析"],"Clearscope是高端内容优化平台，使用NLP技术分析搜索意图，帮助编辑团队创建高质量、高排名的内容。"),
    ("marketmuse","MarketMuse","https://www.marketmuse.com","自定义定价",False,["内容智能","SEO","主题建模","内容规划","AI写作"],"MarketMuse运用AI进行深度主题建模和内容差距分析，帮助企业建立权威性的内容集群和营销策略。"),
    ("frase","Frase","https://www.frase.io","$14.99/月起",False,["内容优化","SEO","AI写作","研究","问答"],"Frase将AI内容研究与SEO优化结合，通过分析搜索查询快速生成优化大纲和内容草稿。"),
    ("jasper","Jasper","https://www.jasper.ai","$49/月起",False,["AI写作","营销文案","品牌声音","内容创作","多语言"],"Jasper是企业级AI写作助手，支持品牌声音定制和团队协作，可快速生成高质量营销文案和长篇内容。"),
    ("copy-ai","Copy.ai","https://www.copy.ai","免费 + $36/月",True,["AI写作","营销文案","销售邮件","社交媒体","自动化"],"Copy.ai提供超过90种AI写作模板，帮助营销人员快速生成社交媒体帖子、广告文案和销售邮件。"),
    ("writesonic","Writesonic","https://writesonic.com","免费 + $13/月",True,["AI写作","SEO","聊天机器人","内容创作","图像生成"],"Writesonic是集AI写作、SEO优化和聊天机器人于一体的全能内容平台，支持实时联网获取最新信息。"),
    ("anyword","Anyword","https://anyword.com","$49/月起",False,["AI写作","预测分析","广告文案","营销","数据驱动"],"Anyword利用预测分析技术评估文案效果，帮助营销人员在发布前选择转化率最高的文案版本。"),
    ("adzis","AdZis","https://adzis.com","自定义定价",False,["电商内容","产品描述","AI写作","SEO","批量生成"],"AdZis专注电商领域，利用AI批量生成高质量产品描述、类别页面和SEO优化内容。"),
    ("phrasee","Phrasee","https://phrasee.co","自定义定价",False,["邮件营销","品牌语言","AI文案","优化","个性化"],"Phrasee使用生成式AI优化邮件主题行和营销文案，同时确保品牌语言和语调的一致性。"),
    ("persado","Persado","https://www.persado.com","自定义定价",False,["营销文案","情感AI","个性化","数据分析","全渠道"],"Persado是领先的生成式AI营销平台，通过情感分析和个性化消息提升跨渠道营销转化率。"),
    ("drift","Drift","https://www.drift.com","免费 + $2500/月",True,["对话营销","聊天机器人","销售","潜在客户","实时聊天"],"Drift是对话式营销先驱，利用AI聊天机器人实时与网站访客互动，加速销售线索转化。"),
    ("intercom","Intercom","https://www.intercom.com","$74/月起",False,["客户沟通","聊天机器人","产品导览","消息","支持"],"Intercom提供AI驱动的客户沟通平台，结合聊天机器人、产品导览和消息自动化提升用户体验。"),
    ("zendesk","Zendesk","https://www.zendesk.com","$55/月起",False,["客户服务","工单管理","AI聊天","知识库","CRM"],"Zendesk是全球知名的客户服务解决方案，集成AI聊天机器人和智能工单路由，提升支持效率。"),
    ("freshdesk","Freshdesk","https://freshdesk.com","免费 + $15/月",True,["客户服务","工单","AI辅助","自动化","知识库"],"Freshdesk是Freshworks旗下的客户支持软件，提供AI驱动的工单分类、自动回复和知识库建议。"),
    ("crisp","Crisp","https://crisp.chat","免费 + $25/月",True,["实时聊天","聊天机器人","共享收件箱","CRM","营销"],"Crisp是适合中小企业的全能客户沟通平台，集成实时聊天、聊天机器人和多渠道消息管理。"),
    ("tidio","Tidio","https://www.tidio.com","免费 + $29/月",True,["实时聊天","聊天机器人","邮件","自动化","销售"],"Tidio为电商和中小企业提供AI聊天机器人和实时聊天解决方案，提升网站转化率和客户满意度。"),
    ("livechat","LiveChat","https://www.livechat.com","$20/月起",False,["实时聊天","客服","销售","报告","集成"],"LiveChat是行业领先的实时聊天软件，结合AI访客分析和预设回复，帮助企业高效处理客户咨询。"),
    ("olark","Olark","https://www.olark.com","$29/月起",False,["实时聊天","客户洞察","CRM","自动化","报告"],"Olark提供简洁高效的实时聊天解决方案，通过AI驱动的访客洞察和自动化规则提升客户互动质量。"),
    ("chatfuel","Chatfuel","https://chatfuel.com","$14.99/月起",False,["聊天机器人","Facebook","Instagram","自动化","电商"],"Chatfuel是无代码聊天机器人平台，专注Facebook Messenger和Instagram自动化营销与客户服务。"),
    ("manychat","ManyChat","https://manychat.com","免费 + $15/月",True,["聊天机器人","Instagram","WhatsApp","Facebook","自动化"],"ManyChat是领先的社交聊天机器人平台，帮助企业在Instagram、WhatsApp和Messenger上自动获取和培育客户。"),
    ("mobilemonkey","MobileMonkey","https://mobilemonkey.com","自定义定价",False,["聊天机器人","短信","Facebook","B2C","自动化"],"MobileMonkey提供多渠道聊天机器人和短信营销工具，帮助B2C企业实现客户获取和再营销自动化。"),
    ("sendpulse","SendPulse","https://sendpulse.com","免费 + $8/月",True,["邮件营销","短信","聊天机器人","CRM","自动化"],"SendPulse是全渠道营销平台，集成邮件、短信、聊天机器人和CRM，利用AI优化发送时间和内容。"),
    ("mailchimp","Mailchimp","https://mailchimp.com","免费 + $13/月",True,["邮件营销","自动化","着陆页","受众管理","分析"],"Mailchimp是全球最受欢迎的邮件营销平台，提供AI驱动的内容优化、发送时间预测和受众细分功能。"),
    ("klaviyo","Klaviyo","https://www.klaviyo.com","免费 + $45/月",True,["邮件营销","短信","电商","自动化","CDP"],"Klaviyo是电商营销自动化首选，深度集成Shopify等平台，利用AI进行精准客户细分和个性化推荐。"),
    ("activecampaign","ActiveCampaign","https://www.activecampaign.com","$29/月起",False,["邮件营销","CRM","自动化","销售","机器学习"],"ActiveCampaign将邮件营销与CRM和销售自动化结合，利用机器学习预测最佳发送时间和客户行为。"),
    ("convertkit","ConvertKit","https://convertkit.com","免费 + $9/月",True,["邮件营销","创作者","着陆页","自动化","电子商务"],"ConvertKit专为创作者设计，提供简洁的邮件营销自动化和AI辅助内容推荐，帮助创作者变现。"),
    ("drip","Drip","https://www.drip.com","$39/月起",False,["电商CRM","邮件营销","自动化","个性化","分析"],"Drip是专为电商打造的CRM和邮件营销平台，利用AI实现深度客户洞察和个性化购物体验。"),
    ("getresponse","GetResponse","https://www.getresponse.com","免费 + $19/月",True,["邮件营销","着陆页","自动化","网络研讨会","AI"],"GetResponse是全功能数字营销平台，提供AI邮件生成器、自动化漏斗和内置网络研讨会功能。"),
    ("brevo","Brevo (Sendinblue)","https://www.brevo.com","免费 + $25/月",True,["邮件营销","短信","CRM","自动化","聊天"],"Brevo原Sendinblue，是欧洲领先的营销平台，提供AI驱动的邮件设计、发送优化和CRM功能。"),
    ("moosend","Moosend","https://moosend.com","$9/月起",False,["邮件营销","自动化","着陆页","电商","AI"],"Moosend提供高性价比的邮件营销和自动化解决方案，利用AI优化邮件内容和发送策略。"),
    ("omnisend","Omnisend","https://www.omnisend.com","免费 + $16/月",True,["电商营销","邮件","短信","推送","自动化"],"Omnisend专注电商全渠道营销，集成邮件、短信和推送通知，利用AI实现智能购物车挽回。"),
    ("iterable","Iterable","https://iterable.com","自定义定价",False,["跨渠道营销","个性化","AI","B2C","移动营销"],"Iterable是企业级跨渠道营销平台，利用AI在正确的时间通过正确的渠道传递个性化消息。"),
    ("customer-io","Customer.io","https://customer.io","$100/月起",False,["行为邮件","自动化","数据驱动","B2B","SaaS"],"Customer.io基于用户行为触发邮件和消息，利用AI分析用户旅程并优化转化漏斗。"),
    ("braze","Braze","https://www.braze.com","自定义定价",False,["客户互动","移动营销","个性化","AI","生命周期"],"Braze是全球领先的客户互动平台，帮助品牌通过AI驱动的个性化体验建立持久客户关系。"),
    ("attentive","Attentive","https://www.attentive.com","自定义定价",False,["短信营销","电商","个性化","AI","美国"],"Attentive是美国领先的个性化短信营销平台，利用AI分析购物行为并发送精准营销短信。"),
    ("emotive","Emotive","https://www.emotive.io","自定义定价",False,["短信营销","电商","对话","AI","转化"],"Emotive专注电商对话式短信营销，通过AI驱动的双向对话提升客户参与度和转化率。"),
    ("postscript","Postscript","https://www.postscript.io","$25/月起",False,["短信营销","Shopify","电商","自动化","合规"],"Postscript是Shopify商家首选的短信营销平台，提供AI驱动的列表增长和自动化消息流。"),
    ("smsbump","SMSBump (Yotpo)","https://smsbump.com","$19/月起",False,["短信营销","Shopify","电商","自动化","MMS"],"SMSBump现为Yotpo旗下，是Shopify生态中最强大的短信营销工具，支持AI自动化和MMS消息。"),
    ("yotpo","Yotpo","https://www.yotpo.com","自定义定价",False,["用户评价","UGC","电商","AI","忠诚度"],"Yotpo是电商营销平台，整合用户评价、UGC、短信和忠诚度计划，利用AI提升社交证明。"),
    ("okendo","Okendo","https://www.okendo.io","自定义定价",False,["用户评价","UGC","Shopify","电商","评价"],"Okendo是高性能电商评价平台，帮助企业收集和展示高质量客户评价，增强购买信心。"),
    ("stamped","Stamped.io","https://stamped.io","$23/月起",False,["评价","UGC","忠诚度","推荐","Shopify"],"Stamped.io提供电商评价、UGC、忠诚度和推荐计划，利用AI分析客户反馈并优化营销策略。"),
    ("judge-me","Judge.me","https://judge.me","$15/月起",False,["产品评价","Shopify","照片评价","SEO","UGC"],"Judge.me是Shopify上最受欢迎的产品评价应用，支持照片评价、问答和富媒体UGC展示。"),
    ("loox","Loox","https://loox.app","$9.99/月起",False,["照片评价","Shopify","推荐","社交证明","UGC"],"Loox专注收集和展示视觉化产品评价，通过照片评价和推荐计划提升电商转化率。"),
    ("smile-io","Smile.io","https://smile.io","$49/月起",False,["忠诚度","推荐","电商","奖励","VIP"],"Smile.io是电商忠诚度计划平台，帮助企业创建积分、推荐和VIP计划，提升客户终身价值。"),
    ("loyaltylion","LoyaltyLion","https://loyaltylion.com","$159/月起",False,["忠诚度","电商","个性化","数据","留存"],"LoyaltyLion是数据驱动的电商忠诚度平台，利用AI分析客户行为并创建个性化奖励计划。"),
    ("referralcandy","ReferralCandy","https://www.referralcandy.com","$59/月起",False,["推荐营销","电商","口碑","自动化","追踪"],"ReferralCandy帮助电商企业建立自动化推荐计划，通过口碑营销获取新客户并激励现有客户分享。"),
    ("friendbuy","Friendbuy","https://friendbuy.com","自定义定价",False,["推荐","忠诚度","电商","SaaS","分析"],"Friendbuy提供企业级推荐和忠诚度解决方案，利用AI优化推荐奖励并追踪全渠道推荐效果。"),
    ("talkable","Talkable","https://www.talkable.com","自定义定价",False,["推荐营销","电商","A/B测试","欺诈检测","ROI"],"Talkable是高级推荐营销平台，提供A/B测试、欺诈检测和ROI追踪，帮助企业最大化推荐价值。"),
    ("extole","Extole","https://extole.com","自定义定价",False,["推荐","倡导","电商","SaaS","全渠道"],"Extole是企业级倡导营销平台，帮助品牌将客户转化为倡导者，通过推荐和分享实现增长。"),
    ("ambassador","Ambassador","https://getambassador.com","自定义定价",False,["推荐","联盟","影响者","B2B","SaaS"],"Ambassador提供推荐、联盟和影响者营销解决方案，利用AI追踪和优化合作伙伴绩效。"),
    ("influencer","Influencer","https://influencer.com","自定义定价",False,["影响者营销","社交","品牌","AI","数据分析"],"Influencer是领先的影响者营销平台，利用AI匹配品牌与合适的影响者，并追踪 campaign 效果。"),
    ("aspireiq","AspireIQ","https://aspireiq.com","自定义定价",False,["影响者","创作者","品牌","CRM","分析"],"AspireIQ是创作者关系管理平台，帮助品牌发现、管理和分析创作者合作，构建长期品牌社群。"),
    ("upfluence","Upfluence","https://upfluence.com","自定义定价",False,["影响者","联盟","电商","数据分析","AI"],"Upfluence集影响者发现和联盟营销于一体，利用AI分析社交数据找到最佳品牌合作伙伴。"),
    ("creatoriq","CreatorIQ","https://creatoriq.com","自定义定价",False,["影响者","企业","数据分析","安全","合规"],"CreatorIQ是企业级影响者营销平台，提供AI驱动的创作者发现、欺诈检测和ROI测量。"),
    ("grin","Grin","https://grin.co","自定义定价",False,["影响者","电商","DTC","管理","报告"],"Grin专注DTC电商影响者营销，提供全流程创作者管理工具，从发现到报告一站式解决。"),
    ("klear","Klear","https://klear.com","自定义定价",False,["影响者","分析","社交监听","AI","发现"],"Klear是AI驱动的影响者营销平台，提供深度社交分析和智能匹配，帮助品牌找到最佳创作者。"),
    ("hypeauditor","HypeAuditor","https://hypeauditor.com","$399/月起",False,["影响者","欺诈检测","受众分析","AI","Instagram"],"HypeAuditor使用AI进行影响者欺诈检测和受众真实性分析，帮助品牌避免虚假粉丝陷阱。"),
    ("modash","Modash","https://modash.io","$120/月起",False,["影响者","发现","监控","TikTok","Instagram"],"Modash提供影响者发现、监控和受众分析工具，覆盖TikTok、Instagram和YouTube平台。"),
    ("heepsy","Heepsy","https://heepsy.com","$49/月起",False,["影响者","发现","分析","Instagram","TikTok"],"Heepsy是直观的影响者搜索和分析平台，利用AI筛选真实创作者并提供详细受众数据。"),
    ("social-blade","Social Blade","https://socialblade.com","免费 + $9.99/月",True,["社交分析","YouTube","Twitch","Instagram","统计"],"Social Blade提供社交媒体统计和分析，帮助用户追踪YouTube、Twitch等平台的增长趋势。"),
    ("sprout-social","Sprout Social","https://sproutsocial.com","$249/月起",False,["社交管理","发布","分析","监听","CRM"],"Sprout Social是企业级社交媒体管理平台，利用AI进行情感分析和最佳发布时间推荐。"),
    ("hootsuite","Hootsuite","https://hootsuite.com","$99/月起",False,["社交管理","发布","监听","分析","AI"],"Hootsuite是老牌社交媒体管理工具，提供AI辅助内容创作、社交监听和团队协作功能。"),
    ("buffer","Buffer","https://buffer.com","免费 + $6/月",True,["社交发布","排期","分析","AI","团队协作"],"Buffer是简洁的社交媒体管理工具，利用AI推荐最佳发布时间并简化内容排期流程。"),
    ("later","Later","https://later.com","免费 + $16.67/月",True,["视觉社交","Instagram","排期","分析","创作者"],"Later专注视觉化社交媒体管理，提供AI辅助的Instagram排期、标签建议和内容规划。"),
    ("planoly","Planoly","https://www.planoly.com","$13/月起",False,["视觉规划","Instagram","Pinterest","排期","分析"],"Planoly帮助创作者和品牌 visually 规划社交媒体内容，提供拖放式排期和AI标签建议。"),
    ("tailwind","Tailwind","https://www.tailwindapp.com","$12.99/月起",False,["Pinterest","Instagram","排期","AI","电商"],"Tailwind是Pinterest和Instagram官方合作伙伴，提供AI智能排期和Hashtag建议，专注视觉营销。"),
    ("creator-studio","Creator Studio","https://business.facebook.com/creatorstudio","免费",True,["内容管理","Facebook","Instagram","货币化","分析"],"Meta Creator Studio帮助创作者管理Facebook和Instagram内容，提供发布、排期和收益分析工具。"),
    ("meta-business-suite","Meta Business Suite","https://business.facebook.com","免费",True,["Facebook","Instagram","广告","分析","消息"],"Meta Business Suite是企业免费管理Facebook和Instagram的一站式工具，集成广告管理和AI洞察。"),
    ("tiktok-creative-center","TikTok Creative Center","https://ads.tiktok.com/business/creativecenter","免费",True,["TikTok","创意","趋势","分析","灵感"],"TikTok Creative Center提供趋势洞察、创意灵感和效果分析，帮助广告主制作高转化TikTok内容。"),
    ("pinterest-trends","Pinterest Trends","https://trends.pinterest.com","免费",True,["Pinterest","趋势","搜索","灵感","规划"],"Pinterest Trends展示平台上的热门搜索和趋势，帮助品牌和创作者把握内容方向和消费者兴趣。"),
    ("google-trends","Google Trends","https://trends.google.com","免费",True,["趋势","搜索","数据","关键词","热点"],"Google Trends免费展示全球搜索趋势和热门话题，是内容策划和市场研究不可或缺的工具。"),
    ("google-analytics-4","Google Analytics 4","https://analytics.google.com","免费",True,["网站分析","用户行为","归因","AI","转化"],"GA4是Google最新一代分析工具，利用机器学习预测用户行为并提供AI驱动的洞察和异常检测。"),
    ("mixpanel","Mixpanel","https://mixpanel.com","免费 + $20/月",True,["产品分析","用户行为","漏斗","留存","AI"],"Mixpanel是产品分析领导者，利用AI进行用户行为分析、转化漏斗优化和预测性洞察。"),
    ("amplitude","Amplitude","https://amplitude.com","免费 + $49/月",True,["产品分析","实验","AI","个性化","数据"],"Amplitude提供深度产品分析和实验平台，利用AI推荐优化策略并预测用户流失风险。"),
    ("heap","Heap","https://heap.io","免费 + $3600/年",True,["产品分析","自动采集","漏斗","归因","AI"],"Heap自动捕获所有用户交互数据，利用AI进行行为分析，无需手动埋点即可获取洞察。"),
    ("hotjar","Hotjar","https://www.hotjar.com","免费 + $39/月",True,["热图","会话录制","反馈","调研","UX"],"Hotjar提供热图、会话录制和用户反馈工具，帮助理解用户行为并优化网站体验。"),
    ("crazy-egg","Crazy Egg","https://www.crazyegg.com","$24/月起",False,["热图","A/B测试","录屏","滚动图","UX"],"Crazy Egg提供热图、滚动图和A/B测试工具，利用AI分析用户注意力分布和页面优化建议。"),
    ("fullstory","FullStory","https://www.fullstory.com","自定义定价",False,["数字体验","会话回放","分析","AI","错误追踪"],"FullStory提供高保真会话回放和数字体验分析，利用AI自动发现用户痛点和转化障碍。"),
    ("mouseflow","Mouseflow","https://mouseflow.com","$31/月起",False,["热图","会话回放","表单","漏斗","反馈"],"Mouseflow提供热图、会话回放和表单分析，帮助企业识别用户流失点并优化转化路径。"),
    ("lucky-orange","Lucky Orange","https://www.luckyorange.com","$18/月起",False,["热图","聊天","调查","漏斗","分析"],"Lucky Orange整合热图、实时聊天和调查工具，提供一站式网站优化和访客互动解决方案。"),
    ("vwo","VWO","https://vwo.com","$199/月起",False,["A/B测试","个性化","热图","分析","优化"],"VWO是企业级实验和优化平台，提供A/B测试、多变量测试和AI驱动的个性化体验。"),
    ("optimizely","Optimizely","https://www.optimizely.com","自定义定价",False,["实验","个性化","CMS","AI","B2B"],"Optimizely是数字实验平台领导者，利用AI进行智能流量分配和个性化内容推荐。"),
    ("ab-tasty","AB Tasty","https://www.abtasty.com","自定义定价",False,["实验","个性化","Feature Flag","AI","优化"],"AB Tasty提供客户端和服务器端实验、个性化和Feature Flag管理，利用AI优化用户体验。"),
    ("convert","Convert.com","https://www.convert.com","$699/月起",False,["A/B测试","个性化","隐私","安全","分析"],"Convert是注重隐私的A/B测试平台，符合GDPR要求，利用AI进行智能测试和转化优化。"),
    ("unbounce","Unbounce","https://unbounce.com","$74/月起",False,["着陆页","A/B测试","AI写作","转化","弹窗"],"Unbounce是领先的AI着陆页构建器，利用Smart Builder和AI文案生成提升广告转化率。"),
    ("instapage","Instapage","https://instapage.com","$299/月起",False,["着陆页","个性化","热图","A/B测试","协作"],"Instapage提供企业级着陆页平台，利用AI实现1:1广告个性化和高级A/B测试。"),
    ("leadpages","Leadpages","https://www.leadpages.com","$37/月起",False,["着陆页","网站","弹窗","转化","AI"],"Leadpages帮助小型企业创建高转化着陆页和网站，集成AI辅助设计和转化工具。"),
    ("clickfunnels","ClickFunnels","https://www.clickfunnels.com","$97/月起",False,["销售漏斗","着陆页","电商","自动化","AI"],"ClickFunnels是销售漏斗构建先驱，提供AI驱动的漏斗模板和自动化营销工具。"),
    ("kartra","Kartra","https://home.kartra.com","$119/月起",False,["营销自动化","漏斗","会员","视频","电商"],"Kartra是全合一营销平台，集成漏斗、邮件、会员和视频托管，利用AI优化营销流程。"),
    ("kajabi","Kajabi","https://kajabi.com","$149/月起",False,["知识付费","课程","网站","营销","AI"],"Kajabi是知识创作者的首选平台，提供AI内容生成、课程构建和营销自动化功能。"),
    ("teachable","Teachable","https://teachable.com","免费 + $59/月",True,["在线课程","营销","支付","分析","AI"],"Teachable帮助创作者创建和销售在线课程，提供AI辅助的课程内容建议和营销工具。"),
    ("thinkific","Thinkific","https://www.thinkific.com","免费 + $36/月",True,["在线课程","网站","社区","AI","分析"],"Thinkific提供灵活的在线课程平台，集成AI内容推荐和社区建设工具，支持多种商业模式。"),
    ("podia","Podia","https://www.podia.com","$39/月起",False,["数字产品","课程","社区","邮件","AI"],"Podia帮助创作者销售课程、数字下载和社区会员，提供简洁的AI营销和内容工具。"),
    ("gumroad","Gumroad","https://gumroad.com","免费 + 10%抽成",True,["数字产品","创作者","电商","AI","简单"],"Gumroad是创作者经济平台，帮助创作者轻松销售数字产品，提供AI辅助的定价和营销建议。"),
    ("stripe","Stripe","https://stripe.com","按交易付费",True,["支付","订阅","发票","金融","API"],"Stripe是全球领先的支付基础设施，利用AI进行欺诈检测、收入优化和订阅管理。"),
    ("paypal","PayPal","https://www.paypal.com","按交易付费",True,["支付","转账","商务","安全","全球"],"PayPal是全球知名的在线支付平台，利用AI和机器学习保护交易安全并优化支付体验。"),
    ("shopify","Shopify","https://www.shopify.com","$39/月起",False,["电商","建站","POS","AI","全渠道"],"Shopify是全球领先的电商平台，集成AI驱动的库存管理、个性化推荐和营销自动化。"),
    ("woocommerce","WooCommerce","https://woocommerce.com","免费",True,["电商","WordPress","插件","开源","AI"],"WooCommerce是WordPress最流行的电商插件，通过AI扩展实现智能推荐和动态定价。"),
    ("bigcommerce","BigCommerce","https://www.bigcommerce.com","$39/月起",False,["电商","B2B","多渠道","AI","企业"],"BigCommerce是面向成长型企业的电商平台，提供AI驱动的搜索、个性化和B2B功能。"),
    ("magento","Adobe Commerce (Magento)","https://business.adobe.com/products/magento/magento-commerce.html","自定义定价",False,["电商","开源","B2B","AI","Adobe"],"Adobe Commerce原名Magento，是灵活的企业电商解决方案，集成AI实时个性化和库存管理。"),
    ("wix","Wix","https://www.wix.com","免费 + $16/月",True,["建站","电商","设计","AI","CMS"],"Wix是流行的网站构建平台，提供AI网站生成器ADI和智能设计辅助功能。"),
    ("squarespace","Squarespace","https://www.squarespace.com","$16/月起",False,["建站","设计","电商","AI","创作者"],"Squarespace以精美模板著称，集成AI设计和内容工具，帮助用户创建专业网站。"),
]

# Education tools core data
education = [
    ("khan-academy","Khan Academy","https://www.khanacademy.org","免费",True,["免费教育","数学","科学","K-12","视频"],"Khan Academy是全球知名的非营利教育平台，提供免费的世界级教育内容，涵盖数学、科学、编程和人文学科。"),
    ("khanmigo","Khanmigo","https://www.khanacademy.org/khan-labs","免费",True,["AI导师","GPT","个性化","Khan Academy","辅导"],"Khanmigo是Khan Academy的AI导师，由GPT技术驱动，提供个性化的苏格拉底式辅导和学习支持。"),
    ("duolingo","Duolingo","https://www.duolingo.com","免费 + $6.99/月",True,["语言学习","游戏化","移动","多语言","每日"],"Duolingo是全球最流行的语言学习应用，利用游戏化和间隔重复帮助用户轻松学习新语言。"),
    ("duolingo-max","Duolingo Max","https://www.duolingo.com/super","$14/月起",False,["AI对话","语言","GPT","角色扮演","解释"],"Duolingo Max集成GPT-4技术，提供AI角色扮演对话和解释答案功能，加速语言流利度提升。"),
    ("coursera","Coursera","https://www.coursera.org","免费 + $49/月",True,["在线课程","大学","学位","证书","职业"],"Coursera与全球顶尖大学和公司合作，提供数千门在线课程、专业证书和学位项目。"),
    ("coursera-plus","Coursera Plus","https://www.coursera.org/courseraplus","$59/月",False,["无限访问","证书","职业","AI","学习"],"Coursera Plus提供无限访问7000多门课程和专业证书，帮助学习者持续技能提升和职业转型。"),
    ("edx","edX","https://www.edx.org","免费 + $299/年起",True,["在线课程","大学","微学位","MIT","哈佛"],"edX由哈佛和MIT创立，提供来自140多所大学的高质量在线课程、微学位和训练营。"),
    ("udemy","Udemy","https://www.udemy.com","$10-200/课程",False,["技能","视频课程","职业","实践","多样"],"Udemy是全球最大的技能市场，提供超过20万门课程，涵盖编程、设计、商业和个人发展。"),
    ("udacity","Udacity","https://www.udacity.com","$249/月",False,["纳米学位","科技","编程","职业","项目"],"Udacity提供与行业合作的纳米学位项目，专注AI、编程、数据科学和自动驾驶等前沿技术。"),
    ("skillshare","Skillshare","https://www.skillshare.com","$32/月",False,["创意","设计","视频","社区","项目"],"Skillshare是创意学习社区，提供设计、摄影、写作和创业等领域的短视频课程和项目。"),
    ("masterclass","MasterClass","https://www.masterclass.com","$120/年",False,["名人","大师","创意","影视","体育"],"MasterClass邀请各领域大师授课，让学员向娜塔莉波特曼、戈登拉姆齐等名人学习专业技能。"),
    ("linkedin-learning","LinkedIn Learning","https://www.linkedin.com/learning","$29.99/月",False,["职业","商业","技术","证书","LinkedIn"],"LinkedIn Learning提供商业、技术和创意领域的专家课程，完成课程可添加证书到LinkedIn档案。"),
    ("pluralsight","Pluralsight","https://www.pluralsight.com","$29/月",False,["技术","编程","云","DevOps","评估"],"Pluralsight是技术技能平台，提供编程、云和网络安全课程，利用AI评估技能差距并推荐路径。"),
    ("codecademy","Codecademy","https://www.codecademy.com","免费 + $19.99/月",True,["编程","互动","初学者","职业路径","代码"],"Codecademy提供互动式编程学习，支持Python、JavaScript等语言，通过实践项目培养编程技能。"),
    ("freecodecamp","freeCodeCamp","https://www.freecodecamp.org","免费",True,["免费","编程","开源","认证","项目"],"freeCodeCamp是免费开源的编程学习平台，提供完整课程和实战项目，帮助学习者获得开发者工作。"),
    ("leetcode","LeetCode","https://leetcode.com","免费 + $35/月",True,["算法","面试","编程","竞赛","技术"],"LeetCode是全球最大的算法练习平台，帮助软件工程师准备技术面试和提升编程能力。"),
    ("hackerrank","HackerRank","https://www.hackerrank.com","免费 + $25/月",True,["编程","面试","评估","招聘","技能"],"HackerRank提供编程挑战和技能评估，被全球公司用于技术招聘和员工技能测评。"),
    ("codesignal","CodeSignal","https://codesignal.com","免费 + $19/月",True,["面试","评估","编程","技能","招聘"],"CodeSignal提供标准化技术评估和面试平台，利用AI辅助评估候选人的实际编程能力。"),
    ("datacamp","DataCamp","https://www.datacamp.com","免费 + $25/月",True,["数据科学","Python","R","SQL","交互"],"DataCamp提供交互式数据科学和AI课程，通过浏览器内编程环境学习Python、R和SQL。"),
    ("dataquest","Dataquest","https://www.dataquest.io","$49/月",False,["数据科学","项目","Python","R","职业"],"Dataquest通过项目驱动的方式教授数据科学，学习者通过完成真实项目建立作品集。"),
    ("brilliant","Brilliant.org","https://brilliant.org","$24.99/月",False,["STEM","数学","科学","互动","思维"],"Brilliant.org通过互动问题和课程教授数学、数据科学和计算机科学，培养批判性思维。"),
    ("photomath","Photomath","https://photomath.com","免费 + $9.99/月",True,["数学","拍照解题","步骤","学习","K-12"],"Photomath通过相机识别数学问题并提供详细分步解答，帮助学生学习代数、几何和微积分。"),
    ("socratic","Socratic by Google","https://socratic.org","免费",True,["AI辅导","拍照","学习","Google","多学科"],"Socratic是Google的AI学习助手，学生拍照提问即可获得AI生成的解释、视频和资源。"),
    ("quizlet","Quizlet","https://quizlet.com","免费 + $7.99/月",True,["闪卡","记忆","学习","游戏化","测试"],"Quizlet是全球领先的学习工具，提供闪卡、学习模式和游戏化测试，帮助学生记忆知识点。"),
    ("quizlet-plus","Quizlet Plus","https://quizlet.com/magic","$7.99/月",False,["AI","专家解答","记忆","学习","去广告"],"Quizlet Plus增加AI专家解答、智能评分和离线访问，提供更深入的学习支持和体验。"),
    ("chegg","Chegg","https://www.chegg.com","$14.95/月",False,["作业","辅导","教材","学习","大学生"],"Chegg为大学生提供作业帮助、在线辅导、教科书租赁和学习工具，支持学业成功。"),
    ("cheggmate","CheggMate","https://www.chegg.com/cheggmate","$14.95/月起",False,["AI辅导","GPT","个性化","学习","即时"],"CheggMate集成GPT-4技术，提供个性化AI辅导、即时解答和适应性学习计划。"),
    ("course-hero","Course Hero","https://www.coursehero.com","$14.95/月",False,["学习资料","24/7辅导","笔记","解释","大学"],"Course Hero提供数百万学习资料、24/7在线辅导和AI解释工具，帮助学生理解课程材料。"),
    ("study-com","Study.com","https://study.com","$59.99/月",False,["视频课程","学分","考试","K-12","大学"],"Study.com提供超过84000个视频课程，帮助学生备考、获得学分和完成学位要求。"),
    ("brainly","Brainly","https://brainly.com","免费 + $24/年",True,["问答","学习","社区","作业","学生"],"Brainly是全球最大的学生学习社区，学生可以提问和回答作业问题，获得同伴和专家帮助。"),
    ("kahoot","Kahoot!","https://kahoot.com","免费 + $7/月",True,["游戏化","测验","课堂","互动","教育"],"Kahoot!是全球最受欢迎的教育游戏化平台，教师和学生可以创建和参与互动测验和学习游戏。"),
    ("nearpod","Nearpod","https://nearpod.com","免费 + $10/月",True,["互动课堂","演示","评估","VR","教育"],"Nearpod将互动元素融入课堂演示，支持实时评估、VR体验和协作活动，提升学生参与度。"),
    ("pear-deck","Pear Deck","https://www.peardeck.com","免费 + $149.99/年",True,["互动","Google幻灯片","评估","课堂","参与"],"Pear Deck为Google幻灯片添加互动元素，教师可以实时了解学生理解程度并调整教学。"),
    ("flipgrid","Flipgrid","https://info.flipgrid.com","免费",True,["视频","讨论","学生","创意","社区"],"Flipgrid是微软旗下的视频讨论平台，学生通过短视频分享想法和创意，构建学习社区。"),
    ("padlet","Padlet","https://padlet.com","免费 + $8/月",True,["协作","白板","创意","教育","分享"],"Padlet是数字公告板和协作工具，教师和学生可以收集想法、作品和资源，支持多种媒体格式。"),
    ("wakelet","Wakelet","https://wakelet.com","免费",True,["内容管理","教育","收藏","故事","分享"],"Wakelet帮助教育工作者和学生收集、组织和分享网络内容，创建互动式数字故事和课程资源。"),
    ("edpuzzle","Edpuzzle","https://edpuzzle.com","免费 + $11.50/月",True,["视频","互动","课堂","评估","翻转"],"Edpuzzle让教师在任何视频中添加问题、画外音和笔记，将被动观看转化为主动学习体验。"),
    ("screencastify","Screencastify","https://www.screencastify.com","免费 + $15/年",True,["录屏","视频","教学","编辑","分享"],"Screencastify是Chrome浏览器录屏工具，教师可以轻松录制课程、提供反馈和创建翻转课堂内容。"),
    ("loom","Loom","https://www.loom.com","免费 + $12.50/月",True,["视频","异步","沟通","教学","屏幕"],"Loom让教师通过快速录制屏幕和摄像头创建视频消息，用于教学讲解、反馈和异步沟通。"),
    ("canva-education","Canva for Education","https://www.canva.com/education","免费",True,["设计","教育","模板","协作","创意"],"Canva for Education为师生提供免费设计工具，数千教育模板帮助创建演示、海报和学习材料。"),
    ("google-classroom","Google Classroom","https://classroom.google.com","免费",True,["课堂管理","作业","Google","协作","K-12"],"Google Classroom是免费课堂管理平台，与Google Workspace集成，简化作业分发、评分和沟通。"),
    ("microsoft-teams-edu","Microsoft Teams for Education","https://www.microsoft.com/education/products/teams","免费",True,["协作","课堂","Office","视频会议","作业"],"Microsoft Teams for Education提供课堂协作、作业管理和在线会议，与Office 365深度集成。"),
    ("canvas-lms","Canvas","https://www.instructure.com/canvas","自定义定价",False,["LMS","高等教育","课程","评估","K-12"],"Canvas是全球最受欢迎的学习管理系统之一，提供直观的课程设计、评估工具和移动学习支持。"),
    ("blackboard","Blackboard Learn","https://www.blackboard.com","自定义定价",False,["LMS","高等教育","企业","课程","评估"],"Blackboard Learn是历史悠久的学习管理系统，为全球高等教育机构提供全面的在线教学解决方案。"),
    ("moodle","Moodle","https://moodle.org","免费",True,["开源","LMS","社区","灵活","自定义"],"Moodle是全球最流行的开源学习管理系统，免费且高度可定制，被全球数亿用户使用。"),
    ("schoology","Schoology","https://www.schoology.com","自定义定价",False,["K-12","LMS","协作","评估","分析"],"Schoology是K-12学习管理系统，连接学生、教师和家长，提供课程管理和协作工具。"),
    ("seesaw","Seesaw","https://web.seesaw.me","免费 + $120/年",True,["K-12","作品集","家校","创意","早期"],"Seesaw帮助小学生创建数字作品集，家长实时了解学习进展，支持创意表达和反思。"),
    ("classdojo","ClassDojo","https://www.classdojo.com","免费 + $59.99/年",True,["课堂","行为","家校","社区","K-6"],"ClassDojo连接教师、学生和家长，通过正向行为激励和实时分享促进课堂社区建设。"),
    ("remind","Remind","https://www.remind.com","免费 + $10/月",True,["沟通","家校","消息","安全","K-12"],"Remind是安全的学校沟通平台，教师可以发送消息、作业提醒和公告，无需共享个人号码。"),
    ("clever","Clever","https://clever.com","免费",True,["单点登录","教育","K-12","数据","集成"],"Clever为K-12学校提供单点登录和自动 rostering，简化学生访问教育应用的管理流程。"),
    ("goguardian","GoGuardian","https://www.goguardian.com","自定义定价",False,["安全","监控","课堂","K-12","过滤"],"GoGuardian保护学生在线安全，提供课堂管理、网站过滤和心理健康监测工具。"),
    ("securly","Securly","https://www.securly.com","自定义定价",False,["安全","过滤","学生","K-12","心理健康"],"Securly提供学生安全解决方案，包括内容过滤、活动监控和AI驱动的心理健康风险预警。"),
    ("grammarly-education","Grammarly for Education","https://www.grammarly.com/education","自定义定价",False,["写作","语法","抄袭","教育","协作"],"Grammarly for Education帮助学生和教师提升写作质量，检查语法、清晰度和潜在抄袭。"),
    ("turnitin","Turnitin","https://www.turnitin.com","自定义定价",False,["抄袭检测","写作","反馈","评估","教育"],"Turnitin是全球领先的抄袭检测和写作反馈平台，帮助教育机构维护学术诚信。"),
    ("gptzero","GPTZero","https://gptzero.me","免费 + $10/月",True,["AI检测","写作","学术","ChatGPT","工具"],"GPTZero是流行的AI内容检测工具，帮助教育工作者识别学生提交内容中由AI生成的部分。"),
    ("originality-ai","Originality.ai","https://originality.ai","$14.95/月起",False,["AI检测","抄袭","内容","营销","团队"],"Originality.ai提供准确的AI内容检测和抄袭检查，适合内容营销团队和教育工作者使用。"),
    ("copyleaks","Copyleaks","https://copyleaks.com","$13.99/月起",False,["抄袭","AI检测","教育","企业","API"],"Copyleaks提供AI驱动的抄袭和AI内容检测，支持100多种语言，适合教育和企业使用。"),
    ("elicit","Elicit","https://elicit.org","免费 + $10/月",True,["研究","AI","文献","学术","分析"],"Elicit是AI研究助手，帮助研究人员搜索、分析和综合学术文献，加速科研发现过程。"),
    ("consensus","Consensus","https://consensus.app","免费 + $9.99/月",True,["搜索","科学","证据","研究","AI"],"Consensus是AI驱动的科学搜索引擎，直接回答研究问题并引用同行评审的科学论文。"),
    ("semantic-scholar","Semantic Scholar","https://www.semanticscholar.org","免费",True,["学术","AI","文献","引用","发现"],"Semantic Scholar由AI2开发，利用AI理解论文内容，提供更智能的学术文献搜索和推荐。"),
    ("researchrabbit","Research Rabbit","https://www.researchrabbit.ai","免费",True,["文献","可视化","发现","研究","AI"],"Research Rabbit帮助研究人员以可视化方式探索学术文献网络，发现相关论文和研究者。"),
    ("connected-papers","Connected Papers","https://www.connectedpapers.com","免费 + $5/月",True,["图谱","文献","可视化","研究","发现"],"Connected Papers创建学术论文的关联图谱，帮助研究者发现相关工作和研究前沿。"),
    ("inciteful","Inciteful","https://inciteful.xyz","免费",True,["文献","分析","引用","学术","网络"],"Inciteful是免费的学术文献分析工具，通过引用网络帮助研究者快速了解新领域。"),
    ("scite","Scite","https://scite.ai","$20/月起",False,["引用","智能","学术","验证","研究"],"Scite通过AI分析引用上下文，帮助研究者判断论文是被支持、对比还是提及，提升文献评估质量。"),
    ("litmaps","Litmaps","https://litmaps.com","免费 + $10/月",True,["文献","地图","发现","协作","研究"],"Litmaps帮助研究者构建文献地图，追踪研究领域的最新进展并发现关键论文。"),
    ("zotero","Zotero","https://www.zotero.org","免费",True,["文献管理","开源","引用","协作","学术"],"Zotero是免费开源的文献管理工具，帮助研究者收集、组织和引用研究资料，支持团队协作。"),
    ("mendeley","Mendeley","https://www.mendeley.com","免费",True,["文献","PDF","引用","学术","社交"],"Mendeley是Elsevier旗下的文献管理和学术社交网络，帮助研究者组织论文和发现合作机会。"),
    ("endnote","EndNote","https://endnote.com","$249.95",False,["文献管理","引用","学术","写作","专业"],"EndNote是专业的文献管理和引用工具，广泛应用于学术机构，支持数千种引用格式。"),
    ("paperpile","Paperpile","https://paperpile.com","$2.99/月",False,["文献","PDF","Google","引用","简洁"],"Paperpile是简洁的文献管理工具，与Google Docs深度集成，适合习惯云端工作的研究者。"),
    ("readcube","ReadCube Papers","https://www.papersapp.com","$3/月起",False,["文献","PDF","阅读","同步","发现"],"ReadCube Papers提供增强的PDF阅读体验和智能推荐，帮助研究者管理和发现学术文献。"),
    ("dimensions","Dimensions","https://www.dimensions.ai","免费 + 付费",True,["研究","数据","分析","资助","学术"],"Dimensions提供全面的研究数据和分析，覆盖出版物、资助、专利和临床试验，助力科研决策。"),
    ("openalex","OpenAlex","https://openalex.org","免费",True,["开放","学术","图谱","数据","API"],"OpenAlex是开放的学术图谱数据库，免费提供全球研究作品、作者和机构的关联数据。"),
    ("google-scholar","Google Scholar","https://scholar.google.com","免费",True,["学术","搜索","引用","论文","免费"],"Google Scholar是免费的学术搜索引擎，索引全球学术文献，提供引用跟踪和相关文章推荐。"),
    ("pubmed","PubMed","https://pubmed.ncbi.nlm.nih.gov","免费",True,["医学","生物","文献","NCBI","健康"],"PubMed是美国国家医学图书馆的生物医学文献数据库，提供超过3400万条生物医学引文。"),
    ("arxiv","arXiv","https://arxiv.org","免费",True,["预印本","物理","数学","计算机","开放"],"arXiv是开放获取的预印本服务器，物理学、数学和计算机科学领域的研究者免费分享论文。"),
    ("biorxiv","bioRxiv","https://www.biorxiv.org","免费",True,["生物学","预印本","开放","研究","生命科学"],"bioRxiv是生物学预印本服务器，帮助生命科学研究者快速分享发现并获得社区反馈。"),
    ("medrxiv","medRxiv","https://www.medrxiv.org","免费",True,["医学","预印本","健康","临床","开放"],"medRxiv是医学预印本服务器，支持临床研究者快速传播健康科学发现，促进医学进步。"),
    ("perplexity-edu","Perplexity for Research","https://www.perplexity.ai","免费 + $20/月",True,["研究","AI搜索","引用","学术","问答"],"Perplexity为研究者提供带引用的AI搜索，实时获取最新学术文献和可靠信息来源。"),
    ("notion-education","Notion for Education","https://www.notion.so/product/notion-for-education","免费",True,["笔记","协作","Wiki","任务","教育"],"Notion为师生提供免费工作空间，用于笔记、课程计划、项目管理和知识库建设。"),
    ("obsidian","Obsidian","https://obsidian.md","免费 + $50/年",True,["笔记","知识","双向链接","本地","思维"],"Obsidian是本地优先的笔记和知识管理工具，通过双向链接帮助用户构建思维网络。"),
    ("anki","Anki","https://apps.ankiweb.net","免费",True,["间隔重复","记忆","闪卡","开源","语言"],"Anki是强大的间隔重复记忆工具，利用算法优化复习时间，广泛用于语言学习和考试准备。"),
    ("remnote","RemNote","https://www.remnote.com","免费 + $8/月",True,["笔记","闪卡","学习","双向链接","记忆"],"RemNote将笔记和间隔重复闪卡结合，学习者可以直接从笔记创建复习卡片。"),
    ("notion-ai-edu","Notion AI for Students","https://www.notion.so/product/ai","$10/月",False,["AI写作","笔记","总结","学习","效率"],"Notion AI帮助学生快速总结笔记、生成学习大纲和撰写论文草稿，提升学习效率。"),
    ("gradescope","Gradescope","https://www.gradescope.com","免费 + 机构定价",True,["评分","评估","AI","作业","反馈"],"Gradescope利用AI辅助评分，帮助教师快速批改作业和考试，提供一致的反馈和统计。"),
    ("examsoft","ExamSoft","https://examsoft.com","自定义定价",False,["考试","评估","安全","分析","高等教育"],"ExamSoft提供安全的数字考试和评估平台，利用AI分析学生表现并提供详细学习洞察。"),
    ("proctorio","Proctorio","https://proctorio.com","自定义定价",False,["监考","在线","安全","AI","隐私"],"Proctorio提供AI驱动的在线考试监考解决方案，确保远程考试的学术诚信和安全性。"),
    ("honorlock","Honorlock","https://honorlock.com","自定义定价",False,["监考","在线","AI","检测","教育"],"Honorlock是在线监考平台，利用AI和真人监考员结合，确保远程评估的公平性和安全性。"),
    ("pearson-mylab","Pearson MyLab","https://www.pearsonmylabandmastering.com","自定义定价",False,["教材","作业","自适应","STEM","评估"],"Pearson MyLab提供自适应学习体验和个性化作业，利用AI根据学生表现调整难度和内容。"),
    ("mckinsey-academy","McKinsey Academy","https://www.mckinsey.com/capabilities/learning","自定义定价",False,["领导力","商业","企业","高管","咨询"],"McKinsey Academy提供高管领导力发展项目，结合McKinsey咨询经验培养商业领袖。"),
    ("harvard-business-publishing","Harvard Business Publishing","https://hbsp.harvard.edu","自定义定价",False,["商业","案例","高管","哈佛","管理"],"HBP提供哈佛商学院案例和文章，是全球商业教育和企业培训的核心内容来源。"),
    ("coursera-for-business","Coursera for Business","https://www.coursera.org/business","自定义定价",False,["企业","技能","培训","大学","证书"],"Coursera for Business帮助企业为员工提供世界顶尖大学的技能和学位项目，推动人才发展。"),
    ("udemy-business","Udemy Business","https://business.udemy.com","自定义定价",False,["企业","技能","LMS","分析","内容"],"Udemy Business提供企业级技能学习平台，拥有超过14000门专业课程和详细学习分析。"),
    ("linkedin-learning-business","LinkedIn Learning Business","https://business.linkedin.com/talent/learning","自定义定价",False,["企业","技能","LinkedIn","分析","LMS"],"LinkedIn Learning for Business帮助企业构建技能型组织，通过AI推荐个性化学习路径。"),
    ("skillsoft","Skillsoft","https://www.skillsoft.com","自定义定价",False,["企业","合规","领导力","IT","学习"],"Skillsoft提供企业数字学习内容，涵盖领导力、技术和合规培训，支持职业发展。"),
    ("cornerstone","Cornerstone OnDemand","https://www.cornerstoneondemand.com","自定义定价",False,["人才","学习","绩效","招聘","AI"],"Cornerstone是全方位人才管理平台，利用AI推荐学习内容并追踪技能发展和职业路径。"),
    ("docebo","Docebo","https://www.docebo.com","自定义定价",False,["LMS","企业","AI","社交","移动"],"Docebo是企业LMS平台，利用AI进行内容推荐和学习路径个性化，支持正式和非正式学习。"),
    ("360learning","360Learning","https://360learning.com","自定义定价",False,["协作","创作","企业","LMS","内训"],"360Learning专注协作式学习，让内部专家轻松创建课程，利用AI优化学习体验和效果。"),
    ("lessonly","Lessonly (Seismic)","https://seismic.com/lessonly","自定义定价",False,["培训","客服","销售","练习","模拟"],"Lessonly提供培训练习和模拟工具，帮助客服和销售团队通过场景练习提升技能。"),
    ("articulate-360","Articulate 360","https://articulate.com/360","$1399/年",False,["电子学习","课程","创作","互动","企业"],"Articulate 360是领先的电子学习内容创作套件，帮助教学设计者创建专业互动课程。"),
    ("adobe-captivate","Adobe Captivate","https://www.adobe.com/products/captivate.html","$33.99/月",False,["电子学习","互动","模拟","视频","创作"],"Adobe Captivate是高级电子学习创作工具，支持VR体验和软件模拟，适合复杂培训内容。"),
    ("ispring","iSpring Suite","https://www.ispringsolutions.com","$470/年",False,["PPT","电子学习","测验","视频","企业"],"iSpring Suite将PowerPoint转化为互动电子课程，提供测验、录屏和对话模拟功能。"),
    ("rise-360","Rise 360","https://articulate.com/360/rise","$1399/年",False,["响应式","课程","创作","协作","云"],"Rise 360是云端响应式课程创作工具，无需编程即可创建适配所有设备的精美课程。"),
    ("elucidat","Elucidat","https://www.elucidat.com","自定义定价",False,["企业","电子学习","规模化","分析","品牌"],"Elucidat帮助企业规模化创建高质量电子学习，利用AI优化内容并追踪学习效果。"),
    ("gomo-learning","Gomo Learning","https://www.gomolearning.com","自定义定价",False,["响应式","多语言","云端","协作","电子学习"],"Gomo提供云端响应式和多语言电子学习创作，支持团队协作和一键发布到LMS。"),
    ("lms365","LMS365","https://lms365.com","自定义定价",False,["Microsoft 365","LMS","Teams","SharePoint","企业"],"LMS365是Microsoft 365集成的LMS，在Teams和SharePoint中提供完整的学习管理功能。"),
    ("open-edx","Open edX","https://open.edx.org","免费",True,["开源","MOOC","平台","大学","自定义"],"Open edX是哈佛和MIT开源的MOOC平台，全球顶尖大学和企业用于创建大规模在线课程。"),
    ("moodle-workplace","Moodle Workplace","https://moodle.com/workplace","自定义定价",False,["企业","LMS","合规","入职","培训"],"Moodle Workplace是基于Moodle的企业学习平台，专注员工培训、合规和入职管理。"),
    ("totara","Totara Learn","https://www.totaralearn.com","自定义定价",False,["开源","企业","LMS","绩效","合规"],"Totara Learn是面向企业培训的开源LMS，提供绩效管理、合规追踪和社交学习功能。"),
    ("chamilo","Chamilo","https://chamilo.org","免费",True,["开源","LMS","协作","e-portfolio","教育"],"Chamilo是开源学习管理系统，专注于易用性和协作学习，适合中小型教育机构。"),
    ("sakai","Sakai","https://www.sakaiproject.org","免费",True,["开源","LMS","高等教育","协作","研究"],"Sakai是高等教育开源协作和学习环境，由全球大学共同开发和维护。"),
    ("d2l-brightspace","D2L Brightspace","https://www.d2l.com","自定义定价",False,["LMS","K-12","高等教育","企业","AI"],"D2L Brightspace是创新学习平台，利用AI提供个性化学习路径和预测分析支持学生成功。"),
    ("itslearning","itslearning","https://itslearning.com","自定义定价",False,["K-12","LMS","计划","评估","协作"],"itslearning是专为K-12设计的LMS，帮助教师简化课程计划、作业管理和家校沟通。"),
    ("powerschool","PowerSchool","https://www.powerschool.com","自定义定价",False,["K-12","SIS","成绩","管理","分析"],"PowerSchool是北美最大的K-12学生信息系统，管理成绩、出勤和学生数据，支持学区运营。"),
    ("infinite-campus","Infinite Campus","https://www.infinitecampus.com","自定义定价",False,["SIS","K-12","成绩","管理","沟通"],"Infinite Campus提供全面的K-12学生信息和管理系统，支持成绩、出勤和家校沟通。"),
    ("tynker","Tynker","https://www.tynker.com","免费 + $120/年",True,["编程","儿童","游戏","STEM","创意"],"Tynker教儿童通过游戏化方式学习编程，支持从图形化编程到Python和JavaScript过渡。"),
    ("scratch","Scratch","https://scratch.mit.edu","免费",True,["编程","儿童","MIT","创意","社区"],"Scratch是MIT开发的图形化编程工具，全球儿童通过拖拽积木创造互动故事和游戏。"),
    ("scratchjr","ScratchJr","https://www.scratchjr.org","免费",True,["编程","幼儿","平板","创意","学前"],"ScratchJr是5-7岁儿童的图形化编程应用，在平板设备上创造故事和游戏，培养计算思维。"),
    ("code-org","Code.org","https://code.org","免费",True,["编程","K-12","计算机","活动","公益"],"Code.org是计算机科学教育非营利组织，提供免费的编程课程和全球Hour of Code活动。"),
    ("blockly","Blockly","https://developers.google.com/blockly","免费",True,["编程","可视化","Google","教育","开源"],"Blockly是Google开源的可视化编程库，被众多教育工具采用作为图形化编程基础。"),
    ("makecode","MakeCode","https://makecode.microbit.org","免费",True,["编程","硬件","micro:bit","游戏","教育"],"Microsoft MakeCode支持micro:bit和Arcade等硬件编程，通过图形化和文本代码学习物理计算。"),
    ("microbit","micro:bit","https://microbit.org","$20设备",True,["硬件","编程","物理","STEM","创意"],"micro:bit是掌上可编程计算机，帮助学生学习编程和物理计算，全球数千万学生使用。"),
    ("arduino-edu","Arduino Education","https://www.arduino.cc/education","自定义定价",False,["硬件","编程","STEM","机器人","电子"],"Arduino Education提供教育套件和课程，帮助学生通过动手实践学习电子和编程。"),
    ("raspberry-pi","Raspberry Pi","https://www.raspberrypi.org","$35设备",True,["硬件","编程","Linux","创客","教育"],"Raspberry Pi是低成本微型计算机，广泛用于学校教授编程、电子和计算机科学。"),
    ("lego-education","LEGO Education","https://education.lego.com","自定义定价",False,["积木","机器人","STEM","动手","K-12"],"LEGO Education将乐高积木与教育结合，通过SPIKE Prime等机器人套装教授STEM概念。"),
    ("sphero","Sphero","https://www.sphero.com","自定义定价",False,["机器人","编程","STEM","球","创意"],"Sphero是可编程机器人球，帮助学生在游戏和创造中学习编程、物理和工程概念。"),
    ("ozobot","Ozobot","https://ozobot.com","$99设备",False,["机器人","编程","颜色","K-8","STEM"],"Ozobot是小型编程机器人，通过颜色代码和图形化编程教授K-8学生计算思维。"),
    ("dash-dot","Dash & Dot","https://www.makewonder.com","自定义定价",False,["机器人","编程","儿童","故事","STEM"],"Wonder Workshop的Dash和Dot机器人帮助儿童学习编程，通过挑战和故事培养解决问题能力。"),
    ("kibo","KIBO","https://kinderlabrobotics.com","$199设备",False,["机器人","编程","幼儿","无屏幕","STEM"],"KIBO是无屏幕编程机器人，幼儿通过 wooden 积木学习编程基础，无需屏幕或阅读。"),
    ("mathletics","Mathletics","https://www.mathletics.com","$14/月",False,["数学","游戏","K-12","评估","个性化"],"Mathletics是数学学习平台，通过互动活动和游戏帮助学生掌握数学概念，提供个性化学习路径。"),
    ("ixl","IXL","https://www.ixl.com","$9.95/月起",False,["K-12","数学","语言","科学","自适应"],"IXL提供K-12自适应学习，涵盖数学、语言艺术、科学和社会研究，实时调整难度。"),
    ("khan-kids","Khan Academy Kids","https://learn.khanacademy.org/khan-kids","免费",True,["幼儿","阅读","数学","游戏","早期"],"Khan Academy Kids为2-8岁儿童提供免费早期教育应用，涵盖阅读、数学和社会情感学习。"),
    ("abcmouse","ABCmouse","https://www.abcmouse.com","$12.99/月",False,["幼儿","阅读","数学","艺术","早期"],"ABCmouse是综合早期学习学院，涵盖阅读、数学、科学和艺术，适合2-8岁儿童。"),
    ("reading-eggs","Reading Eggs","https://readingeggs.com","$9.99/月",False,["阅读","拼写","数学","儿童","游戏"],"Reading Eggs通过游戏化课程教儿童阅读和拼写，拥有超过3000本在线书籍和互动活动。"),
    ("epic","Epic!","https://www.getepic.com","免费 + $11.99/月",True,["阅读","图书","儿童","音频","教育"],"Epic是全球最大的儿童数字图书馆，提供超过40000本高质量图书、音频书和学习视频。"),
    ("newsela","Newsela","https://newsela.com","自定义定价",False,["新闻","阅读","分级","K-12","时事"],"Newsela将真实新闻调整为五个阅读级别，帮助不同水平的学生理解时事并提升阅读能力。"),
    ("commonlit","CommonLit","https://www.commonlit.org","免费",True,["阅读","文学","K-12","评估","免费"],"CommonLit是免费数字阅读和写作平台，提供分级文学资源和评估工具支持读写教学。"),
    ("achieve3000","Achieve3000","https://www.achieve3000.com","自定义定价",False,["阅读","差异化","写作","评估","K-12"],"Achieve3000提供差异化读写教学，根据学生水平自动调整文章内容和评估难度。"),
    ("lexia","Lexia Learning","https://www.lexialearning.com","自定义定价",False,["读写","干预","评估","K-12","自适应"],"Lexia提供读写能力评估和干预方案，利用自适应技术识别学习差距并提供个性化指导。"),
    ("raz-plus","Raz-Plus","https://www.learninga-z.com","$109.95/年",False,["阅读","分级","K-5","评估","教学"],"Raz-Plus提供分级阅读资源和教学工具，帮助教师差异化教学并追踪学生阅读进步。"),
    ("reading-a-z","Reading A-Z","https://www.readinga-z.com","$109.95/年",False,["阅读","资源","分级","K-5","教师"],"Reading A-Z提供大量分级阅读资源和教学材料，是全球教师广泛使用的阅读教学工具。"),
    ("headsprout","Headsprout","https://www.headsprout.com","自定义定价",False,["阅读","早期","互动","K-5","基础"],"Headsprout通过互动在线课程教授阅读基础技能，适合早期和 struggling readers。"),
    ("dreambox","DreamBox Learning","https://www.dreambox.com","自定义定价",False,["数学","自适应","K-8","游戏","数据"],"DreamBox是K-8自适应数学学习平台，利用AI实时分析学生策略并调整学习路径。"),
    ("prodigy","Prodigy Math","https://www.prodigygame.com","免费 + $8.33/月",True,["数学","游戏","K-8","角色扮演","自适应"],"Prodigy将数学练习融入角色扮演游戏，通过自适应问题保持学生参与和学习动力。"),
    ("st-math","ST Math","https://www.stmath.com","自定义定价",False,["数学","视觉","K-8","JiJi","认知"],"ST Math通过视觉 puzzle 和游戏教授数学概念，无需阅读即可学习，适合所有语言背景。"),
    ("zearn","Zearn","https://www.zearn.org","免费",True,["数学","K-5","教学","数字","补充"],"Zearn是K-5数学补充学习平台，与 Eureka Math 对齐，提供数字课程和练习。"),
    ("khan-mastery","Khan Academy Mastery","https://www.khanacademy.org","免费",True,["掌握","个性化","进度","练习","徽章"],"Khan Academy掌握系统允许学生按自己节奏学习，获得即时反馈和个性化练习推荐。"),
    ("coursera-guided","Coursera Guided Projects","https://www.coursera.org/browse/guided-projects","$9.99",False,["项目","实践","云端","快速","技能"],"Coursera Guided Projects在浏览器云端环境中提供2小时实践项目，快速学习具体技能。"),
    ("udemy-lab","Udemy Labs","https://www.udemy.com","$10-50",False,["实践","编程","云端","项目","技能"],"Udemy Labs提供浏览器内编程环境，学习者无需配置即可练习代码和完成项目。"),
    ("qwiklabs","Qwiklabs","https://www.qwiklabs.com","$1-15/实验",True,["云","Google","AWS","实验","实践"],"Qwiklabs提供真实云环境实验，学习者在临时云中练习Google Cloud和AWS技能。"),
    ("acloudguru","A Cloud Guru","https://acloudguru.com","$35/月",False,["云","AWS","Azure","DevOps","实践"],"A Cloud Guru提供云技术实践培训，通过动手实验和沙盒环境掌握AWS和Azure。"),
    ("cloudacademy","CloudAcademy","https://cloudacademy.com","$59/月",False,["云","DevOps","安全","技能","评估"],"CloudAcademy提供云、DevOps和安全培训，利用技能评估定制个性化学习路径。"),
    ("whizlabs","Whizlabs","https://www.whizlabs.com","$15-100",False,["认证","云","Java","PM","模拟"],"Whizlabs提供IT认证备考材料和模拟测试，帮助考生通过AWS、Azure和Java等认证。"),
    ("linux-academy","Linux Foundation Training","https://www.linuxfoundation.org/training","$299-500",False,["开源","Linux","云原生","Kubernetes","认证"],"Linux Foundation提供开源技术培训，包括Linux、Kubernetes和云原生技术认证课程。"),
    ("red-hat-training","Red Hat Training","https://www.redhat.com/training","自定义定价",False,["Linux","企业","开源","认证","DevOps"],"Red Hat Training提供企业级开源技术培训，帮助IT专业人员获得红帽认证。"),
    ("vmware-edu","VMware Education","https://www.vmware.com/education.html","自定义定价",False,["虚拟化","云","企业","认证","IT"],"VMware Education提供虚拟化和云计算培训，帮助IT专业人员掌握企业基础设施技术。"),
    ("cisco-learning","Cisco Learning Network","https://learningnetwork.cisco.com","免费 + 付费",True,["网络","Cisco","认证","社区","IT"],"Cisco Learning Network提供免费学习资源、社区支持和认证备考材料，培养网络专业人才。"),
    ("juniper-edu","Juniper Open Learning","https://www.juniper.net/us/en/training/open-learning.html","免费",True,["网络","Juniper","认证","免费","IT"],"Juniper Open Learning提供免费网络课程和认证考试券，帮助学习者进入网络行业。"),
    ("paloalto-edu","Palo Alto Networks Academy","https://www.paloaltonetworks.com/services/education","免费",True,["安全","网络","防火墙","认证","IT"],"Palo Alto Networks Academy提供网络安全教育，帮助培养下一代网络安全专业人才。"),
    ("fortinet-training","Fortinet Training Institute","https://www.fortinet.com/training","免费 + 付费",True,["安全","网络","认证","NSE","IT"],"Fortinet Training Institute提供免费网络安全培训和NSE认证，应对全球网络安全人才缺口。"),
    ("comptia","CompTIA CertMaster","https://www.comptia.org","$139-499",False,["IT","认证","基础","安全","网络"],"CompTIA提供IT基础认证如A+、Network+和Security+，是IT职业入门的黄金标准。"),
    ("isc2","ISC2","https://www.isc2.org","免费 + $749",True,["安全","CISSP","CSSLP","认证","专业"],"ISC2是全球领先的网络安全认证机构，CISSP是网络安全领域最受认可的认证之一。"),
    ("eccouncil","EC-Council","https://www.eccouncil.org","$950-2200",False,["安全","CEH","道德黑客","认证","网络"],"EC-Council提供CEH等网络安全认证，培养道德黑客和网络安全防御专业人才。"),
    ("offsec","Offensive Security","https://www.offensive-security.com","$1499-4500",False,["安全","渗透测试","OSCP","Kali","高级"],"Offensive Security提供高级渗透测试培训，OSCP是网络安全行业最实践导向的认证。"),
    ("sans","SANS Institute","https://www.sans.org","$8000-9000",False,["安全","高级","培训","GIAC","网络"],"SANS Institute提供世界顶级网络安全培训，GIAC认证是行业公认的高级技能证明。"),
    ("cissp","CISSP","https://www.isc2.org/Certifications/CISSP","$749",False,["安全","管理","高级","认证","ISC2"],"CISSP是信息安全管理和领导力的顶级认证，证明持有者在安全领域的全面知识和经验。"),
    ("pmp","PMP Certification","https://www.pmi.org/certifications/project-management-pmp","$555",False,["项目管理","PMI","职业","认证","标准"],"PMP是项目管理领域全球公认的专业认证，证明项目经理具备领导和指导项目的能力。"),
    ("pmi-acp","PMI-ACP","https://www.pmi.org/certifications/agile-certification","$495",False,["敏捷","项目管理","Scrum","PMI","认证"],"PMI-ACP是敏捷认证从业者，证明在敏捷原则、实践和工具方面的知识和专业技能。"),
    ("safe","SAFe","https://www.scaledagile.com","自定义定价",False,["敏捷","规模化","企业","框架","培训"],"SAFe是规模化敏捷框架，帮助大型组织实施敏捷实践，提供认证和培训体系。"),
    ("scrum-alliance","Scrum Alliance","https://www.scrumalliance.org","自定义定价",False,["Scrum","敏捷","认证","CSM","团队"],"Scrum Alliance是Scrum认证先驱，提供CSM等认证和持续教育资源，促进敏捷社区发展。"),
    ("scrum-org","Scrum.org","https://www.scrum.org","自定义定价",False,["Scrum","敏捷","PSM","专业","认证"],"Scrum.org由Ken Schwaber创立，提供专业Scrum认证和评估，标准严格且全球认可。"),
    ("togaf","TOGAF","https://www.opengroup.org/togaf","$360",False,["企业架构","标准","框架","认证","Open Group"],"TOGAF是企业架构开发方法论和框架标准，帮助组织设计、规划和实施企业架构。"),
    ("itil","ITIL 4","https://www.axelos.com/certifications/itil-service-management","$500",False,["IT服务","管理","框架","最佳实践","认证"],"ITIL是全球IT服务管理最佳实践框架，ITIL 4增加敏捷和DevOps元素适应现代IT环境。"),
]

# Generate JSON
all_tools = []

for idx, raw in enumerate(marketing[:100]):
    tool = generate_tool(idx, raw, "ai-marketing")
    all_tools.append(tool)

for idx, raw in enumerate(education[:100]):
    tool = generate_tool(idx, raw, "ai-education")
    all_tools.append(tool)

with open("/workspace/data/tools-batch-5.json", "w", encoding="utf-8") as f:
    json.dump(all_tools, f, ensure_ascii=False, indent=2)

print(f"Generated {len(all_tools)} tools to /workspace/data/tools-batch-5.json")
